- README.md
- README.md describes overview of expected usage.
> Setup repository and describe overview

- README.md
- bin/run-test.sh
- bin/run.sh
And update commends and README.md.
> [CircleCI] delete "set +e" to stop process if instance setup is failed

- README.md
- bin/run.sh
- docs/cicd.md
- docs/deploy.md
- docs/manifests.md
- test/setup.go
- Split topics by different file.
- Explain deployment/release procedure in deploy.md.
> Improve neco-ops documents

- coil/base/daemonset.yaml
- coil/base/deployment.yaml
- egress/base/squid-deployment.yaml
- egress/base/unbound-deployment.yaml
- egress/test/unbound.go
- monitoring/base/alertmanager/deployment.yaml
- monitoring/base/kube-state-metrics/deployment.yaml
- monitoring/base/machines-endpoints/cronjob.yaml
- monitoring/base/prometheus/deployment.yaml
- test/install.yaml
related: https://github.com/cybozu/neco-containers/pull/147
> Update container tags

- metallb/base/deployment.yaml
- metallb/test/metallb.go
- monitoring/base/machines-endpoints/cronjob.yaml
- test/README.md
To support `externalTrafficPolicy=Local`, speaker Pod need to be run on all nodes.
https://metallb.universe.tf/usage/#bgp
> [metallb] deploy speaker as DaemonSet

- monitoring/base/prometheus/prometheus.yaml
Monitor-hw is exported port number 9105.
Prometheus goes to see its exported targets.
> [monitor-hw] Add monitoer-hw-endpoint

- .circleci/config.yml
and change the instance type to "n1-standard-64".
> [gcp] use Ubuntu based vmx-enabled image

- monitoring/base/machines-endpoints/cronjob.yaml
- monitoring/base/prometheus/alert_rules.yaml
- monitoring/base/prometheus/prometheus.yaml
- monitoring/base/prometheus/test_rules.yaml
- test/Makefile
- test/monitoring_test.go
Add `make test-alert-rules` for the prometheus alert unit test.
> [monitoring] Add new alert rules for etcd DB usage

- test/setup_test.go
> [setup] check no operation is running

- teleport/base/clusterrole.yaml
- teleport/base/kustomization.yaml
This pull request made the following change.
- add a cluster role for general Neco users
> [teleport] add custom admin cluster role

- argocd-config/base/argocd.yaml
- argocd-config/base/elastic.yaml
- argocd-config/base/external-dns.yaml
- argocd-config/base/gatekeeper.yaml
- argocd-config/base/ingress.yaml
- argocd-config/base/metallb.yaml
- argocd-config/base/monitoring.yaml
- argocd-config/base/network-policy.yaml
- argocd-config/base/team-management.yaml
- argocd-config/base/teleport.yaml
- argocd-config/base/topolvm.yaml
- argocd/base/crd.yaml
- argocd/base/deployment.yaml
- teleport/overlays/gcp/deployment.yaml
- test/Makefile
The self-healing solves OutOfSync automatically.
It expects automatically re-sync by Argo CD feature of v1.2.0.
- Apply https://github.com/argoproj/argo-cd/blob/v1.2.0-rc2/manifests/install.yaml
- Add `selfHeal: true` to all apps.
- Fix manifests with kustomize 3.1.0 which is included in argocd 1.2.0-rc2.
> [argocd] Update version to v1.2.0-rc2 and enable self-healing

- argocd-config/overlays/osaka0/external-dns.yaml
- argocd-config/overlays/osaka0/kustomization.yaml
- argocd-config/overlays/osaka0/metallb.yaml
- argocd-config/overlays/osaka0/monitoring.yaml
- argocd-config/overlays/osaka0/teleport.yaml
- external-dns/overlays/osaka0/external-dns/deployment.yaml
- external-dns/overlays/osaka0/kustomization.yaml
- metallb/overlays/osaka0/configmap.yaml
- metallb/overlays/osaka0/kustomization.yaml
- monitoring/overlays/osaka0/alertmanager/env.template
- monitoring/overlays/osaka0/grafana/ingressroute.yaml
- monitoring/overlays/osaka0/grafana/statefulset.yaml
- monitoring/overlays/osaka0/kustomization.yaml
- monitoring/overlays/osaka0/prometheus/statefulset.yaml
- teleport/overlays/osaka0/certificate.yaml
- teleport/overlays/osaka0/kustomization.yaml
https://github.com/cybozu-go/neco/issues/519
> Add osaka0 overlays

- test/setup_test.go
Teleport Enterprise is already deployed on stage0.
It should move to the block !doUpgrade.
> Fix teleport license deployment test

- test/gatekeeper_test.go
- test/reboot_test.go
https://github.com/cybozu-go/neco/issues/576
> Improve gatekeeper test to wait for ready

- monitoring/base/prometheus/statefulset.yaml
refer to the link https://github.com/helm/charts/blob/f5bcdc1c4e6c039cfd28184f2ed00f0f38470771/stable/prometheus/templates/server-deployment.yaml#L97-L108
> [monitoring] Add readiness/liveness probe for Prometheus

- monitoring/base/grafana/configmap.yaml
- monitoring/base/grafana/dashboards/all_nodes.json
- monitoring/base/grafana/dashboards/cpu_usage.json
- monitoring/base/grafana/dashboards/memory_usage.json
- monitoring/base/grafana/statefulset.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/prometheus.yaml
- test/monitoring_test.go
https://github.com/cybozu-go/neco/issues/570
In addition to the above issue, remove port number from "__address__" label value.
> Add the dashboard to grasp the usage of computing resource is appropriate or not

- .circleci/config.yml
- bin/run-kindtest.sh
- network-policy/overlays/kind/global-policies/network-set.yaml
- test/Makefile
It allows developer to debug on the instance if CI is failed.
> Run kindtest on GCE instance

- argocd/base/service.yaml
We need an IP address for the bastion network...
> argocd: Fix address pool

- argocd-config/base/secrets.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/namespaces.yaml
- argocd/base/deployment.yaml
Also fix stage0 overlay for namespace App does not refer stage revision.
> argocd: Update to 1.2.2.2

- monitoring/base/prometheus/alert_rules/kubernetes.yaml
- monitoring/base/prometheus/alert_rules/monitoring.yaml
- monitoring/base/prometheus/alert_rules/topolvm.yaml
- monitoring/base/prometheus/prometheus.yaml
- test/alert_test/kubernetes.yaml
https://github.com/cybozu-go/neco/issues/568
- Alert if the usage of PV is over the threshold
- Alert if the usage of PV increases rapidly within a certain period of time
> prometheus: Add topolvm alert rules

- test/README.md
- test/fetch-secret.sh
Use NECO_APPS_SECRET_DIR on run tests.
> Use SECRET_DIR on test.

- team-management/base/kustomization.yaml
- team-management/base/maneki/project.yaml
- team-management/base/neco/kustomization.yaml
- team-management/base/neco/project.yaml
- test/setup_test.go
- Add an ArgoCD project for Maneki team.
- Permit just the Neco team to access the ArgoCD default project.
> ArgoCD RBAC for maneki

- test/setup_test.go
This pull request removes temporal codes as they are already useless now.
> Remove temporal codes

- monitoring/base/grafana/dashboards/contour.json
Update the "Contour" dashboard to monitor HTTPProxy metrics.
> monitoring: Update contour dashboard

- argocd-ingress/base/httpproxy.yaml
- docs/maintenance.md
- test/argocd-ingress_test.go
https://github.com/cybozu-go/neco/issues/643
> argocd-ingress: Refactor route settings in HTTPProxy

- docs/maintenance.md
- ingress/base/contour/deployment.yaml
- ingress/base/contour/upstream/02-job-certgen.yaml
- ingress/base/contour/upstream/03-contour.yaml
- ingress/base/contour/upstream/03-envoy.yaml
contour: 1.0.1.1
envoy: 1.12.2.1
> contour: update images of contour and envoy

- metallb/base/role.yaml
- test/Makefile
- test/Makefile.kindtest
- test/network-policy_test.go
- test/run_test_kind.go
- test/setup_test.go
https://github.com/cybozu-go/neco/issues/685
> Update versions for k8s 1.16

- .circleci/config.yml
- bin/commit-push.sh
- bin/run-neco-apps-secret-ci.sh
- docs/cicd.md
https://github.com/cybozu-go/neco-apps/issues/247
> Make pull request instead of merging stage automatically

- .circleci/config.yml
> Fix checking diff of create PR

- monitoring/base/alertmanager/deployment.yaml
- monitoring/base/grafana/statefulset.yaml
- monitoring/base/prometheus/statefulset.yaml
prometheus & alertmanager: quay.io/cybozu/prometheus:2.15.1.1
grafana: quay.io/cybozu/grafana:6.5.2.1
> monitoring: update images

- monitoring/base/prometheus/alert_rules/kubernetes.yaml
- monitoring/base/prometheus/prometheus.yaml
- monitoring/base/prometheus/record_rules.yaml
- test/monitoring_test.go
- Add recording rules for scheduler
- Add health check alert rules for scheduler and controller-manager
> Add recording rules for scheduler

- monitoring/base/grafana/configmap.yaml
- monitoring/base/grafana/dashboards/cert-manager.json
- monitoring/base/grafana/statefulset.yaml
- monitoring/base/kustomization.yaml
- test/monitoring_test.go
> grafana: add cert-manager dashboard

- test/local-pv-provisioner_test.go
- test/network-policy_test.go
- test/topolvm_test.go
Add a test to confirm that a local PV created by `local-pv-provisioner` can be used on a Pod.
> Add test for local-pv-provisioner

- ingress/base/template/deployment.yaml
https://github.com/cybozu-go/neco/issues/661
> Sleep in preStop hook for graceful termination

- monitoring/base/grafana/configmap.yaml
- monitoring/base/grafana/dashboards/sabakan.json
- monitoring/base/grafana/statefulset.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/alert_rules/sabakan.yaml
- monitoring/base/prometheus/prometheus.yaml
- test/monitoring_test.go
To monitor Sabakan on boot serves, add the followings:
- Grafana dashboard
- Alert rules
> Monitoring Sabakan

- monitoring/base/grafana/configmap.yaml
- monitoring/base/grafana/dashboards/all_nodes.json
- monitoring/base/grafana/dashboards/calico.json
- monitoring/base/grafana/dashboards/cert-manager.json
- monitoring/base/grafana/dashboards/contour.json
- monitoring/base/grafana/dashboards/cpu_usage.json
- monitoring/base/grafana/dashboards/envoy.json
- monitoring/base/grafana/dashboards/etcd.json
- monitoring/base/grafana/dashboards/kube-apiserver.json
- monitoring/base/grafana/dashboards/kube-controller-manager.json
- monitoring/base/grafana/dashboards/kube-scheduler.json
- monitoring/base/grafana/dashboards/kubelet.json
- monitoring/base/grafana/dashboards/kubernetes_cluster.json
- monitoring/base/grafana/dashboards/local-pv-provisioner.json
- monitoring/base/grafana/dashboards/memory_usage.json
- monitoring/base/grafana/dashboards/neco-admission.json
- monitoring/base/grafana/dashboards/sabakan.json
- monitoring/base/grafana/dashboards/topolvm_volumegroup.json
- monitoring/base/grafana/statefulset.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/alert_rules/neco-admission.yaml
- monitoring/base/prometheus/prometheus.yaml
- neco-admission/base/deployment.yaml
- test/Makefile
- test/env.go
- test/monitoring_test.go
- Add the target of neco-admission to Prometheus.
- Add the alert rules for neco-admission.
- Add the Grafana dashboard for neco-admission.
- Fix the Grafana dashboard for Sabakan.
- Add tags to dashboards.
- Add directories for dashboards.
> monitoring: add metrics setting for neco-admission.

- elastic/base/kustomization.yaml
- elastic/base/validatingwebhookconfiguration.yaml
- test/setup_test.go
> elastic: ignore caBundle field

- bmc-reverse-proxy/base/bmc-reverse-proxy/deployment.yaml
https://github.com/cybozu-go/neco/issues/748
> bmc-reverse-proxy: Update version to 0.1.2

- monitoring/base/prometheus/alert_rules/kubernetes.yaml
- secrets/base/monitoring/alertmanager.yaml
- test/alert_test/kubernetes.yaml
https://github.com/cybozu-go/neco/issues/622
> Add alert rules to detect pods which fall into a ready state abnormally

- monitoring/base/alertmanager/deployment.yaml
- secrets/base/kustomization.yaml
- test/fetch-secret.sh
This PR updates the alertmanager secret name to reflect the change in neco-apps-secret.
This PR also contains a bug fix in the CI script.
> Update alertmanager secret name

- .circleci/config.yml
- docs/cicd.md
- local-pv-provisioner/base/daemonset.yaml
- local-pv-provisioner/overlays/gcp/daemonset.yaml
- local-pv-provisioner/overlays/kind/daemonset.yaml
- test/Makefile.kindtest
- test/local-pv-provisioner_test.go
- Change the target device directory of `local-pv-provisioner`
(`/dev/crypt-disk/by-path`->`/dev/crypt-part/by-path`)
- Refactoring test for `local-pv-provisioner`
- Refactoring CI workflow
> Support SS partition

- argocd-config/base/kustomization.yaml
- argocd-config/base/metrics-server.yaml
- argocd-config/overlays/kind/kustomization.yaml
- argocd-config/overlays/kind/metrics-server.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/metrics-server.yaml
- docs/application_sync_wave.md
- docs/maintenance.md
- metrics-server/base/kustomization.yaml
- metrics-server/base/metrics-server-deployment.yaml
- metrics-server/base/metrics-server-service.yaml
- metrics-server/base/upstream/aggregated-metrics-reader.yaml
- metrics-server/base/upstream/auth-delegator.yaml
- metrics-server/base/upstream/auth-reader.yaml
- metrics-server/base/upstream/metrics-apiservice.yaml
- metrics-server/base/upstream/metrics-server-deployment.yaml
- metrics-server/base/upstream/metrics-server-service.yaml
- metrics-server/base/upstream/resource-reader.yaml
- metrics-server/overlays/kind/kustomization.yaml
- metrics-server/overlays/kind/metrics-server-deployment.yaml
- network-policy/base/kustomization.yaml
- network-policy/base/policies/kube-system.yaml
- test/bmc-reverse-proxy_test.go
- test/metrics-server_test.go
- test/monitoring_test.go
- test/suite_test.go
https://github.com/cybozu-go/neco/issues/484
> Add metrics-server

- .circleci/config.yml
> ci: fix to copy files even when CI failed.

- team-management/base/maneki/app-kodama.yaml
- team-management/base/maneki/kustomization.yaml
- team-management/base/maneki/project.yaml
> Add app-kodama namespace

- test/contour_test.go
> Debug log for contour test

- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/README.md
- monitoring/base/prometheus/alert_rules/cke.yaml
- monitoring/base/prometheus/prometheus.yaml
- network-policy/base/policies/monitoring.yaml
- test/alert_test/cke.yaml
- test/monitoring_test.go
- Add new alert severity level - `info`
- Join cke to Prometheus targets
- Add alert rules for cke
> Monitoring CKE

- metallb/base/deployment.yaml
- monitoring/overlays/osaka0/prometheus/statefulset.yaml
- monitoring/overlays/stage0/prometheus/statefulset.yaml
- monitoring/overlays/tokyo0/prometheus/statefulset.yaml
- team-management/base/maneki/app-gorush.yaml
- team-management/base/maneki/app-kodama.yaml
- team-management/base/maneki/app-misc.yaml
- team-management/base/maneki/app-monitoring.yaml
- team-management/base/maneki/maneki.yaml
- team-management/base/sandbox/sandbox.yaml
- test/setup_test.go
https://github.com/cybozu-go/neco/issues/803
- Remove CPU limits from k8s workloads.
- Remove LimitRange for other teams
> Remove CPU Limits

- ingress/base/template/deployment.yaml
- monitoring/base/kube-state-metrics/deployment.yaml
- teleport/base/deployment.yaml
- teleport/base/statefulset.yaml
- teleport/overlays/gcp/kustomization.yaml
- test/Makefile
> Update containers: teleport, kube-state-metrics, contour

- test/setup_test.go
Delete update logic for team-management.
> Delete update logic for team-management

- go.mod
- test/Makefile
- test/reboot_test.go
- test/teleport_test.go
> use custom-checker

- test/cert-manager_test.go
- test/contour_test.go
> Delete printf used to debug

- test/Makefile.kindtest
- topolvm/base/upstream/controller.yaml
- topolvm/base/upstream/crd.yaml
- topolvm/base/upstream/node.yaml
- topolvm/base/upstream/provisioner.yaml
- topolvm/base/upstream/scheduler.yaml
> topolvm: update manifests to v0.4.0

- teleport/base/deployment.yaml
- teleport/base/statefulset.yaml
> Teleport Enterprise 4.2.4

- monitoring/base/prometheus/alert_rules/node.yaml
- test/alert_test/node.yaml
> turn off the alerts on the node marked as retired

- folding-at-home/daemonset.yaml
> fah: specify --cpus as 24

- monitoring/base/prometheus/alert_rules/kubernetes.yaml
- test/alert_test/kubernetes.yaml
> Remove extra alert `KubeDaemonSetMisScheduled`

- team-management/base/maneki/app-oauth-redirector.yaml
- team-management/base/maneki/kustomization.yaml
- team-management/base/maneki/maneki.yaml
- team-management/base/maneki/project.yaml
https://github.com/cybozu-go/neco/issues/877
> Add app-oauth-redirector namespace

- folding-at-home/daemonset.yaml
> duplicate fah DaemonSets

- teleport/base/deployment.yaml
- teleport/base/statefulset.yaml
> update teleport-ent to 4.2.8

- argocd/base/deployment.yaml
- ingress/base/template/deployment.yaml
- neco-admission/base/deployment.yaml
- test/Makefile
- test/Makefile.kindtest
- topolvm/base/upstream/controller.yaml
- topolvm/base/upstream/crd.yaml
- topolvm/base/upstream/node.yaml
- topolvm/base/upstream/scheduler.yaml
> support k8s 1.17

- teleport/base/conf/admin-role.yaml
- teleport/base/conf/maneki-role.yaml
- teleport/base/conf/neco-readonly-role.yaml
- teleport/base/kustomization.yaml
- teleport/base/statefulset.yaml
> Add Teleport Role Config

- monitoring/base/grafana/statefulset.yaml
> grafana: update version to v6.7.2

- monitoring/base/grafana/dashboards/kube-apiserver.json
- monitoring/base/grafana/dashboards/kube-controller-manager.json
- monitoring/base/grafana/dashboards/kube-scheduler.json
- monitoring/base/grafana/dashboards/kubelet.json
- monitoring/base/grafana/dashboards/neco-admission.json
- monitoring/base/prometheus/alert_rules/neco-admission.yaml
- monitoring/base/prometheus/prometheus.yaml
https://v1-17.docs.kubernetes.io/docs/setup/release/notes/#metrics-changes
> Stop using obsoleted metrics

- argocd/base/deployment.yaml
- argocd/base/upstream/install.yaml
- argocd/overlays/osaka0/configmap.yaml
- argocd/overlays/stage0/configmap.yaml
- argocd/overlays/tokyo0/configmap.yaml
> argocd: 1.5.1

- monitoring/base/grafana/configmap.yaml
- monitoring/base/grafana/dashboards/argocd.json
- monitoring/base/grafana/statefulset.yaml
- monitoring/base/kustomization.yaml
https://github.com/cybozu-go/neco/issues/901
> monitoring: add argocd dashboard

- argocd/base/deployment.yaml
- argocd/base/upstream/install.yaml
> Update Argo CD to 1.5.2

- monitoring/base/alertmanager/deployment.yaml
- monitoring/base/prometheus/statefulset.yaml
> prometheus: update to 2.17.2

- argocd/base/deployment.yaml
> update argocd to 1.5.2.2

- test/setup_test.go
- test/validation_test.go
> test: remove block for updating cert-manager v0.14

- monitoring/base/grafana/statefulset.yaml
> monitoring: update grafana to 6.7.3.1

- ingress/base/template/deployment.yaml
> ingress: add envoy livenessprobe sidecar container.

- argocd-config/overlays/stage0/monitoring.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/alert_rules/grafana-sandbox.yaml
- monitoring/base/prometheus/prometheus.yaml
- monitoring/overlays/stage0/grafana-sandbox/grafana.yaml
- monitoring/overlays/stage0/kustomization.yaml
> grafana-sandbox: Add manifests and README

- sandbox/overlays/gcp/grafana/statefulset.yaml
- secrets/base/monitoring/kustomization.yaml
- test/sandbox_test.go
- test/setup_test.go
> Add dummy secret for sandbox-grafana to fix unit test

- cert-manager/base/deployment.yaml
- cert-manager/base/upstream/cert-manager.yaml
- go.mod
- vendor/modules.txt
> cert-manager: update to 0.14.3

- monitoring/base/grafana-operator/operator.yaml
> grafana-operator: update to v3.3.0

- folding-at-home/daemonset.yaml
> fix fahclient.pid path

- monitoring/base/prometheus/statefulset.yaml
> Resize the  storage request size of Prometheus's volume claim template

- bmc-reverse-proxy/base/bmc-reverse-proxy/deployment.yaml
- bmc-reverse-proxy/base/machines-endpoints/cronjob.yaml
- local-pv-provisioner/base/daemonset.yaml
- monitoring/base/machines-endpoints/cronjob.yaml
- neco-admission/base/deployment.yaml
> Update client libs to support k8s 1.17.6

- test/setup_test.go
> rook: remove an eventually block of the simulate manual operation for rook/ceph

- team-management/base/common/project.yaml
> use namespaceResourceWhitelist instead of namespaceResourceBlacklist

- ingress/base/template/deployment.yaml
> ingress: update envoy to 1.13.2

- argocd/base/deployment.yaml
- argocd/base/kustomization.yaml
- argocd/base/upstream/install.yaml
- cert-manager/base/deployment.yaml
- cert-manager/base/upstream/cert-manager.yaml
- docs/maintenance.md
- elastic/base/upstream/all-in-one.yaml
- external-dns/base/deployment.yaml
- external-dns/base/rbac.yaml
- ingress/base/contour/00-common.yaml
- ingress/base/contour/01-crds.yaml
- ingress/base/contour/02-job-certgen.yaml
- ingress/base/contour/02-rbac.yaml
- ingress/base/contour/03-contour.yaml
- ingress/base/contour/03-envoy.yaml
- ingress/base/template/deployment.yaml
- monitoring/base/alertmanager/deployment.yaml
- monitoring/base/prometheus/statefulset.yaml
- network-policy/base/calico/daemonset.yaml
- network-policy/base/calico/deployment.yaml
- network-policy/base/calico/upstream/calico-policy-only.yaml
- sandbox/overlays/gcp/grafana/statefulset.yaml
- teleport/base/deployment.yaml
- teleport/base/statefulset.yaml
- test/Makefile
This PR for the periodical update of containers & manifests.
https://github.com/cybozu-private/neco-ops/issues/405
> Periodical update of containers & manifests

- monitoring/base/prometheus/prometheus.yaml
> prometheus: preserve labels from pushgateway

- monitoring/base/kustomization.yaml
> monitoring: update alertmanager to 0.21.0

- namespaces/base/argocd.yaml
- namespaces/base/bmc-reverse-proxy.yaml
- namespaces/base/kube-system.yaml
- namespaces/base/metallb.yaml
- namespaces/base/monitoring.yaml
https://github.com/cybozu-go/neco/issues/1021
> remove spec.finalizers from namespace definitions

- ingress/base/template/deployment.yaml
> contour: bump version to 1.6.0.1

- team-management/base/maneki/app-comconv-earthlab.yaml
- team-management/base/maneki/kustomization.yaml
- team-management/base/maneki/project.yaml
> team-management: add NS app-comconv-earthlab for maneki.

- ingress/base/template/deployment.yaml
> envoy: bump 1.14.3

- monitoring/base/grafana-operator/dashboards/kube-apiserver.yaml
https://github.com/cybozu-go/neco/issues/1027
> Fix Grafana dashboard of "Request duration 99th quantile dashboard" to use appropriate metric

- monitoring/base/grafana-operator/dashboards/kube-apiserver.yaml
Small bug fixes of https://github.com/cybozu-go/neco-apps/pull/633 .
> monitoring: fix units of API server dashboard

- test/suite_test.go
moved the OSD test on the last.
> test: change the order of test procedure

- neco-admission/base/deployment.yaml
- neco-admission/base/webhook.yaml
- test/admission_test.go
> Add validating webhook to protect deletion of resources.

- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/values.yaml
> rook: output debug log

- test/contour_test.go
- test/local-pv-provisioner_test.go
- test/network-policy_test.go
- test/storage_test.go
- test/topolvm_test.go
> Add annotations to temporary namespaces.

- docs/application_sync_wave.md
- docs/maintenance.md
- rook/base/ceph-hdd/kustomization.yaml
- rook/base/ceph-ssd/kustomization.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/upstream/toolbox.yaml
- test/storage_test.go
> rook: add ceph-tools

- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/overlays/gcp/kustomization.yaml
- test/storage_test.go
- test/suite_test.go
> rook: spread MON pods over racks

- monitoring/base/ingress-health/httpproxy.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/pushgateway/httpproxy.yaml
- monitoring/overlays/osaka0/ingress-health/httpproxy.yaml
- monitoring/overlays/osaka0/kustomization.yaml
- monitoring/overlays/osaka0/pushgateway/httpproxy.yaml
- monitoring/overlays/stage0/ingress-health/httpproxy.yaml
- monitoring/overlays/stage0/kustomization.yaml
- monitoring/overlays/stage0/pushgateway/httpproxy.yaml
- monitoring/overlays/tokyo0/ingress-health/httpproxy.yaml
- monitoring/overlays/tokyo0/kustomization.yaml
- monitoring/overlays/tokyo0/pushgateway/httpproxy.yaml
- test/monitoring_test.go
- test/setup_test.go
- test/suite_test.go
- confirm that dns is set to etcd
- test for push-gateway
> monitoring: add test for ingress-watcher

- test/contour_test.go
- test/local-pv-provisioner_test.go
- test/network-policy_test.go
- test/setup_test.go
- test/storage_test.go
- test/topolvm_test.go
Fix for [this](https://circleci.com/gh/cybozu-go/neco-apps/11011) 
> Wait for creation of default ServiceAccount when creating namespace in tests

- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-ssd/cluster.yaml
> rook: Fix MON pods affinity

- go.mod
- test/teleport_test.go
> remove dependency against gopkg yaml

- team-management/base/maneki/app-elasticsearch.yaml
- team-management/base/maneki/kustomization.yaml
- team-management/base/maneki/project.yaml
> team-management: add app-elasticsearch namespace for maneki

- test/monitoring_test.go
> monitoring: Simplify test

- test/monitoring_test.go
> monitoring: follow ingress-watcher update

- monitoring/overlays/gcp/grafana-operator/grafana.yaml
- monitoring/overlays/gcp/kustomization.yaml
- test/monitoring_test.go
see https://github.com/cybozu-go/neco/issues/735
> monitoring: grafana uses ClusterIP in dctest too.

- test/monitoring_test.go
https://github.com/cybozu-go/neco-apps/compare/295edc004...master#diff-0fa74b64ecf1add7ea0ff7bbf0dbb8f1L462
> test: fix a regression introduced by merge

- monitoring/base/grafana-operator/dashboards/ingress-watcher.yaml
- monitoring/base/grafana-operator/dashboards/kustomization.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/alert_rules/ingress-watcher.yaml
- monitoring/base/prometheus/alert_rules/monitoring.yaml
- monitoring/base/prometheus/prometheus.yaml
- test/alert_test/ingress-watcher.yaml
- test/alert_test/monitoring.yaml
Add alert rules and graphana dashboards for ingress-watcher
> monitoring: add alert rules and graphana dashboards for ingress-watcher.

- team-management/base/common/elastic-rbac.yaml
- team-management/base/maneki/elastic-serviceaccount.yaml
> team-management: add elastic service account for maneki

- test/argocd-ingress_test.go
- test/contour_test.go
- test/elastic_test.go
- test/local-pv-provisioner_test.go
- test/metallb_test.go
- test/monitoring_test.go
- test/network-policy_test.go
- test/suite_test.go
- test/topolvm_test.go
to reduce the time taken for the test.
> test: prepare resources for test beforehand

- elastic/base/crd.yaml
- elastic/base/statefulset.yaml
- elastic/base/upstream/all-in-one.yaml
- elastic/base/validatingwebhookconfiguration.yaml
> elastic: bump eck to 1.2.0

- test/setup_test.go
> Remove upgrade logic

- test/network-policy_test.go
- test/run_test.go
> test: wrap ExecAt args in its error

- teleport/base/statefulset.yaml
- test/setup_test.go
> teleport: delete teleport-etcd-certs secret

- argocd-config/base/rook.yaml
- argocd/base/configmap.yaml
- docs/maintenance.md
- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-hdd/clusterrolebinding/clusterrolebinding.yaml
- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-hdd/serviceaccount.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/base/ceph-ssd/clusterrolebinding/clusterrolebinding.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/ceph-ssd/serviceaccount.yaml
- rook/base/common/clusterrole.yaml
- rook/base/common/resources.yaml
- rook/base/upstream/.gitignore
- rook/base/upstream/chart/templates/clusterrole.yaml
- rook/base/upstream/chart/templates/clusterrolebinding.yaml
- rook/base/upstream/chart/templates/deployment.yaml
- rook/base/upstream/chart/templates/resources.yaml
- rook/base/upstream/chart/templates/serviceaccount.yaml
- rook/base/upstream/chart/values.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/values.yaml
- test/setup_test.go
- Upgrade rook to v1.3.8
- Upgrade ceph to v15.2.4
- Change podAntiAffinity of MON pods (`preferred` -> `required`)
- Add Lua script to check CephCluster CR
- Reduce log level
> rook: upgrade rook & ceph

- .circleci/config.yml
- bin/clean-dns.sh
Delete DNS records for every fixed number, not all at once.
> clean DNS records not all at once

- .circleci/config.yml
- test/Makefile
> Use CircleCI cache for downloaded artifacts

- docs/maintenance.md
Do not upgrade Rook and Ceph at the same time!
> Add notes for Rook and Ceph maintenance procedure

- .gitignore
- test/Makefile
- test/reboot_test.go
> Fix small mistakes in CI

- ingress/base/template/deployment.yaml
> envoy: update image to 1.14.3.2.

- ingress/base/template/deployment.yaml
> ingress: update Envoy from 1.14.3.2 to 1.14.5.1.

- docs/maintenance.md
- topolvm/base/crd.yaml
- topolvm/base/kustomization.yaml
- topolvm/base/upstream/base/crd.yaml
- topolvm/base/upstream/overlays/daemonset-scheduler/kustomization.yaml
- topolvm/base/upstream/overlays/deployment-scheduler/kustomization.yaml
> topolvm: update to v0.6.0

- local-pv-provisioner/base/clusterrole.yaml
- local-pv-provisioner/base/daemonset.yaml
- test/local-pv-provisioner_test.go
> local-pv-provisioner: update to v0.2.0

- monitoring/base/grafana-operator/dashboards/kube-apiserver.yaml
- monitoring/base/grafana-operator/dashboards/kube-scheduler.yaml
- monitoring/base/grafana-operator/dashboards/kubelet.yaml
> monitoring: Use new metrics

- rook/overlays/osaka0/ceph-hdd/httpproxy.yaml
- rook/overlays/osaka0/kustomization.yaml
- rook/overlays/stage0/ceph-hdd/httpproxy.yaml
- rook/overlays/stage0/kustomization.yaml
- rook/overlays/tokyo0/ceph-hdd/httpproxy.yaml
- rook/overlays/tokyo0/kustomization.yaml
> rook: deploy rgw httpproxy for forest

- team-management/base/common/clusterrole.yaml
- test/suite_test.go
- test/team-management_test.go
> team-management: allow admins to deploy ephemeral containers

- bmc-reverse-proxy/base/bmc-reverse-proxy/deployment.yaml
- bmc-reverse-proxy/base/machines-endpoints/cronjob.yaml
- monitoring/base/machines-endpoints/cronjob.yaml
- neco-admission/base/deployment.yaml
> upgrade containers for k8s 1.18

- argocd-config/base/kustomization.yaml
- argocd-config/base/pvc-autoresizer.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/pvc-autoresizer.yaml
- docs/maintenance.md
- metrics-server/base/kustomization.yaml
- namespaces/base/kustomization.yaml
- namespaces/base/pvc-autoresizer.yaml
- pvc-autoresizer/base/controller.yaml
- pvc-autoresizer/base/kustomization.yaml
- pvc-autoresizer/base/upstream.yaml
- rook/base/ceph-hdd/cephblockpool.yaml
- rook/base/ceph-ssd/cephblockpool.yaml
- rook/overlays/gcp/kustomization.yaml
- test/setup_test.go
- test/teleport_test.go
- test/topolvm_test.go
- test/validation_test.go
- topolvm/base/kustomization.yaml
- topolvm/base/storageclass.yaml
https://github.com/cybozu-go/neco/issues/1096
> Add pvc-autoresizer

- ingress/base/template/deployment.yaml
> fix sh arguments

- .circleci/config.yml
- metallb/overlays/gcp/configmap.yaml
> Fix MetalLB's address pool

- rook/overlays/stage0/ceph-hdd/httpproxy.yaml
to ease the development of applications using S3 API.
> rook: add s3 reverse proxy for stage0 bastion

- elastic/base/upstream/all-in-one.yaml
> Upgrade ECK to 1.2.1

- .circleci/config.yml
- .gitignore
- bin/run-test.sh
- docs/maintenance.md
- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-hdd/role.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/ceph-ssd/role.yaml
- rook/base/upstream/chart/templates/role.yaml
- rook/base/upstream/chart/values.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/upstream/toolbox.yaml
- rook/base/values.yaml
- test/Makefile
- test/storage_test.go
- test/suite_test.go
> rook: bump rook version to 1.4.6

- argocd-config/base/kustomization.yaml
- argocd-config/base/moco.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/moco.yaml
- docs/maintenance.md
- moco/base/crd.yaml
- moco/base/kustomization.yaml
- moco/base/upstream/crd/bases/moco.cybozu.com_mysqlclusters.yaml
- moco/base/upstream/crd/kustomization.yaml
- moco/base/upstream/kustomization.yaml
- moco/base/upstream/manager/kustomization.yaml
- moco/base/upstream/manager/manager.yaml
- moco/base/upstream/namespace.yaml
- moco/base/upstream/rbac/kustomization.yaml
- moco/base/upstream/rbac/leader_election_role.yaml
- moco/base/upstream/rbac/leader_election_role_binding.yaml
- moco/base/upstream/rbac/mysqlcluster_editor_role.yaml
- moco/base/upstream/rbac/mysqlcluster_viewer_role.yaml
- moco/base/upstream/rbac/role.yaml
- moco/base/upstream/rbac/role_binding.yaml
- monitoring/base/prometheus/prometheus.yaml
- test/validation_test.go
> [moco] Add moco manifests.

- .circleci/config.yml
> To reduce running GCP instances, add a hold to ceph workflow

- monitoring/base/prometheus/alert_rules/node.yaml
- test/alert_test/node.yaml
> monitoring: add alert for node memory exhaustion.

- .circleci/config.yml
>  add state label to VM instance when test is failed 

- .circleci/config.yml
> test: disable upgrade test temporarily.

- .circleci/config.yml
This reverts commit edeba86e94170b98877624b7589cd39050d5795e.
> Revert "test: disable upgrade test temporarily."

- .circleci/config.yml
- team-management/base/common/clusterrole.yaml
- test/setup_test.go
- test/storage_test.go
> team-management: configure rbac to create obc resource for tenant users

- .circleci/config.yml
> Change the execution time of daily jobs

- test/Makefile
> test: use CURDIR variable

- argocd-config/base/customer-egress.yaml
- argocd-config/base/kustomization.yaml
- argocd-config/overlays/stage0/customer-egress.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- coil/base/addresspool.yaml
- coil/overlays/osaka0/addresspool.yaml
- coil/overlays/stage0/addresspool.yaml
- coil/overlays/tokyo0/addresspool.yaml
- customer-egress/base/kustomization.yaml
- customer-egress/base/namespace.yaml
- customer-egress/base/neco/squid.yaml
- customer-egress/base/squid.yaml
- docs/maintenance.md
- network-policy/base/kustomization.yaml
- network-policy/base/policies/customer-egress.yaml
- test/customer-egress_test.go
- test/network-policy_test.go
- test/suite_test.go
- test/validation_test.go
> Add squid for customers.

- team-management/base/garoon/app-garoon-static.yaml
- team-management/base/garoon/kustomization.yaml
- team-management/base/garoon/project.yaml
- team-management/base/kustomization.yaml
- teleport/base/conf/garoon-role.yaml
- teleport/base/kustomization.yaml
> team-management: Add garoon group and app-garoon-static namespace.

- customer-egress/base/egress.yaml
- customer-egress/base/kustomization.yaml
- test/customer-egress_test.go
- test/network-policy_test.go
> Add Coil Egress for customers.

- monitoring/base/prometheus/prometheus.yaml
> monitoring: Add customer-egress monitoring.

- argocd-config/base/kustomization.yaml
- argocd-config/base/moco.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/moco.yaml
- moco/base/crd.yaml
- moco/base/kustomization.yaml
- moco/base/namespace.yaml
- moco/base/upstream/crd/bases/moco.cybozu.com_mysqlclusters.yaml
- moco/base/upstream/crd/kustomization.yaml
- moco/base/upstream/kustomization.yaml
- moco/base/upstream/manager/kustomization.yaml
- moco/base/upstream/manager/manager.yaml
- moco/base/upstream/namespace.yaml
- moco/base/upstream/rbac/kustomization.yaml
- moco/base/upstream/rbac/leader_election_role.yaml
- moco/base/upstream/rbac/leader_election_role_binding.yaml
- moco/base/upstream/rbac/mysqlcluster_editor_role.yaml
- moco/base/upstream/rbac/mysqlcluster_viewer_role.yaml
- moco/base/upstream/rbac/role.yaml
- moco/base/upstream/rbac/role_binding.yaml
- test/setup_test.go
- test/validation_test.go
> moco: deploy again

- test/Makefile
- test/setup_test.go
This PR deletes the added line in the PR below.
https://github.com/cybozu-go/neco-apps/pull/836
> Remove temporary code

- monitoring/base/prometheus/prometheus.yaml
> monitor: add "component" label to coil metrics.

- test/.gitignore
> test: ignore "test/bin" directory introduced in 175e4b8.

- argocd/base/configmap.yaml
- team-management/base/ept/app-ept-wiki.yaml
- team-management/base/ept/kustomization.yaml
- team-management/base/ept/project.yaml
- team-management/base/kustomization.yaml
- teleport/base/conf/ept-role.yaml
- teleport/base/kustomization.yaml
> Add EPT team

- monitoring/base/grafana-operator/dashboards/coil.yaml
- monitoring/base/grafana-operator/dashboards/kustomization.yaml
> monitor: add Grafana dashboard for Coil.

- secrets/base/monitoring/kustomization.yaml
- test/validation_test.go
> test: Add mackerel-agent dummy secret

- ingress/base/template/deployment-envoy.yaml
> ingress: Add startupProbe to envory Pod.

- monitoring/base/grafana-operator/dashboards/coil.yaml
> monitoring: Specify datasource for coil dashboard

- teleport/base/deployment.yaml
- teleport/base/kustomization.yaml
- teleport/base/rbac.yaml
- teleport/base/statefulset.yaml
> teleport: Upgrade to v5.0.0

- teleport/overlays/gcp/certificate.yaml
- teleport/overlays/osaka0/certificate.yaml
- teleport/overlays/stage0/certificate.yaml
- teleport/overlays/tokyo0/certificate.yaml
> teleport: Use wildcard cert for teleport proxy.

- monitoring/base/prometheus/prometheus.yaml
- network-policy/base/policies/monitoring.yaml
> monitoring: scrape vault metrics.

- argocd-config/overlays/stage0/ept-apps.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- neco-admission/base/config.yaml
- neco-admission/base/webhook.yaml
- test/validation_test.go
> Add ept-apps

- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/README.md
- monitoring/base/prometheus/alert_rules/vault.yaml
- monitoring/base/prometheus/prometheus.yaml
- test/alert_test/vault.yaml
> monitoring: Add alert rule for vault

- bin/clean-dns.sh
- secrets/base/teleport/kustomization.yaml
- secrets/base/teleport/teleport.yaml
- teleport/base/apps/alertmanager.yaml
- teleport/base/apps/kustomization.yaml
- teleport/base/conf/admin-role.yaml
- teleport/base/conf/ept-role.yaml
- teleport/base/conf/garoon-role.yaml
- teleport/base/conf/maneki-role.yaml
- teleport/base/conf/neco-readonly-role.yaml
- teleport/base/kustomization.yaml
- teleport/base/service.yaml
- teleport/overlays/gcp/apps/alertmanager.yaml
- teleport/overlays/gcp/kustomization.yaml
- test/setup_test.go
- test/teleport_test.go
> teleport: Add alertmanager app.

- namespaces/base/kube-system.yaml
> namespaces: remove 'openpolicyagent.org/webhook' label

- teleport/base/conf/neco-readonly-role.yaml
> teleport: Fix neco-readonly allow/deny app_labels.

- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-ssd/cluster.yaml
> [rook/ceph] set request parameters for the pods

- neco-admission/base/deployment.yaml
Implements https://github.com/cybozu-go/neco/issues/1255
> neco-admission: Add preStop hook for graceful termination

- .circleci/config.yml
- bin/teleport-cname.sh
> test: Create teleport CNAME idempotently.

- monitoring/base/victoriametrics/alertmanager.yaml
- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmsingle-smallset.yaml
> add resource requests to VictoriaMetrics operator managed resources.

- neco-admission/base/deployment.yaml
- neco-admission/base/upstream/manifests.yaml
- neco-admission/base/webhook.yaml
This PR incorporates [this update](https://github.com/cybozu/neco-containers/pull/474).
> admission: Upgrade image to 0.7.0

- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- test/vmalert_test/kubernetes.yaml
> follow kubernetes alert rules for VictoriaMetrics

- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/values.yaml
> rook: update base image

- teleport/base/kustomization.yaml
> upgrade teleport to v5.0.1

- monitoring/base/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/gcp/kustomization.yaml
- monitoring/overlays/gcp/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/osaka0/kustomization.yaml
- monitoring/overlays/osaka0/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/tokyo0/kustomization.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmsingle-smallset.yaml
> increase storage requests of vmsingle PVC

- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-ssd/cluster.yaml
> ceph: update to 15.2.7.1

- teleport/base/kustomization.yaml
> upgrade teleport v5.0.2

- argocd/base/kustomization.yaml
> argocd: Upgrade dex to v2.27.0

- cert-manager/base/deployment.yaml
> cert-manager: Check authoritative server when dns01.

- team-management/base/common/clusterrole.yaml
- test/team-management_test.go
> test: unprivileged team authority 

- monitoring/base/grafana-operator/datasources/victoriametrics.yaml
- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/gcp/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/osaka0/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmsingle-smallset.yaml
- sandbox/overlays/gcp/grafana/configmap.yaml
- test/monitoring_test.go
- test/validation_test.go
> VMSingle is only one

- test/storage_test.go
- test/suite_test.go
> test: test Rook/Ceph data across reboot.

- monitoring/base/ingress-health/deployment.yaml
Related to https://github.com/cybozu/neco-containers/pull/482
> Upgrade testhttpd to 0.1.1

- team-management/base/maneki/app-monitoring-elasticstack.yaml
- team-management/base/maneki/kustomization.yaml
- team-management/base/maneki/project.yaml
Add `app-monitoring-elasticstack` ns for `maneki` team.
> Add app-monitoring-elasticstack ns

- monitoring/base/victoriametrics/operator.yaml
- monitoring/base/victoriametrics/remove_crd_status.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmagents.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalerts.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmclusters.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmnodescrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmrules.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmsingles.yaml
- monitoring/base/victoriametrics/upstream/crd/kustomization.yaml
- monitoring/base/victoriametrics/upstream/crd/patches/cainjection_in_vmnodescrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/patches/webhook_in_vmnodescrapes.yaml
- monitoring/base/victoriametrics/upstream/rbac/role.yaml
- monitoring/base/victoriametrics/upstream/rbac/vmnodescrape_editor_role.yaml
- monitoring/base/victoriametrics/upstream/rbac/vmnodescrape_viewer_role.yaml
> update to VictoriaMetrics operator 0.6.0

- test/validation_test.go
> test: Disable func testGeneratedSecretName()

- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/operator.yaml
- monitoring/base/victoriametrics/rules/monitoring-alertrule.yaml
- monitoring/base/victoriametrics/rules/monitoring-scrape.yaml
- test/validation_test.go
- test/vmalert_test/monitoring.yaml
> add monitoring configs for VictoriaMetrics itself

- bmc-reverse-proxy/overlays/gcp/bmc-reverse-proxy/certificate.yaml
- bmc-reverse-proxy/overlays/osaka0/bmc-reverse-proxy/certificate.yaml
- bmc-reverse-proxy/overlays/stage0/bmc-reverse-proxy/certificate.yaml
- bmc-reverse-proxy/overlays/tokyo0/bmc-reverse-proxy/certificate.yaml
- cert-manager/overlays/gcp/clusterissuer.yaml
- cert-manager/overlays/neco-dev/clusterissuer.yaml
- cert-manager/overlays/osaka0/clusterissuer.yaml
- cert-manager/overlays/stage0/clusterissuer.yaml
- cert-manager/overlays/tokyo0/clusterissuer.yaml
- ingress/base/bastion/certificate.yaml
- ingress/base/forest/certificate.yaml
- ingress/base/global/certificate.yaml
- ingress/base/template/certificate.yaml
- ingress/base/template/httpproxy.yaml
- neco-admission/base/certificates.yaml
- teleport/overlays/gcp/certificate.yaml
- teleport/overlays/osaka0/certificate.yaml
- teleport/overlays/stage0/certificate.yaml
- teleport/overlays/tokyo0/certificate.yaml
> Update cert-manager api to v1

- teleport/base/statefulset.yaml
- teleport/overlays/gcp/statefulset.yaml
- test/setup_test.go
> teleport: use ceph-ssd-block for PVC storage class

- monitoring/base/prometheus/prometheus.yaml
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/rook-scrape.yaml
- test/validation_test.go
> monitoring: add rook/ceph scraping rule

- docs/maintenance.md
> add dex maintenance manual

- customer-egress/base/neco/squid.yaml
- customer-egress/base/squid.yaml
- ingress/base/template/deployment-contour.yaml
> Fix preStop hook.

- test/storage_test.go
> rook/ceph test: check stability of RGW

- test/setup_test.go
https://github.com/cybozu-go/neco-apps/pull/957 and https://github.com/cybozu-go/neco-apps/pull/966 have been released in https://github.com/cybozu-go/neco-apps/pull/990.
> test: remove temporary code for upgrade.

- test/setup_test.go
> test: remove upgrade logic

- monitoring/base/prometheus/prometheus.yaml
> monitoring: fix scraping rule for rook/ceph

- test/setup_test.go
> test: wait after "neco config set"

- monitoring/base/grafana-operator/datasources/victoriametrics.yaml
> extend timeInterval of vmsingle in GrafanaDataSource

- monitoring/base/grafana-operator/datasources/datasource.yaml
- monitoring/base/prometheus/prometheus.yaml
> extend scraping/alerting interval of Prometheus

- test/customer-egress_test.go
- test/suite_test.go
> prepare pod in advance in cursotmer-egress test

- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmsingle-smallset.yaml
> update to VictoriaMetrics 1.51.0

- monitoring/base/grafana-operator/dashboards/kustomization.yaml
- monitoring/base/grafana-operator/dashboards/victoriametrics-vmagent.yaml
- monitoring/base/grafana-operator/dashboards/victoriametrics-vmsingle.yaml
> add grafana dashboards for victoriametrics

- docs/maintenance.md
- rook/base/ceph-hdd/clusterrolebinding/clusterrolebinding.yaml
- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-hdd/role.yaml
- rook/base/ceph-hdd/rolebinding.yaml
- rook/base/ceph-hdd/serviceaccount.yaml
- rook/base/ceph-ssd/clusterrolebinding/clusterrolebinding.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/ceph-ssd/role.yaml
- rook/base/ceph-ssd/rolebinding.yaml
- rook/base/ceph-ssd/serviceaccount.yaml
- rook/base/common/clusterrole.yaml
- rook/base/common/psp.yaml
- rook/base/common/resources.yaml
- rook/base/upstream/chart/Chart.yaml
- rook/base/upstream/chart/templates/NOTES.txt
- rook/base/upstream/chart/templates/clusterrole.yaml
- rook/base/upstream/chart/templates/clusterrolebinding.yaml
- rook/base/upstream/chart/templates/deployment.yaml
- rook/base/upstream/chart/templates/psp.yaml
- rook/base/upstream/chart/templates/resources.yaml
- rook/base/upstream/chart/templates/role.yaml
- rook/base/upstream/chart/templates/rolebinding.yaml
- rook/base/upstream/chart/templates/serviceaccount.yaml
- rook/base/upstream/chart/values.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/upstream/toolbox.yaml
- rook/base/values.yaml
- test/storage_test.go
> rook: Update to 1.5.4.

- test/.gitignore
> ignore temporary generated secret files during test

- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/values.yaml
> rook: update to 1.5.4.2

- monitoring/base/prometheus/alert_rules/cke.yaml
- monitoring/base/prometheus/alert_rules/sabakan.yaml
- test/alert_test/cke.yaml
- test/alert_test/sabakan.yaml
This PR adds some alerts for boot servers including for detecting CKE failure.
> Add boot server alerts.

- argocd-config/overlays/osaka0/maneki-apps.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/maneki-apps.yaml
- argocd-config/overlays/stage0/tenant-apps.yaml
- argocd-config/overlays/tokyo0/maneki-apps.yaml
- neco-admission/base/config.yaml
- test/validation_test.go
> add tenant-apps application

- argocd-config/overlays/stage0/ept-apps.yaml
> Fix the path of ept-apps

- monitoring/base/kustomization.yaml
- monitoring/base/prometheus/alert_rules/rook.yaml
- monitoring/base/prometheus/prometheus.yaml
- test/alert_test/rook.yaml
> Add alert for Ceph health.

- monitoring/base/victoriametrics/rules/rook-alertrule.yaml
- test/vmalert_test/rook.yaml
Reflect https://github.com/cybozu-go/neco-apps/pull/1043 for VictoriaMetrics.
> Add vmalert for ceph health

- argocd-config/overlays/stage0/tenant-apps.yaml
- team-management/base/common/project.yaml
- test/validation_test.go
> Add tenant-apps project

- neco-admission/base/config.yaml
> Change validation rule for tenant-app AppProject

- argocd/base/configmap.yaml
- neco-admission/base/config.yaml
- team-management/base/ept/app-ept-wiki.yaml
- team-management/base/ept/project.yaml
- team-management/base/garoon/app-garoon-static.yaml
- team-management/base/garoon/project.yaml
- team-management/base/maneki/project.yaml
- test/team-management_test.go
- test/validation_test.go
> Change maneki team privileges

- topolvm/base/kustomization.yaml
- topolvm/base/upstream/base/certificates.yaml
- topolvm/base/upstream/base/controller.yaml
- topolvm/base/upstream/base/kustomization.yaml
- topolvm/base/upstream/overlays/daemonset-scheduler/kustomization.yaml
- topolvm/base/upstream/overlays/daemonset-scheduler/scheduler-options.yaml
- topolvm/base/upstream/overlays/deployment-scheduler/kustomization.yaml
- topolvm/base/upstream/overlays/deployment-scheduler/scheduler-options.yaml
> topolvm: update to 0.7.0

- test/README.md
> update neco dctest procedure

- team-management/base/common/clusterrole.yaml
- test/team-management_test.go
- update RBAC definition
- add a test
> [team-management] Allow tenants to read  objectbucket resource

- argocd/base/configmap.yaml
- team-management/base/common/project.yaml
- team-management/base/ept/project.yaml
- team-management/base/garoon/project.yaml
> Change team names in argocd settings

- team-management/base/common/elastic-rbac.yaml
- team-management/base/maneki/elastic-serviceaccount.yaml
> Add elastic ServiceAccount for app-monitoring-elasticstack namespace

- teleport/base/apps/kustomization.yaml
- teleport/base/apps/vmalertmanager.yaml
- teleport/overlays/gcp/apps/vmalertmanager.yaml
- teleport/overlays/gcp/kustomization.yaml
> add vmalertmanager teleport app

- monitoring/base/prometheus/alert_rules/node.yaml
- test/alert_test/node.yaml
> alert for the free space of the each file system.

- test/reboot_test.go
> test: Add image pull test after reboot all nodes.

- test/reboot_test.go
- test/storage_test.go
> Refactor reboot workflow to ensure all Pod are deleted.

- monitoring/base/grafana-operator/dashboards/kustomization.yaml
- monitoring/base/grafana-operator/dashboards/victoriametrics-vmcluster.yaml
- monitoring/base/grafana-operator/datasources/victoriametrics.yaml
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/operator.yaml
- monitoring/base/victoriametrics/rules/monitoring-alertrule.yaml
- monitoring/base/victoriametrics/rules/monitoring-scrape.yaml
- monitoring/base/victoriametrics/vmagent-largeset.yaml
- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmcluster-largeset.yaml
- monitoring/overlays/osaka0/kustomization.yaml
- monitoring/overlays/osaka0/victoriametrics/vmcluster-largeset.yaml
- monitoring/overlays/stage0/kustomization.yaml
- monitoring/overlays/stage0/victoriametrics/vmcluster-largeset.yaml
- monitoring/overlays/tokyo0/kustomization.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmcluster-largeset.yaml
- sandbox/overlays/gcp/grafana/configmap.yaml
- test/monitoring_test.go
- test/suite_test.go
- test/validation_test.go
- test/vmalert_test/monitoring.yaml
> Deploy shared VictoriaMetrics instance

- monitoring/base/prometheus/prometheus.yaml
- monitoring/base/victoriametrics/rules/registry-scrape.yaml
> The label key was changed from `app.kubernetes.io/instance` to `cybozu.com/registry`

- team-management/base/common/elastic-rbac.yaml
- team-management/base/maneki/elastic-serviceaccount.yaml
> Allow the running of Elasticsearch in app-ept-wiki

- monitoring/base/victoriametrics/operator.yaml
> upgrade to VictoriaMetrics operator 0.7.3

- monitoring/base/victoriametrics/alertmanager.yaml
- monitoring/base/victoriametrics/operator.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- test/monitoring_test.go
> VMAlertmanager HA

- monitoring/base/grafana-operator/dashboards/kubelet.yaml
- monitoring/base/grafana-operator/dashboards/kubernetes-cluster.yaml
- monitoring/base/prometheus/alert_rules/kubernetes.yaml
- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- test/alert_test/kubernetes.yaml
- test/vmalert_test/kubernetes.yaml
#1025 
This must be merged after Neco's Kubernetes is upgraded to 1.19.
> metrics: update for k8s 1.19

- argocd/base/deployment.yaml
- bin/teleport-cname.sh
- external-dns/base/deployment.yaml
- monitoring/base/grafana-operator/configmap.yaml
- monitoring/base/grafana-operator/grafana.yaml
- sandbox/overlays/gcp/grafana/configmap.yaml
- secrets/base/monitoring/alertmanager.yaml
- secrets/base/monitoring/vmalertmanager.yaml
- teleport/base/apps/alertmanager.yaml
- teleport/base/statefulset.yaml
- test/teleport_test.go
> remove redudunt .cluster.local suffix

- argocd/base/configmap.yaml
- team-management/base/common/project.yaml
- team-management/base/ept/project.yaml
- team-management/base/garoon/project.yaml
- team-management/base/maneki/project.yaml
> Use GitHub team's slug for ArgoCD SSO

- monitoring/base/victoriametrics/kustomization.yaml
- test/validation_test.go
> rook alert is not enabled in VictoriaMetrics

- test/setup_test.go
Currently, network-policy resources are applied in advance of Argo CD Applications.
Because of that, Argo CD adds `app.kubernetes.io/instance: network-policy` to the resource, but this behavior takes time.
So this PR adds the label when the resources are applied to speed up neco-apps CI.
> Apply ArgoCD annotation to network-policy app beforehand

- pvc-autoresizer/base/upstream.yaml
> bump pvc-autoresizer to 0.1.3

- monitoring/base/prometheus/alert_rules/kubernetes.yaml
- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- test/alert_test/kubernetes.yaml
- test/vmalert_test/kubernetes.yaml
> monitoring: suppress unschedulable Pod alert for rebooting Node.

- README.md
- docs/maintenance.md
- docs/manifests.md
- test/reboot_test.go
> Fix github branch names in some links

- docs/maintenance.md
- test/Makefile
- Update test tools version in `test/Makefile`.
> test: Update test tools version

- team-management/base/ept/elastic-serviceaccount.yaml
- team-management/base/ept/kustomization.yaml
- team-management/base/maneki/elastic-serviceaccount.yaml
> Move elastic ServiceAccount for ept to ept directory

- test/validation_test.go
> check VictoriaMetrics rule files are written in kustomization

- .circleci/config.yml
- test/Makefile
- test/README.md
- test/env.go
- test/suite_test.go
> test: add "bootstrap" suite instead of BOOTSTRAP variable.

- team-management/base/common/project.yaml
- team-management/base/cydec/app-gorush.yaml
- team-management/base/cydec/kustomization.yaml
- team-management/base/cydec/project.yaml
- team-management/base/kustomization.yaml
- team-management/base/maneki/kustomization.yaml
- team-management/base/maneki/project.yaml
- teleport/base/conf/cydec-role.yaml
- teleport/base/kustomization.yaml
- test/setup_test.go
> Add cydec team

- moco/base/kustomization.yaml
- moco/base/upstream/rbac/role.yaml
- test/Makefile
- test/moco_test.go
- test/registry_test.go
> [moco] Upgrade to v0.5.1

- .gitignore
- argocd-config/base/kustomization.yaml
- argocd-config/base/logging.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/logging.yaml
- docs/maintenance.md
- logging/base/kustomization.yaml
- logging/base/loki.yaml
- logging/base/loki/configmap.yaml
- logging/base/loki/obc.yaml
- logging/base/loki/upstream/loki.yaml
- logging/base/promtail.yaml
- logging/base/promtail/configmap.yaml
- logging/base/promtail/upstream/promtail.yaml
- monitoring/base/grafana-operator/datasources/loki.yaml
- monitoring/base/grafana-operator/kustomization.yaml
- namespaces/base/kustomization.yaml
- namespaces/base/logging.yaml
- test/logging_test.go
- test/suite_test.go
> loki: deploy loki with monolithic mode

- local-pv-provisioner/base/daemonset.yaml
- metallb/base/deployment.yaml
- network-policy/base/calico/daemonset.yaml
- topolvm/base/node.yaml
> Update DaemonSet Pods in bulk.

- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-ssd/cluster.yaml
> update ceph image version in ceph cluster

- neco-admission/base/config.yaml
> add cydec-apps repo

- test/storage_test.go
> remove load pod from cs nodes to stablize ci

- test/logging_test.go
> logging: add Eventually for checkLog method to stablize CI

- logging/base/promtail/configmap.yaml
> logging: describe container name and hostname for loki

- monitoring/base/alertmanager/deployment.yaml
- monitoring/base/prometheus/README.md
- monitoring/base/prometheus/alert_rules/rook.yaml
- monitoring/base/victoriametrics/rules/rook-alertrule.yaml
- secrets/base/monitoring/kustomization.yaml
- test/alert_test/rook.yaml
- test/vmalert_test/rook.yaml
> deploy pager notification

- monitoring/base/grafana-operator/operator.yaml
- sandbox/overlays/gcp/grafana/statefulset.yaml
> upgrade grafana to 7.4.1

- registry/templates/configmap.yaml
> Change the log level in the registry for debugging

- argocd/base/configmap.yaml
by a custom Lua health check script.
> argocd: wait for OBC to get bound

- sandbox/overlays/gcp/grafana/configmap.yaml
cf. https://github.com/cybozu-go/neco-apps/commit/4c486c3301729daaa2a76b6809c0e02207185cb3#diff-82f8dd87bd41e99efc1822dd1cda3eb314b4a4a618c09cb6607536690e54a52c
> add loki datasource to sandbox grafana

- moco/base/kustomization.yaml
- test/moco_test.go
> Update moco v0.6.0

- argocd-config/overlays/osaka0/maneki-apps.yaml
- argocd-config/overlays/stage0/ept-apps.yaml
- argocd-config/overlays/stage0/maneki-apps.yaml
- argocd-config/overlays/stage0/tenant-apps.yaml
- argocd-config/overlays/tokyo0/maneki-apps.yaml
> argocd: purge sync-wave settings

- argocd-config/overlays/stage0/garoon-apps.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- neco-admission/base/config.yaml
- test/validation_test.go
> argocd: add reference to garoon-apps repository

- test/setup_test.go
> test: wait for docker's restart and stability.

- logging/base/loki.yaml
- test/setup_test.go
> logging: shorten termination grace period.

- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/common/clusterrole.yaml
- rook/base/common/resources.yaml
- rook/base/upstream/chart/templates/clusterrole.yaml
- rook/base/upstream/chart/templates/deployment.yaml
- rook/base/upstream/chart/templates/resources.yaml
- rook/base/upstream/chart/values.yaml
- rook/base/upstream/toolbox.yaml
- rook/base/values.yaml
> rook: version up to v1.5.7

- .circleci/config.yml
- bin/run-test.sh
- cert-manager/overlays/gcp/clusterissuer.yaml
- cert-manager/overlays/neco-dev/clusterissuer.yaml
- test/README.md
- test/setup_test.go
> use ZeroSSL in CI

- test/README.md
> add documentation for ZeroSSL

- monitoring/base/victoriametrics/rules/monitoring-alertrule.yaml
- test/vmalert_test/monitoring.yaml
> monitoring: extend alert threshold for single-instance monitors.

- monitoring/base/victoriametrics/rbac/editor_aggregation.yaml
- monitoring/base/victoriametrics/rbac/kustomization.yaml
- monitoring/base/victoriametrics/rbac/viewer_aggregation.yaml
- monitoring/base/victoriametrics/upstream/rbac/kustomization.yaml
- test/team-management_test.go
> Add aggregation for VictoriaMetrics resources.

- monitoring/base/victoriametrics/rules/cert-manager-alertrule.yaml
- test/vmalert_test/cert-manager.yaml
> add alert rules to detect certificate expiration

- team-management/base/maneki/app-forest-certs.yaml
- team-management/base/maneki/app-maneki-static-cybozu-com.yaml
- team-management/base/maneki/kustomization.yaml
- team-management/base/maneki/project.yaml
> team-management: add app-maneki-static-cybozu-com and app-forest-certs namespaces

- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/values.yaml
- test/suite_test.go
> rook: update version to 1.5.7.2

- teleport/base/apps/alertmanager.yaml
- teleport/base/apps/vmalertmanager.yaml
- test/setup_test.go
> fix pod labels in teleport app deployments

- argocd-config/overlays/osaka0/tenant-apps.yaml
- argocd-config/overlays/tokyo0/tenant-apps.yaml
- test/validation_test.go
> tenant-apps: set up overlays

- monitoring/base/victoriametrics/configmap-settype.yaml
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/kube-state-metrics-alertrule.yaml
- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- monitoring/base/victoriametrics/rules/monitoring-alertrule.yaml
- monitoring/base/victoriametrics/rules/monitoring-scrape.yaml
- monitoring/base/victoriametrics/vmagent-largeset.yaml
- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmalertmanager-largeset.yaml
- monitoring/base/victoriametrics/vmalertmanager-smallset.yaml
- monitoring/overlays/gcp/victoriametrics/env.template
- monitoring/overlays/osaka0/victoriametrics/env.template
- monitoring/overlays/stage0/victoriametrics/env.template
- monitoring/overlays/tokyo0/victoriametrics/env.template
- teleport/base/apps/kustomization.yaml
- teleport/base/apps/vmalertmanager-largeset.yaml
- teleport/base/apps/vmalertmanager-smallset.yaml
- teleport/overlays/gcp/apps/vmalertmanager-largeset.yaml
- teleport/overlays/gcp/apps/vmalertmanager-smallset.yaml
- teleport/overlays/gcp/kustomization.yaml
- test/monitoring_test.go
- test/suite_test.go
- test/topolvm_test.go
- test/validation_test.go
- test/vmalert_test/monitoring.yaml
> prepare to remove prometheus

- rook/overlays/gcp/kustomization.yaml
> rook: set log level to debug on gcp

- .circleci/config.yml
- test/storage_test.go
> rook: change downloaded file name to avoid conflicting

- monitoring/base/victoriametrics/vmagent-largeset.yaml
- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmcluster-largeset.yaml
- monitoring/base/victoriametrics/vmsingle-smallset.yaml
> upgrade to VictoriaMetrics 1.55.1

- Makefile
- docs/maintenance.md
- monitoring/base/grafana-operator/operator.yaml
> use custom-built grafana_plugins_init container

- test/monitoring_test.go
- test/network-policy_test.go
- test/validation_test.go
> add more test for VictoriaMetrics

- test/contour_test.go
- test/network-policy_test.go
> don't delete namespaces during e2e test

- team-management/base/ept/app-ept-monitoring.yaml
- team-management/base/ept/kustomization.yaml
- team-management/base/ept/project.yaml
- team-management/base/maneki/project.yaml
> Add app-ept-monitoring namespace

- rook/base/ceph-hdd/cephblockpool.yaml
- rook/base/ceph-hdd/cephobjectstore.yaml
- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-ssd/cephblockpool.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/base/upstream/kustomization.yaml
> Rook: stabilize rook

- monitoring/base/prometheus/alert_rules/teleport.yaml
- monitoring/base/victoriametrics/rules/teleport-alertrule.yaml
- teleport/base/deployment.yaml
- test/alert_test/teleport.yaml
- test/vmalert_test/teleport.yaml
> teleport: set replicas of teleport proxy to 2

- Makefile
- docs/maintenance.md
- monitoring/base/victoriametrics/operator.yaml
- monitoring/base/victoriametrics/vmagent-largeset.yaml
- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmalertmanager-largeset.yaml
- monitoring/base/victoriametrics/vmalertmanager-smallset.yaml
- monitoring/base/victoriametrics/vmcluster-largeset.yaml
- monitoring/base/victoriametrics/vmsingle-smallset.yaml
> VictoriaMetrics: transfer individual specs to operator's env vars.

- test/Makefile
- test/env.go
- test/metallb_test.go
- test/monitoring_test.go
- test/teleport_test.go
- test/test.sh
This PR modifies tests to work with both placemat versions 1 and 2.
> Apply placemat v2

- .circleci/config.yml
This reverts commit afd47ea52b0d0acb5bebf190f4360e1b90e68825.
> Revert "CI: skip upgrade tests temporarily"

- teleport/base/conf/admin-role.yaml
- teleport/base/conf/maneki-role.yaml
> Fix label filter for Teleport nodes.

- monitoring/base/victoriametrics/rules/monitoring-alertrule.yaml
- test/vmalert_test/monitoring.yaml
> Loosen VMAlertmanagerSmallsetDown to 30mins on reboot

- pvc-autoresizer/base/upstream/default/kustomization.yaml
- topolvm/base/kustomization.yaml
- topolvm/base/upstream/overlays/daemonset-scheduler/kustomization.yaml
- topolvm/base/upstream/overlays/deployment-scheduler/kustomization.yaml
> update topolvm and pvc-autoresizer

- monitoring/base/victoriametrics/rules/kube-state-metrics-alertrule.yaml
- monitoring/base/victoriametrics/rules/kube-state-metrics-scrape.yaml
- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- test/validation_test.go
- test/vmalert_test/kube-state-metrics.yaml
> Add scrape setting for kube-state-metrics telemetry

- test/Makefile
> add setup script of custom-checker

- team-management/base/garoon/app-garoon-monitoring.yaml
- team-management/base/garoon/app-garoon-static.yaml
- teleport/base/conf/garoon-role.yaml
- teleport/base/nodes/garoon.yaml
- teleport/base/nodes/kustomization.yaml
- teleport/base/nodes/serviceaccount.yaml
- teleport/overlays/gcp/kustomization.yaml
- teleport/overlays/gcp/nodes/garoon.yaml
> Add Teleport node Pod for garoon team.

- team-management/base/cydec/app-gorush.yaml
- team-management/base/ept/app-ept-monitoring.yaml
- team-management/base/ept/app-ept-wiki.yaml
- teleport/base/conf/cydec-role.yaml
- teleport/base/conf/ept-role.yaml
- teleport/base/nodes/cydec.yaml
- teleport/base/nodes/ept.yaml
- teleport/base/nodes/kustomization.yaml
- teleport/base/nodes/serviceaccount.yaml
- teleport/overlays/gcp/kustomization.yaml
- teleport/overlays/gcp/nodes/cydec.yaml
- teleport/overlays/gcp/nodes/ept.yaml
> Add Teleport nodes for all tenant teams

- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmalertmanager-largeset.yaml
- monitoring/base/victoriametrics/vmalertmanager-smallset.yaml
- monitoring/base/victoriametrics/vmsingle-smallset.yaml
- test/setup_test.go
> victoriametrics: pod of smallset run in the same node

- team-management/base/ept/app-ept-plantuml.yaml
- team-management/base/ept/kustomization.yaml
- team-management/base/ept/project.yaml
- team-management/base/maneki/project.yaml
> Add app-ept-plantuml namespace

- Makefile
> fix setup in Makefile for golang 1.16

- monitoring/base/grafana-operator/dashboards/kustomization.yaml
- monitoring/base/grafana-operator/dashboards/loki-canary.yaml
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/logging-alertrule.yaml
- monitoring/base/victoriametrics/rules/logging-scrape.yaml
> add a dashboard and alert rules for loki

- topolvm/base/config/lvmd.yaml
- topolvm/base/kustomization.yaml
- topolvm/base/lvmd.yaml
- topolvm/base/upstream/lvmd/kustomization.yaml
- topolvm/base/upstream/lvmd/lvmd-configmap.yaml
- topolvm/base/upstream/lvmd/lvmd.yaml
- topolvm/base/upstream/overlays/daemonset-scheduler/kustomization.yaml
- topolvm/base/upstream/overlays/deployment-scheduler/kustomization.yaml
- introduce lvmd daemonset.
- set lvmd-socket option of topolvm-node to communicate with lvmd daemonset.
> topolvm: update version to 0.8.2

- Makefile
- docs/maintenance.md
- elastic/base/crd.yaml
- elastic/base/upstream/all-in-one.yaml
- elastic/base/validatingwebhookconfiguration.yaml
- test/setup_test.go
- test/team-management_test.go
> eck: update to 1.5.0

- bin/run-test.sh
- test/Makefile
- test/argocd-ingress_test.go
- test/contour_test.go
- test/hpa_test.go
- test/metallb_test.go
- test/monitoring_test.go
- test/run_test.go
- test/sandbox_test.go
- test/suite_test.go
- test/teleport_test.go
This PR lets neco-apps CI pass once after cke-localproxy is installed.
> Fix test for reinstallation for cke-localproxy

- test/reboot_test.go
This PR fixes the reboot test for the new implementation of `neco power`.
* change the subcommand name from `ipmipower` to `power`
* fix not to call `neco power start` for the running boot servers
* remove the retries of `neco power stop/start`
* remove the special treatment of rack-3
> test: fix reboot test for new "neco power"

- neco-admission/base/deployment.yaml
This PR removes temporal image validation
> Remove temporal image validation

- monitoring/base/victoriametrics/rules/etcd-alertrule.yaml
- test/vmalert_test/etcd.yaml
> add alerts for CKE etcd backup

- monitoring/base/victoriametrics/rules/monitoring-alertrule.yaml
- test/vmalert_test/monitoring.yaml
> Changed the alert time threshold depending on whether rolling reboot is in progress or not.

- test/setup_test.go
> Remove upgrade step for PR 1366

- argocd-config/base/ingress.yaml
- ingress/base/patch/crd.yaml
This PR fixes OutOfSync error in ingress application.
> Remove preserveUnknownFields patch

- test/setup_test.go
> Overwrite privileged label

- namespaces/base/domestic-egress.yaml
> Fix privileged label for domestic-egress namespace

- test/validation_test.go
This PR removes a test that checks branches of tenant apps being deployed to clusters.
Formerly, specification of branches is maintained in multiple YAML files, causing it prone to errors.
Now the branches of tenant apps is maintained by a single JSON file (`team-management/template/settings.json`), this double check can be removed.
> team-management: remove validation for tenant app destination

- Makefile
- argocd-config/base/kustomization.yaml
- argocd-config/base/moco.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/moco.yaml
- moco/base/kustomization.yaml
- moco/base/namespace.yaml
- moco/base/upstream/moco.yaml
- neco-admission/base/webhook.yaml
- test/moco_test.go
- test/suite_test.go
- test/team-management_test.go
- test/testdata/moco.yaml
- test/validation_test.go
> moco: deploy moco v0.8.2

- customer-egress/base/kustomization.yaml
> update squid to 4.15

- test/testdata/setup-teleport.yaml
> Add comment for teleport setting

- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/moco-scrape.yaml
- test/testdata/moco.yaml
> moco: add scrape rules

- monitoring/overlays/gcp/victoriametrics/vmsingle-smallset.yaml
> Remove PodAntiAffinity for vmsingle

- external-dns/overlays/gcp/deployment.yaml
- external-dns/overlays/neco-dev/deployment.yaml
- external-dns/overlays/osaka0/deployment.yaml
- external-dns/overlays/stage0/deployment.yaml
- external-dns/overlays/tokyo0/deployment.yaml
- test/metallb_test.go
- test/testdata/metallb.yaml
> [external-dns] Support ServiceSource

- ingress/base/contour/01-crds.yaml
- ingress/base/contour/02-job-certgen.yaml
- ingress/base/contour/02-role-contour.yaml
- ingress/base/contour/03-contour.yaml
- ingress/base/contour/03-envoy.yaml
- ingress/base/kustomization.yaml
> upgrade contour to v1.15.1 and envoy to v1.18.3

- Makefile
- docs/maintenance.md
> update maintenance procedure

- topolvm/base/kustomization.yaml
- topolvm/base/upstream/base/controller.yaml
- topolvm/base/upstream/base/crd.yaml
- topolvm/base/upstream/base/mutatingwebhooks.yaml
- topolvm/base/upstream/overlays/daemonset-scheduler/kustomization.yaml
- topolvm/base/upstream/overlays/daemonset-scheduler/scheduler.yaml
- topolvm/base/upstream/overlays/deployment-scheduler/kustomization.yaml
> update topolvm to v0.8.3

- pvc-autoresizer/base/upstream/default/kustomization.yaml
> update pvc-autoresizer to v 0.1.5

- team-management/base/cydec/project.yaml
- team-management/base/dbre/project.yaml
- team-management/base/ept/project.yaml
- team-management/base/garoon/project.yaml
- team-management/base/maneki/project.yaml
- team-management/template/team-management/base/team-template/project.libsonnet
- test/validation_test.go
> Enable to deploy dev-* ns for tenant teams

- docs/maintenance.md
- rook/base/ceph-hdd/cephobjectstore.yaml
- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-hdd/role.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/ceph-ssd/role.yaml
- rook/base/common/clusterrole.yaml
- rook/base/common/kustomization.yaml
- rook/base/common/patch.yaml
- rook/base/common/resources.yaml
- rook/base/upstream/chart/templates/clusterrole.yaml
- rook/base/upstream/chart/templates/deployment.yaml
- rook/base/upstream/chart/templates/resources.yaml
- rook/base/upstream/chart/templates/role.yaml
- rook/base/upstream/chart/values.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/upstream/toolbox.yaml
- rook/base/values.yaml
- test/team-management_test.go
> upgrade rook to v1.6.2.1

- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/common/resources.yaml
- rook/base/upstream/chart/templates/resources.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/upstream/toolbox.yaml
- rook/base/values.yaml
> update rook to v1.6.3

- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- test/vmalert_test/kubernetes.yaml
> Use group_left

- docs/maintenance.md
- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/values.yaml
> update ceph to 16.2.4.1

- team-management/template/teleport/base/kustomization.libsonnet
- teleport/base/kustomization.yaml
- teleport/base/restart/cronjob.yaml
- teleport/base/restart/kustomization.yaml
- teleport/base/restart/rbac.yaml
There is a problem that teleport does not reload certificates.
https://github.com/gravitational/teleport/issues/3815
We will restart teleport periodically to avoid this problem.
> Restart teleport-proxy periodically

- .circleci/config.yml
This reverts commit 9cb236408a3581aa3700238674c6ae0271ffee6c.
> Revert "Disable upgrade tests temporarily"

- moco/base/upstream/moco.yaml
- test/team-management_test.go
> moco: update to 0.9.2

- teleport/base/restart/cronjob.yaml
> Set securityContext for restart-teleport-proxy

- .circleci/config.yml
- bin/run-test.sh
- cert-manager/overlays/gcp/clusterissuer.yaml
- cert-manager/overlays/neco-dev/clusterissuer.yaml
- test/README.md
- test/contour_test.go
- test/setup_test.go
> Use SelfSigned Issuer on GCP

- neco-admission/base/config.yaml
- team-management/template/neco-admission/base/config.libsonnet
> team-management: allow apps from es-cluster-allocator

- argocd-config/overlays/gcp/kustomization.yaml
- argocd-config/overlays/gcp/namespaces.yaml
- namespaces/overlays/gcp/ceph-poc.yaml
- namespaces/overlays/gcp/kustomization.yaml
- namespaces/overlays/stage0/ceph-poc.yaml
- namespaces/overlays/stage0/kustomization.yaml
- rook/base/values-poc.yaml
- rook/overlays/gcp/kustomization.yaml
- rook/poc/ceph-poc/cephblockpool.yaml
- rook/poc/ceph-poc/cephobjectstore.yaml
- rook/poc/ceph-poc/cluster.yaml
- rook/poc/ceph-poc/clusterrolebinding/clusterrolebinding.yaml
- rook/poc/ceph-poc/clusterrolebinding/kustomization.yaml
- rook/poc/ceph-poc/configmap.yaml
- rook/poc/ceph-poc/deployment.yaml
- rook/poc/ceph-poc/kustomization.yaml
- rook/poc/ceph-poc/operator.yaml
- rook/poc/ceph-poc/role.yaml
- rook/poc/ceph-poc/rolebinding.yaml
- rook/poc/ceph-poc/serviceaccount.yaml
- test/storage_test.go
add a PoC rook/ceph cluster to evaluate RGW performance improvement with SSD using the index.
> add ceph-poc

- .circleci/config.yml
- bin/run-test.sh
- test/.gitignore
- test/Makefile
- test/README.md
> Remove ZeroSSL secret related operations

- bmc-reverse-proxy/base/bmc-reverse-proxy/deployment.yaml
> Update bmc-reverse-proxy for Go 1.16.5

- monitoring/base/victoriametrics/rules/etcd-alertrule.yaml
- test/vmalert_test/etcd.yaml
part of https://github.com/cybozu-go/neco/issues/1613
> revise alret rule to avoid LogicalDatabaseUsageIncreaseRapidly false positives

- rook/poc/ceph-poc/configmap.yaml
> Rook/Ceph: disable dynamic resharding for performance mesurment

- test/monitoring_test.go
When the ConfigMap for a VMAlertmanager is updated, VictoriaMetrics
operator should update the StatefulSet for the VMAlertmanager
to refer to the new ConfigMap.
The operator sometimes fails to do this because the old StatefulSet
gets unstable due to the deletion of the old ConfigMap.
The operator cannot reconcile unstable StatefulSets.
So this PR adds a function to delete the old StatefulSet until
the StatefulSet refers to the proper ConfigMap.
> Delete old StatefulSets for VMAlertmanagers

- test/monitoring_test.go
> Fix test messages

- secrets/base/teleport/kustomization.yaml
- teleport/base/statefulset.yaml
> Update secret name for Teleport to sync with new Kustomize

- test/network-policy_test.go
It would be nice to parse not only API server hostname but also its port number from `~/.kube/config`. The port number may be changed by `ckecli kubernetes issue`.
> parse API server port too from ~/.kube/config

- Makefile
- argocd-config/base/kustomization.yaml
- argocd-config/base/session-log.yaml
- argocd-config/overlays/osaka0/kustomization.yaml
- argocd-config/overlays/osaka0/session-log.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/session-log.yaml
- argocd-config/overlays/tokyo0/kustomization.yaml
- argocd-config/overlays/tokyo0/session-log.yaml
- docs/maintenance.md
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/session-log-alertrule.yaml
- monitoring/base/victoriametrics/rules/session-log-scrape.yaml
- session-log/base/kustomization.yaml
- session-log/base/namespace.yaml
- session-log/base/obc.yaml
- session-log/base/s3gw.yaml
- session-log/overlays/osaka0/kustomization.yaml
- session-log/overlays/osaka0/s3gw.yaml
- session-log/overlays/tokyo0/kustomization.yaml
- session-log/overlays/tokyo0/s3gw.yaml
- test/session-log_test.go
- test/suite_test.go
- test/validation_test.go
- test/vmalert_test/session-log.yaml
part of https://github.com/cybozu-go/neco/issues/1411
> add s3gw for session-log subsystem

- neco-admission/base/webhook.yaml
> Apply PreventDeleteValidator to Services

- logging/base/loki/main.jsonnet
- logging/base/loki/upstream/apps-v1.Deployment-distributor.yaml
- logging/base/loki/upstream/apps-v1.Deployment-query-frontend.yaml
- logging/base/loki/upstream/apps-v1.Deployment-table-manager.yaml
- logging/base/loki/upstream/apps-v1.StatefulSet-compactor.yaml
- logging/base/loki/upstream/apps-v1.StatefulSet-ingester.yaml
- logging/base/loki/upstream/apps-v1.StatefulSet-querier.yaml
- logging/base/loki/upstream/v1.ConfigMap-loki.yaml
- monitoring/overlays/osaka0/grafana-operator/httpproxy.yaml
- monitoring/overlays/stage0/grafana-operator/httpproxy.yaml
- monitoring/overlays/tokyo0/grafana-operator/httpproxy.yaml
- test/testdata/monitoring-grafana-operator.yaml
> monitoring: enable websocket for grafana's live stream logs

- moco/base/upstream/moco.yaml
> Update moco to 0.10.1

- argocd-config/base/prometheus-adapter.yaml
- test/customer-egress_test.go
- test/elastic_test.go
- test/hpa_test.go
- test/local-pv-provisioner_test.go
- test/moco_test.go
- test/setup_test.go
- test/storage_test.go
- test/testdata/customer-egress.yaml
- test/testdata/elastic.yaml
- test/testdata/hpa.yaml
- test/testdata/local-pv.yaml
- test/testdata/moco.yaml
- test/testdata/storage-obc.yaml
- test/testdata/storage-rbd.yaml
- test/testdata/storage-reboot.yaml
- test/testdata/topolvm.yaml
- test/topolvm_test.go
part of https://github.com/cybozu-go/neco-apps/issues/1477
> use another namespace for dctest and drop privilege from sandbox namespace

- neco-admission/base/kustomization.yaml
> admission: update to 0.9.4

- moco/base/upstream/moco.yaml
> Update moco to 0.10.2

- team-management/base/common/project.yaml
- team-management/template/team-management/base/common/main.libsonnet
- team-management/template/team-management/base/common/project.libsonnet
> Allow tenant members to sync Argo CD FOO-apps Applications

- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
- monitoring/base/grafana-operator/dashboards/ceph-osd.yaml
- make dashboards readonly
- make namespace variable be refreshed when the dashboard is loaded
- fix OSD status when showing long term
> monitoring: improve ceph dashboard

- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/values.yaml
- rook/poc/ceph-poc/cluster.yaml
- rook/poc/ceph-poc/deployment.yaml
- test/storage_test.go
- double mgr pods to high availability
- add anti-affinity to spread across racks
> rook: double mgr pods

- moco/base/upstream/moco.yaml
> Update moco to 0.10.3

- moco/base/upstream/moco.yaml
> Update moco to 0.10.4

- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- test/vmalert_test/kubernetes.yaml
> Add a warning alert when persistent volume space exceeds 80%.

- monitoring/base/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/osaka0/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmsingle-smallset.yaml
> Expand VictoriaMetrics smallset storage size.

- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
Issue: https://github.com/cybozu/csa/issues/48
> Dashboard: improve ceph dashboard to detect osds out status

- rook/base/ceph-hdd/cluster.yaml
- rook/poc/ceph-poc/cluster.yaml
> rook: lengthen initialDelaySeconds for slow startup

- moco/base/upstream/moco.yaml
> Update MOCO to 0.10.5

- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/poc/ceph-poc/cluster.yaml
> Rook: extend mon failover timeout

- namespaces/overlays/stage0/ceph-poc-2.yaml
- rook/base/values-poc-2.yaml
- rook/overlays/stage0/kustomization.yaml
- rook/poc/ceph-poc-2/cephblockpool.yaml
- rook/poc/ceph-poc-2/cephobjectstore.yaml
- rook/poc/ceph-poc-2/cluster.yaml
- rook/poc/ceph-poc-2/clusterrolebinding/clusterrolebinding.yaml
- rook/poc/ceph-poc-2/clusterrolebinding/kustomization.yaml
- rook/poc/ceph-poc-2/configmap.yaml
- rook/poc/ceph-poc-2/deployment.yaml
- rook/poc/ceph-poc-2/kustomization.yaml
- rook/poc/ceph-poc-2/operator.yaml
- rook/poc/ceph-poc-2/role.yaml
- rook/poc/ceph-poc-2/rolebinding.yaml
- rook/poc/ceph-poc-2/serviceaccount.yaml
> add ceph-poc-2 cluster

- team-management/template/teleport/overlays/gcp/kustomization.libsonnet
- teleport/base/apps/kustomization.yaml
- teleport/base/apps/vmalertmanager-app-monitoring.yaml
- teleport/overlays/gcp/apps/vmalertmanager-app-monitoring.yaml
- teleport/overlays/gcp/kustomization.yaml
> add vmalertmanager-app-monitoring teleport app

- team-management/base/maneki/app-maneki.yaml
- team-management/base/maneki/dev-maneki.yaml
- team-management/template/team-management/base/team-template/namespace.libsonnet
> add propagate annotations to RoleBindings in root or template namespace

- argocd-config/base/prometheus-adapter.yaml
> fix query parameter for prometheus-adapter

- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/pvc-autoresizer.yaml
> Delete pvc-autoresizer overlay for stage-0.

- meows/overlays/gcp/clusterrole.yaml
- meows/overlays/gcp/kustomization.yaml
- test/setup_test.go
Add a missing role for slack-agent.
The slack-agent needs to get/list pods in many namespaces.
> Add ClusterRole for slack-agent

- ingress/base/kustomization.yaml
> upgrade envoy to 1.18.4

- argocd-config/overlays/neco-dev/kustomization.yaml
- argocd-config/overlays/neco-dev/meows.yaml
- test/meows_test.go
- test/setup_test.go
> Disable meows when secret file does not exist

- meows/overlays/stage0/runnerpool.yaml
> fix runnerpool resouces

- bin/run-test.sh
- test/.gitignore
- test/Makefile
- test/setup_test.go
> Create secrets for ghcr.io and quay.io private repositories

- argocd-config/base/accurate.yaml
- argocd-config/base/init-template.yaml
- argocd-config/base/team-management.yaml
- test/validation_test.go
> Deploy team-management Application after accurate and init-template

- bmc-reverse-proxy/base/bmc-reverse-proxy/deployment.yaml
- bmc-reverse-proxy/base/machines-endpoints/cronjob.yaml
- customer-egress/base/kustomization.yaml
- kube-metrics-adapter/base/apiservice.yaml
- kube-metrics-adapter/base/kustomization.yaml
- kube-metrics-adapter/base/upstream/manifest.yaml
- local-pv-provisioner/base/daemonset.yaml
- monitoring/base/kube-state-metrics/cluster-role-binding.yaml
- monitoring/base/kube-state-metrics/cluster-role.yaml
- monitoring/base/kube-state-metrics/deployment.yaml
- monitoring/base/kube-state-metrics/service-account.yaml
- monitoring/base/kube-state-metrics/service.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/machines-endpoints/cronjob.yaml
- neco-admission/base/kustomization.yaml
- pod-security-admission/base/upstream/install.yaml
- test/network-policy_test.go
- test/run_test.go
- test/team-management_test.go
- test/tools_test.go
> Update manifests before upgrading Kubernetes to 1.21

- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- test/vmalert_test/kubernetes.yaml
This PR add KubeOwnerJobFailed alert rule to check the latest job if the Job has owner(controller, CronJob ,etc...).
And I add KubeJobFailed alert rule to check the job without owner.
Signed-off-by: yamatcha <soju-yamashita@cybozu.co.jp>
> fix KubeJobFailed

- argocd/base/kustomization.yaml
- argocd/base/upstream/install.yaml
- metallb/base/kustomization.yaml
- monitoring/base/kustomization.yaml
- test/Makefile
- Revert Argo CD for now.
- Due to upstream image repo change in https://github.com/cybozu-go/neco-apps/pull/1780, we have to change kustomization too.
> fix container image name

- team-management/base/dbre/app-cybozu-com-mysql-replica.yaml
- team-management/base/dbre/app-cybozu-com-mysql.yaml
- team-management/template/settings.json
> Add alert-group label for dbre

- cert-manager/base/kustomization.yaml
- cert-manager/base/upstream/cert-manager.yaml
> update cert-manager to 1.5.4

- argocd/base/kustomization.yaml
- argocd/base/upstream/install.yaml
- test/Makefile
- test/argocd-ingress_test.go
> update argocd to 2.1.2.2, dex to 2.27.0.4, redis to 6.2.5.1

- meows/overlays/stage0/runnerpool.yaml
> update to dctest-meows-runner:0.3.1.3

- test/setup_test.go
> Create private repository secret from file

- metallb/base/deployment.yaml
> Change maxUnavailable of MetalLB speaker

- argocd-config/base/rook.yaml
- rook/base/ceph-hdd/cephobjectstore.yaml
- rook/poc/ceph-poc/cephobjectstore.yaml
- test/setup_test.go
> Disable auto-sync for rook app

- monitoring/base/grafana-operator/operator.yaml
- sandbox/overlays/gcp/grafana/statefulset.yaml
> update grafana to 8.1.5.1

- test/contour_test.go
- test/testdata/contour-httpproxy.yaml
> use .spec.ingressClassName in HTTPProxy test

- monitoring/base/grafana-operator/dashboards/kustomization.yaml
- monitoring/base/grafana-operator/dashboards/victoriametrics-vmalert.yaml
> add grafana dashboard for vmalert

- customer-egress/base/kustomization.yaml
> upgrade squid to 5.2.1

- monitoring/base/victoriametrics/vmcluster-largeset.yaml
- monitoring/overlays/osaka0/victoriametrics/vmcluster-largeset.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmcluster-largeset.yaml
> use ceph-ssd-block for vmcluster-largeset on gcp and stage0

- monitoring/base/grafana-operator/dashboards/coil.yaml
> Fix Grafana Dashboard for Coil

- monitoring/base/victoriametrics/vmagent-largeset.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmalertmanager-largeset.yaml
- monitoring/base/victoriametrics/vmcluster-largeset.yaml
add loose rack spreading and strict node spreading
> add topologySpreadConstraints to VictoriaMetrics Pods

- monitoring/base/victoriametrics/rules/moco-scrape.yaml
> Set honor_labels for moco-controler metrics

- monitoring/base/victoriametrics/rules/rook-scrape.yaml
- monitoring/overlays/gcp/kustomization.yaml
- monitoring/overlays/gcp/victoriametrics/rules/rook-scrape.yaml
- neco-admission/base/kustomization.yaml
- neco-admission/base/upstream/manifests.yaml
- neco-admission/base/webhook.yaml
- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-object-store/cluster.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/poc/ceph-poc-2/cephobjectstore.yaml
- rook/poc/ceph-poc-2/cluster.yaml
- rook/poc/ceph-poc/cluster.yaml
- test/accurate_test.go
[image_list.txt](https://26443-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.10.29-26452

- meows/overlays/stage0/runnerpool.yaml
> Fix a mount path of a working directory for dctest-runner

- meows/overlays/stage0/runnerpool.yaml
[image_list.txt](https://26481-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.11.01-26484

- test/setup_test.go
- test/storage_test.go
part of https://github.com/cybozu-go/neco/issues/1793
Signed-off-by: UMEZAWA Takeshi takeshi-umezawa@cybozu.co.jp
> increase cs nodes

- monitoring/base/kube-state-metrics/cluster-role-binding.yaml
- monitoring/base/kube-state-metrics/cluster-role.yaml
- monitoring/base/kube-state-metrics/deployment.yaml
- monitoring/base/kube-state-metrics/service-account.yaml
- monitoring/base/kube-state-metrics/service.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/patch-kube-state-metrics.yaml
- test/monitoring_test.go
part of https://github.com/cybozu-go/neco/issues/1802
> scrape more labels and annotations by kube-state-metrics

- moco/base/upstream/moco.yaml
> Update MOCO to v0.10.7

- .gitignore
- Makefile
- argocd-config/base/topolvm.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/topolvm.yaml
- argocd/base/configmap.yaml
- docs/maintenance.md
- test/Makefile
- test/setup_test.go
- test/validation_test.go
- topolvm/base/kustomization.yaml
- topolvm/base/values.yaml
> update topolvm 0.10.1

- .gitignore
- Makefile
- argocd-config/base/topolvm.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/topolvm.yaml
- argocd/base/configmap.yaml
- bin/run-test.sh
- docs/maintenance.md
- test/.gitignore
- test/Makefile
- test/setup_test.go
- test/validation_test.go
- topolvm/base/kustomization.yaml
- topolvm/base/values.yaml
[image_list.txt](https://26642-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.11.04-26645

- monitoring/base/victoriametrics/vmagent-largeset.yaml
- monitoring/base/victoriametrics/vmagent-smallset.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- monitoring/base/victoriametrics/vmalertmanager-largeset.yaml
- monitoring/base/victoriametrics/vmalertmanager-smallset.yaml
- test/validation_test.go
> Add XxxNamespaceSelector to workload custom resources

- test/network-policy_test.go
> remove duplicate test in network-policy_test.go

- argocd-config/base/accurate.yaml
- test/accurate_test.go
> Propagate `pod-security.cybozu.com/policy` label

- test/reboot_test.go
- test/setup_test.go
part of https://github.com/cybozu-go/neco/issues/1793
https://github.com/cybozu-go/neco-apps/pull/1884 was not sufficient.
> fix reboot test to follow cs increasing

- argocd-config/base/meows.yaml
- test/setup_test.go
This reverts commit f4c0e31761eaaeaed1a3ad6452651cb171f16c69.
> Enable auto-sync of meows application

- argocd-config/base/meows.yaml
- test/reboot_test.go
- test/setup_test.go
[image_list.txt](https://26782-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.11.08-26801

- rook/base/ceph-hdd/deployment.yaml
- rook/base/ceph-object-store/deployment.yaml
- rook/base/ceph-ssd/deployment.yaml
- rook/base/upstream/chart/templates/clusterrolebinding.yaml
- rook/base/upstream/chart/templates/resources.yaml
- rook/base/upstream/chart/templates/role.yaml
- rook/base/upstream/chart/values.yaml
- rook/base/upstream/kustomization.yaml
- rook/base/upstream/toolbox.yaml
- rook/base/values.yaml
- rook/poc/ceph-poc-2/deployment.yaml
- rook/poc/ceph-poc/deployment.yaml
Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>
> rook: update rook to 1.7.7.1

- .gitignore
- Makefile
- argocd-config/base/pvc-autoresizer.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/pvc-autoresizer.yaml
- docs/maintenance.md
- pvc-autoresizer/base/kustomization.yaml
- pvc-autoresizer/base/values.yaml
> Update pvc-autoresizer to 0.3.2.

- rook/overlays/stage0/kustomization.yaml
> Resize ceph-ssd at stage0.

- rook/overlays/osaka0/ceph-object-store/httpproxy.yaml
- rook/overlays/osaka0/kustomization.yaml
- rook/overlays/stage0/ceph-object-store/httpproxy.yaml
- rook/overlays/stage0/kustomization.yaml
- rook/overlays/tokyo0/ceph-object-store/httpproxy.yaml
- rook/overlays/tokyo0/kustomization.yaml
> Add HTTPProxy for ceph-object-store.

- monitoring/base/victoriametrics/rules/kubernetes-scrape.yaml
- network-policy/base/policies/monitoring.yaml
- test/validation_test.go
part of https://github.com/cybozu-go/neco-apps/issues/1927
> scrape kube-proxy metrics

- meows/overlays/stage0/runnerpool.yaml
> Fixed the way dctest-runner mounts the WorkingDirectory.

- test/bmc-reverse-proxy_test.go
- test/contour_test.go
- test/customer-egress_test.go
- test/domestic-egress_test.go
- test/elastic_test.go
- test/local-pv-provisioner_test.go
- test/meows_test.go
- test/metallb_test.go
- test/moco_test.go
- test/monitoring_test.go
- test/network-policy_test.go
- test/replica_test.go
- test/sandbox_test.go
- test/setup_test.go
- test/storage_test.go
> refactor: Deployment/StatefulSet/DaemonSet replica check

- test/elastic_crds/kustomization.yaml
- test/setup_test.go
> elastic: remove temporary upgrade steps

- meows/overlays/stage0/runnerpool.yaml
> Enable the organization level runner of dctest-runner

- monitoring/base/grafana-operator/operator.yaml
- sandbox/overlays/gcp/grafana/statefulset.yaml
part of https://github.com/cybozu-go/neco/issues/1815
> upgrade grafana to 8.2.3.1

- meows/overlays/stage0/runnerpool.yaml
- monitoring/base/grafana-operator/operator.yaml
- sandbox/overlays/gcp/grafana/statefulset.yaml
- test/bmc-reverse-proxy_test.go
- test/contour_test.go
- test/customer-egress_test.go
- test/domestic-egress_test.go
- test/elastic_crds/kustomization.yaml
- test/elastic_test.go
- test/local-pv-provisioner_test.go
- test/meows_test.go
- test/metallb_test.go
- test/moco_test.go
- test/monitoring_test.go
- test/network-policy_test.go
- test/replica_test.go
- test/sandbox_test.go
- test/setup_test.go
- test/storage_test.go
[image_list.txt](https://27099-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.11.11-27100

- test/meows_test.go
- test/metrics_test.go
- test/monitoring_test.go
- test/topolvm_test.go
> refactor: metrics querying

- test/setup_test.go
> Remove obsolete upgrade operations

- argocd-config/base/moco.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- argocd-config/overlays/stage0/moco.yaml
- test/validation_test.go
> Update MOCO to 0.10.8 (chart: 0.1.1)

- meows/overlays/gcp/kustomization.yaml
- meows/overlays/gcp/upstream/agent/kustomization.yaml
- meows/overlays/gcp/upstream/controller/kustomization.yaml
- meows/overlays/stage0/runnerpool.yaml
- test/testdata/meows-runnerpool.tmpl.yaml
> Update meows to v0.4.1

- rook/overlays/stage0/kustomization.yaml
> Rook/Ceph: expand capacity of stage0 ceph-ssd

- monitoring/base/victoriametrics/operator.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmagents.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalerts.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmauths.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmclusters.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmnodescrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmpodscrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmprobes.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmservicescrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmsingles.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmstaticscrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmusers.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmagents.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmalerts.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmauths.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmclusters.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmnodescrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmpodscrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmprobes.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmservicescrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmsingles.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmstaticscrapes.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmusers.yaml
part of https://github.com/cybozu-go/neco/issues/1810
> upgrade to VictoriaMetrics operator 0.20.3.1

- test/setup_test.go
Argocd synchronization process takes so long even after all applications have been synched because each request of `argocd app get` in checkAllAppsSynced takes more than 1 second.
> Use argocd app list instead of argocd app get in checkAllAppsSynced

- rook/base/ceph-hdd/configmap.yaml
- rook/base/ceph-object-store/configmap.yaml
- rook/base/ceph-ssd/configmap.yaml
- rook/overlays/gcp/ceph-hdd/debug.yaml
- rook/overlays/gcp/ceph-object-store/debug.yaml
- rook/poc/ceph-poc-2/configmap.yaml
- rook/poc/ceph-poc/configmap.yaml
> Rook/Ceph: fix target component of the config

- monitoring/base/grafana-operator/kustomization.yaml
- monitoring/base/grafana-operator/mysql.yaml
- monitoring/base/victoriametrics/rules/moco-alertrule.yaml
- monitoring/overlays/gcp/kustomization.yaml
- test/setup_test.go
- test/vmalert_test/moco.yaml
add MySQL for Grafana to use it later.
Grafana's configuration will be changed in https://github.com/cybozu-go/neco-apps/pull/2006
part of https://github.com/cybozu-go/neco/issues/1805
> Grafana HA, step1

- argocd-config/base/moco.yaml
> Update MOCO v0.10.9 (chart v0.1.2)

- monitoring/base/grafana-operator/grafana.yaml
- monitoring/overlays/gcp/grafana-operator/grafana.yaml
- monitoring/overlays/gcp/kustomization.yaml
- test/monitoring_test.go
- increase the number of Grafana's replicas
- use MySQL as Grafana's database
part of https://github.com/cybozu-go/neco/issues/1805
> Grafana HA, step2

- meows/overlays/stage0/kustomization.yaml
> stop dctest-runner

- meows/overlays/stage0/kustomization.yaml
- monitoring/base/grafana-operator/grafana.yaml
- monitoring/overlays/gcp/grafana-operator/grafana.yaml
- monitoring/overlays/gcp/kustomization.yaml
- test/monitoring_test.go
[image_list.txt](https://27613-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.11.22-27614

- teleport/base/deployment.yaml
workaround for recent teleport failure
> decrease number of replicas of teleport-proxy to 1

- neco-admission/base/config.yaml
- team-management/template/neco-admission/base/config.libsonnet
> Allow kintone-neco to deploy from kintone-private

- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
- neco-admission/base/config.yaml
- team-management/template/neco-admission/base/config.libsonnet
- teleport/base/deployment.yaml
- test/monitoring_test.go
- test/vmalert_test/kubernetes.yaml
[image_list.txt](https://27726-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.11.26-27728

- team-management/base/csa/project.yaml
- team-management/template/settings.json
> team: move app-forest-archive to app-csa

- team-management/base/csa/project.yaml
- team-management/base/maneki/project.yaml
- team-management/template/settings.json
> team: add app-csa-* namespace

- customer-egress/base/neco/squid.yaml
- customer-egress/base/squid.yaml
> Update PDB API version

- team-management/template/teleport/overlays/gcp/kustomization.libsonnet
- teleport/base/apps/kustomization.yaml
- teleport/base/apps/vmalertmanager-app-csa-monitoring.yaml
- teleport/overlays/gcp/apps/vmalertmanager-app-csa-monitoring.yaml
- teleport/overlays/gcp/kustomization.yaml
> teleport: add CSA Alertmanager application to teleport

- meows/overlays/gcp/deployment.yaml
- meows/overlays/gcp/kustomization.yaml
- meows/overlays/gcp/upstream/agent/kustomization.yaml
- meows/overlays/gcp/upstream/controller/deployment.yaml
- meows/overlays/gcp/upstream/controller/kustomization.yaml
- meows/overlays/gcp/upstream/controller/webhook.yaml
- meows/overlays/gcp/upstream/crd/bases/meows.cybozu.com_runnerpools.yaml
- meows/overlays/gcp/upstream/runnerpool/sample.yaml
- meows/overlays/stage0/deployment.yaml
- meows/overlays/stage0/runnerpool.yaml
- test/testdata/meows-runnerpool.tmpl.yaml
> Update meows to v0.5.0

- meows/overlays/gcp/deployment.yaml
- meows/overlays/gcp/kustomization.yaml
- meows/overlays/gcp/upstream/agent/kustomization.yaml
- meows/overlays/gcp/upstream/controller/deployment.yaml
- meows/overlays/gcp/upstream/controller/kustomization.yaml
- meows/overlays/gcp/upstream/controller/webhook.yaml
- meows/overlays/gcp/upstream/crd/bases/meows.cybozu.com_runnerpools.yaml
- meows/overlays/gcp/upstream/runnerpool/sample.yaml
- meows/overlays/stage0/deployment.yaml
- meows/overlays/stage0/runnerpool.yaml
- monitoring/base/victoriametrics/rules/node-alertrule.yaml
- team-management/template/teleport/overlays/gcp/kustomization.libsonnet
- teleport/base/apps/kustomization.yaml
- teleport/base/apps/vmalertmanager-app-csa-monitoring.yaml
- teleport/overlays/gcp/apps/vmalertmanager-app-csa-monitoring.yaml
- teleport/overlays/gcp/kustomization.yaml
- test/testdata/meows-runnerpool.tmpl.yaml
- test/vmalert_test/node.yaml
- topolvm/base/kustomization.yaml
[image_list.txt](https://27990-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.12.07-28003

- team-management/template/teleport/base/kustomization.libsonnet
- teleport/base/kustomization.yaml
> teleport: mount boot-admin-role setting

- session-log/base/obc.yaml
- session-log/base/s3gw.yaml
> session-log: Migrate session-log to ceph-object-store.

- kube-metrics-adapter/base/kustomization.yaml
- logging/base/loki/kustomization.yaml
- monitoring/base/ingress-health/deployment.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/victoriametrics/operator.yaml
- session-log/base/s3gw.yaml
Regular update in December 2021.
I update to use images which are created by the following PR.
https://github.com/cybozu/neco-containers/pull/703
https://github.com/cybozu/neco-containers/pull/704
> Update base images

- argocd-config/base/accurate.yaml
- monitoring/base/grafana-operator/dashboards/sabakan.yaml
- test/accurate_test.go
- test/monitoring_test.go
- test/team-management_test.go
- test/teleport_test.go
- test/testdata/accurate-propagated.yaml
- test/testdata/accurate-subnamespace.yaml
[image_list.txt](https://28181-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.12.10-28183

- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
- monitoring/base/grafana-operator/dashboards/ceph-osd.yaml
> dashboard: make datasource selectable

- meows/overlays/stage0/kustomization.yaml
- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
- monitoring/base/grafana-operator/dashboards/ceph-osd.yaml
[image_list.txt](https://28265-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.12.13-28276

- session-log/base/obc.yaml
> session-log: Remove unused OBC.

- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
- monitoring/base/grafana-operator/dashboards/kustomization.yaml
> Add a dashboard of CSA Overview

- test/metallb_test.go
> fix metallb access test from boot-0

- session-log/base/obc.yaml
[image_list.txt](https://28306-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.12.14-28317

- meows/overlays/stage0/runnerpool.yaml
> decrease dctest-runner replicas

- argocd-config/base/accurate.yaml
- test/accurate_test.go
- test/testdata/accurate-invalid-subnamespace.yaml
- test/testdata/accurate-propagated.yaml
- test/testdata/accurate-subnamespace.yaml
> Update accurate's Helm chart to 0.2.3 and enable a naming policy.

- team-management/base/dbre/kustomization.yaml
- team-management/base/dbre/project.yaml
- team-management/base/dbre/team-dbre.yaml
- team-management/base/kintone-neco/kustomization.yaml
- team-management/base/kintone-neco/project.yaml
- team-management/base/kintone-neco/team-kintone.yaml
- team-management/base/maneki/project.yaml
- team-management/template/settings.json
- test/setup_test.go
> Use team-kintone and team-dbre

- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
> monitoring: extend alert window for KubePodCrashLooping

- monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
[image_list.txt](https://28526-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.12.17-28533

- argocd-config/base/prometheus-adapter.yaml
- bmc-reverse-proxy/base/bmc-reverse-proxy/deployment.yaml
- bmc-reverse-proxy/base/machines-endpoints/cronjob.yaml
- customer-egress/base/kustomization.yaml
- docs/maintenance.md
- kube-metrics-adapter/base/kustomization.yaml
- local-pv-provisioner/base/daemonset.yaml
- monitoring/base/kube-state-metrics/cluster-role-binding.yaml
- monitoring/base/kube-state-metrics/cluster-role.yaml
- monitoring/base/kube-state-metrics/deployment.yaml
- monitoring/base/kube-state-metrics/service-account.yaml
- monitoring/base/kube-state-metrics/service.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/machines-endpoints/cronjob.yaml
- sealed-secrets/base/deployment.yaml
- sealed-secrets/base/kustomization.yaml
- sealed-secrets/base/upstream/controller.yaml
- test/setup_test.go
part of https://github.com/cybozu-go/neco-apps/issues/2075
> update manifests for k8s 1.22

- argocd-config/base/prometheus-adapter.yaml
- bmc-reverse-proxy/base/bmc-reverse-proxy/deployment.yaml
- bmc-reverse-proxy/base/machines-endpoints/cronjob.yaml
- customer-egress/base/kustomization.yaml
- docs/maintenance.md
- kube-metrics-adapter/base/kustomization.yaml
- local-pv-provisioner/base/daemonset.yaml
- monitoring/base/kube-state-metrics/cluster-role-binding.yaml
- monitoring/base/kube-state-metrics/cluster-role.yaml
- monitoring/base/kube-state-metrics/deployment.yaml
- monitoring/base/kube-state-metrics/service-account.yaml
- monitoring/base/kube-state-metrics/service.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/machines-endpoints/cronjob.yaml
- sealed-secrets/base/deployment.yaml
- sealed-secrets/base/kustomization.yaml
- sealed-secrets/base/upstream/controller.yaml
- team-management/base/dbre/team-dbre.yaml
- team-management/template/settings.json
- test/setup_test.go
[image_list.txt](https://28687-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2021.12.23-28696

- test/setup_test.go
> test: remove transitional setup code

- argocd-config/base/prometheus-adapter.yaml
- argocd-config/base/rook.yaml
- metallb/base/kustomization.yaml
- metallb/base/upstream/example-config.yaml
- metallb/base/upstream/metallb.yaml
- metallb/base/upstream/prometheus-operator.yaml
- monitoring/README.md
- monitoring/base/kustomization.yaml
- monitoring/base/victoriametrics/operator.yaml
- monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmagents.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalerts.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmauths.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmclusters.yaml
- monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmsingles.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmagents.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmalerts.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmauths.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmclusters.yaml
- monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmsingles.yaml
- monitoring/base/victoriametrics/upstream/rbac/role.yaml
- monitoring/base/victoriametrics/vmalert-largeset.yaml
- monitoring/base/victoriametrics/vmalert-smallset.yaml
- test/vmalert_test/sabakan.yaml
[image_list.txt](https://28850-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.04-28856

- teleport/base/service.yaml
> teleport: relinquish external IP of teleport-auth

- teleport/base/service.yaml
[image_list.txt](https://28901-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.05-28902

- test/setup_test.go
> Remove upgrade procedure

- elastic/base/statefulset.yaml
- elastic/base/upstream/crds.yaml
- elastic/base/upstream/operator.yaml
> Update ECK to v1.9.1

- test/setup_test.go
> Fix upgrade test

- Makefile
- monitoring/base/grafana-operator/deployment.yaml
- sandbox/overlays/gcp/grafana/statefulset.yaml
> Grafana v8.3.3

- pvc-autoresizer/base/kustomization.yaml
> pvc-autoresizer: Bump version to 0.2.2.

- topolvm/base/kustomization.yaml
> topolvm: version up to 0.10.4

- monitoring/base/grafana-operator/dashboards/cert-manager.yaml
- monitoring/base/victoriametrics/rules/cert-manager-scrape.yaml
- network-policy/base/kustomization.yaml
- network-policy/base/policies/hubble-relay.yaml
- test/setup_test.go
- test/suite_test.go
- test/team-management_test.go
[image_list.txt](https://29231-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.13-29240

- Makefile
- monitoring/base/grafana-operator/deployment.yaml
- pvc-autoresizer/base/kustomization.yaml
- sandbox/overlays/gcp/grafana/statefulset.yaml
[image_list.txt](https://29256-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.14-29276

- meows/overlays/stage0/kustomization.yaml
- meows/overlays/stage0/runnerpool.yaml
Adjsut `dctest-runner` to meows 0.6.0.
> Adjsut dctest-runner to meows 0.6.0

- meows/overlays/stage0/kustomization.yaml
- meows/overlays/stage0/runnerpool.yaml
[image_list.txt](https://29492-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.21-29506

- monitoring/base/victoriametrics/rules/cert-manager-scrape.yaml
[image_list.txt](https://29543-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.24-29548

- neco-admission/overlays/neco-dev/kustomization.yaml
- neco-admission/overlays/neco-dev/webhook.yaml
> Disable ApplicationValidator on neco-dev

- monitoring/base/victoriametrics/rules/kubernetes-scrape.yaml
- neco-admission/overlays/neco-dev/kustomization.yaml
- neco-admission/overlays/neco-dev/webhook.yaml
- network-policy/base/global-policies/controller-manager.yaml
[image_list.txt](https://29633-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.25-29644

- meows/overlays/gcp/deployment.yaml
- meows/overlays/gcp/kustomization.yaml
- meows/overlays/gcp/upstream/agent/kustomization.yaml
- meows/overlays/gcp/upstream/controller/kustomization.yaml
- meows/overlays/stage0/runnerpool.yaml
[image_list.txt](https://29678-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.27-29692

- monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml
- test/vmalert_test/sabakan.yaml
[image_list.txt](https://29682-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.01.28-29709

- monitoring/base/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/osaka0/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmsingle-smallset.yaml
> Extend pvc size used by vmsingle-smallset

- Makefile
- argocd-config/overlays/stage0/grafana-sandbox.yaml
- argocd-config/overlays/stage0/kustomization.yaml
- grafana-sandbox/README.md
- grafana-sandbox/base/kustomization.yaml
- grafana-sandbox/overlays/common/config/grafana.ini
- grafana-sandbox/overlays/common/config/providers.yaml
- grafana-sandbox/overlays/common/grafana-sandbox-alertrule.yaml
- grafana-sandbox/overlays/common/grafana-sandbox-scrape.yaml
- grafana-sandbox/overlays/common/grafana.yaml
- grafana-sandbox/overlays/common/kustomization.yaml
- grafana-sandbox/overlays/common/service.yaml
- grafana-sandbox/overlays/gcp/grafana.yaml
- grafana-sandbox/overlays/gcp/kustomization.yaml
- grafana-sandbox/overlays/gcp/mysql-init.yaml
- grafana-sandbox/overlays/stage0/httpproxy.yaml
- grafana-sandbox/overlays/stage0/kustomization.yaml
- namespaces/base/grafana-sandbox.yaml
- namespaces/base/kustomization.yaml
- test/validation_test.go
part of https://github.com/cybozu-go/neco/issues/1871
> deploy new sandbox Grafana to grafana-sandbox NS

- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
> monitoring: fix wrong expressions of dashboard for TopoLVM

- logging/base/loki-canary/patch.yaml
- logging/base/promtail/patch.yaml
- monitoring/base/cadvisor/daemonset.yaml
> Set maxUnavailable 25% to speed up daemonset restart

- logging/base/loki-canary/patch.yaml
- logging/base/promtail/patch.yaml
- monitoring/base/cadvisor/daemonset.yaml
- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
[image_list.txt](https://29957-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.02.03-29958

- rook/base/ceph-hdd-clusterrolebinding/values.yaml
- rook/base/ceph-hdd.yaml
- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-hdd/values.yaml
- rook/base/ceph-object-store-clusterrolebinding/values.yaml
- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/cluster.yaml
- rook/base/ceph-object-store/kustomization.yaml
- rook/base/ceph-object-store/values.yaml
- rook/base/ceph-poc-2-clusterrolebinding/values.yaml
- rook/base/ceph-poc-2/cluster.yaml
- rook/base/ceph-poc-2/values.yaml
- rook/base/ceph-poc-clusterrolebinding/values.yaml
- rook/base/ceph-poc/cluster.yaml
- rook/base/ceph-poc/kustomization.yaml
- rook/base/ceph-poc/values.yaml
- rook/base/ceph-ssd-clusterrolebinding/values.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/base/ceph-ssd/kustomization.yaml
- rook/base/ceph-ssd/values.yaml
- rook/base/common/values.yaml
- rook/base/toolbox/kustomization.yaml
- rook/base/values.yaml
- rook/overlays/stage0/ceph-poc-2/ceph-poc-2.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
- test/setup_test.go
> rook: update rook to 1.8.3.1

- grafana-sandbox/overlays/common/kustomization.yaml
- grafana-sandbox/overlays/common/rbac.yaml
part of https://github.com/cybozu-go/neco/issues/1871
> add right to read grafana-sandbox's password Secret to tenant users.

- argocd/base/configmap.yaml
See https://github.com/cilium/cilium/issues/17349
> Declare resource exclusions in the ArgoCD ConfigMap not to delete CiliumIdentities

- grafana-sandbox/overlays/common/kustomization.yaml
- grafana-sandbox/overlays/common/rbac.yaml
- rook/base/ceph-hdd-clusterrolebinding/values.yaml
- rook/base/ceph-hdd.yaml
- rook/base/ceph-hdd/cluster.yaml
- rook/base/ceph-hdd/values.yaml
- rook/base/ceph-object-store-clusterrolebinding/values.yaml
- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/cluster.yaml
- rook/base/ceph-object-store/kustomization.yaml
- rook/base/ceph-object-store/values.yaml
- rook/base/ceph-poc-2-clusterrolebinding/values.yaml
- rook/base/ceph-poc-2/cluster.yaml
- rook/base/ceph-poc-2/values.yaml
- rook/base/ceph-poc-clusterrolebinding/values.yaml
- rook/base/ceph-poc/cluster.yaml
- rook/base/ceph-poc/kustomization.yaml
- rook/base/ceph-poc/values.yaml
- rook/base/ceph-ssd-clusterrolebinding/values.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/base/ceph-ssd/kustomization.yaml
- rook/base/ceph-ssd/values.yaml
- rook/base/common/values.yaml
- rook/base/toolbox/kustomization.yaml
- rook/base/values.yaml
- rook/overlays/stage0/ceph-poc-2/ceph-poc-2.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
- test/setup_test.go
[image_list.txt](https://30003-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.02.04-30004

- pvc-autoresizer/base/kustomization.yaml
- topolvm/base/kustomization.yaml
> topolvm: version up to 0.10.5

- argocd-config/base/rook.yaml
- rook/base/ceph-poc/cluster.yaml
Co-authored-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
> rook/ceph: increase hdd osd number of ceph-poc

- Makefile
- argocd-config/base/accurate.yaml
- argocd-config/base/kustomization.yaml
- argocd-config/base/tenet.yaml
- docs/maintenance.md
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/tenet-alertrule.yaml
- monitoring/base/victoriametrics/rules/tenet-scrape.yaml
- namespaces/base/kustomization.yaml
- namespaces/base/tenet.yaml
- neco-admission/base/config.yaml
- team-management/template/neco-admission/base/config.libsonnet
- test/suite_test.go
- test/team-management_test.go
- test/tenet_test.go
- test/testdata/tenet-privileged-ciliumnetworkpolicy.yaml
- test/testdata/tenet-subnamespace.yaml
- test/testdata/tenet.yaml
- test/validation_test.go
- test/vmalert_test/tenet.yaml
Signed-off-by: Hsn723 <antoine@cybozu.co.jp>
> deploy tenet

- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/configmap.yaml
issue: https://github.com/cybozu/csa/issues/9
> Rook/Ceph: disable dynamic resharding on stage and prod.

- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
Signed-off-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>
> increment the number of osds

- Makefile
- argocd-config/base/accurate.yaml
- argocd-config/base/kustomization.yaml
- argocd-config/base/rook.yaml
- argocd-config/base/tenet.yaml
- docs/maintenance.md
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/tenet-alertrule.yaml
- monitoring/base/victoriametrics/rules/tenet-scrape.yaml
- namespaces/base/kustomization.yaml
- namespaces/base/tenet.yaml
- neco-admission/base/config.yaml
- rook/base/ceph-poc/cluster.yaml
- team-management/template/neco-admission/base/config.libsonnet
- test/suite_test.go
- test/team-management_test.go
- test/tenet_test.go
- test/testdata/tenet-privileged-ciliumnetworkpolicy.yaml
- test/testdata/tenet-subnamespace.yaml
- test/testdata/tenet.yaml
- test/validation_test.go
- test/vmalert_test/tenet.yaml
[image_list.txt](https://30248-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.02.14-30257

- bin/run-test.sh
- test/Makefile
- test/monitoring_test.go
- test/suite_test.go
part of https://github.com/cybozu-go/neco/issues/1904
> check alerts after test

- elastic/base/upstream/crds.yaml
- elastic/base/upstream/operator.yaml
part of https://github.com/cybozu-go/neco/issues/1921
> update ECK to 2.0.0

- teleport/overlays/stage0/kustomization.yaml
- teleport/overlays/stage0/statefulset.yaml
> Change pvc name for teleport-auth

- argocd-config/overlays/osaka0/tenants/garoon-apps.yaml
- argocd-config/overlays/tokyo0/tenants/garoon-apps.yaml
- team-management/template/argocd-config/overlays/template/tenants/main.libsonnet
- team-management/template/settings.json
> Change the destination of prod for garoon-apps

- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/configmap.yaml
- rook/base/ceph-poc-2/configmap.yaml
- rook/base/ceph-poc/configmap.yaml
- rook/overlays/gcp/ceph-object-store/debug.yaml
- rook/overlays/stage0/ceph-poc-2/ceph-poc-2.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
> rook/ceph: fix section name for RGW

- argocd/base/configmap.yaml
> ignore unhealthy status of tenant apps

- argocd/base/configmap.yaml
> add health check script for MySQLCluster

- monitoring/base/victoriametrics/rules/topolvm-scrape.yaml
> metrics: fix scraping rule for topolvm.

- monitoring/base/grafana-operator/upstream/manifests/crds.yaml
- monitoring/base/grafana-operator/upstream/manifests/deployment.yaml
- monitoring/base/kustomization.yaml
> upgrade grafana-operator to 4.2.0.1

- ingress/base/kustomization.yaml
> upgrade envoy to 1.19.3.1

- network-policy/base/policies/domestic-egress.yaml
- test/monitoring_test.go
> fix NetworkPolicy to network-nat Egress Pods

- argocd/base/configmap.yaml
- ingress/base/kustomization.yaml
- monitoring/base/grafana-operator/upstream/manifests/crds.yaml
- monitoring/base/grafana-operator/upstream/manifests/deployment.yaml
- monitoring/base/kustomization.yaml
- monitoring/base/victoriametrics/rules/topolvm-scrape.yaml
- network-policy/base/policies/domestic-egress.yaml
- test/monitoring_test.go
[image_list.txt](https://30943-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.02.25-30947

- teleport/overlays/osaka0/kustomization.yaml
- teleport/overlays/osaka0/node-ept.yaml
- teleport/overlays/tokyo0/kustomization.yaml
- teleport/overlays/tokyo0/node-ept.yaml
> Remove unused teleport-node

- test/testdata/cattage-application.yaml
> Fix targetRevision

- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/configmap.yaml
- rook/base/ceph-poc/configmap.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/configmap.yaml
- rook/overlays/gcp/ceph-object-store/debug.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
issue: https://github.com/cybozu/csa/issues/19
> rook: Change mon_osd_down_out_subtree_limit

- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
- monitoring/base/grafana-operator/dashboards/ceph-osd.yaml
- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
- fix selectable datasource
- add a panel of cke reboot queue
- add panels of local-pv-provisioner
- update panels of ceph cluster digests
> monitoring: update dashboard for storage

- monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml
- monitoring/base/grafana-operator/dashboards/ceph-osd.yaml
- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
[image_list.txt](https://31164-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.03.02-31176

- docs/maintenance.md
> fix maintenance.md heading

- topolvm/base/kustomization.yaml
> topolvm: update topolvm version to v0.10.6

- monitoring/base/cadvisor/daemonset.yaml
- monitoring/base/kustomization.yaml
> Update cadvisor to 0.44.0

- monitoring/overlays/osaka0/kustomization.yaml
- monitoring/overlays/osaka0/victoriametrics/vmalertmanager.yaml
- monitoring/overlays/stage0/kustomization.yaml
- monitoring/overlays/stage0/victoriametrics/vmalertmanager.yaml
- monitoring/overlays/tokyo0/kustomization.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmalertmanager.yaml
> set externalURL for VMAlertmanagers

- argocd/base/configmap.yaml
part of https://github.com/cybozu-go/neco/issues/778
> fix argocd-notifications subscription selector

- argocd/base/configmap.yaml
- pvc-autoresizer/base/kustomization.yaml
[image_list.txt](https://31427-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.03.07-31464

- argocd-config/overlays/osaka0/kustomization.yaml
- argocd-config/overlays/osaka0/registry-elastic.yaml
- argocd-config/overlays/osaka0/registry-ghcr.yaml
- argocd-config/overlays/osaka0/registry-quay.yaml
- argocd-config/overlays/tokyo0/kustomization.yaml
- argocd-config/overlays/tokyo0/registry-elastic.yaml
- argocd-config/overlays/tokyo0/registry-ghcr.yaml
- argocd-config/overlays/tokyo0/registry-quay.yaml
- Once performance tuning is complete, I will revert this commit back.
> Remove registries on prod

- monitoring/base/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/osaka0/victoriametrics/vmsingle-smallset.yaml
- monitoring/overlays/tokyo0/victoriametrics/vmsingle-smallset.yaml
> increase vmsingle-smallset PVC size

- monitoring/base/grafana-operator/dashboards/registry.yaml
> Fix registry dashboard

- coil/overlays/stage0/egress.yaml
> Update destinations of domestic-egress/nat

- coil/overlays/stage0/egress.yaml
> Remove unnecessary destination

- monitoring/base/cadvisor/daemonset.yaml
> Extend cAdvisor metrics

- coil/overlays/stage0/egress.yaml
[image_list.txt](https://31630-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.03.10-31667

- rook/base/ceph-object-store-clusterrolebinding/values.yaml
- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/cluster.yaml
- rook/base/ceph-object-store/values.yaml
- rook/base/ceph-poc-clusterrolebinding/values.yaml
- rook/base/ceph-poc/cluster.yaml
- rook/base/ceph-poc/values.yaml
- rook/base/ceph-ssd-clusterrolebinding/values.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/base/ceph-ssd/values.yaml
- rook/base/common/values.yaml
- rook/base/toolbox/kustomization.yaml
- rook/base/values.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
- topolvm/base/values.yaml
> rook/ceph, topolvm: add tolerations to prepare for applying l4lb

- argocd-config/base/moco.yaml
- monitoring/base/grafana-operator/mysql.yaml
- monitoring/overlays/gcp/kustomization.yaml
- neco-admission/base/webhook.yaml
- test/testdata/moco.yaml
> Update moco to v0.11.0 (Chart v0.2.0)

- test/setup_test.go
> Print the result of "get pod" when CI fails due to rook sync timeout.

- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/configmap.yaml
- rook/base/ceph-poc/configmap.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/configmap.yaml
- rook/overlays/gcp/ceph-object-store/debug.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
> rook: Change slow ops threshold

- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
> grafana: fix csa overview dashboard

- argocd-config/base/moco.yaml
> Update moco to v0.11.1 (Chart v0.2.1)

- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/configmap.yaml
- rook/base/ceph-poc/configmap.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/configmap.yaml
- rook/overlays/gcp/ceph-object-store/debug.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
- test/setup_test.go
[image_list.txt](https://31912-166922796-gh.circle-artifacts.com/0/~/test-results/image_list.txt)
> [CI] Stage stage-2022.03.16-31922

- team-management/base/maneki/project.yaml
- team-management/template/settings.json
This PR is for an internal request.
NECOREQ-37
> Add app-schreiben NS to destinations in maneki AppProject

- namespaces/base/teleport.yaml
- team-management/template/teleport/base/nodes/kustomization.libsonnet
- team-management/template/teleport/base/nodes/team.libsonnet
- teleport/base/nodes/csa.yaml
- teleport/base/nodes/cydec.yaml
- teleport/base/nodes/dbre.yaml
- teleport/base/nodes/ept.yaml
- teleport/base/nodes/garoon.yaml
- teleport/base/nodes/izumo.yaml
- teleport/base/nodes/kintone-neco.yaml
- teleport/base/nodes/kustomization.yaml
- teleport/base/nodes/landsat.yaml
- teleport/base/nodes/maneki.yaml
- teleport/base/nodes/neco-guests.yaml
- teleport/base/nodes/neco.yaml
- teleport/base/nodes/network.yaml
- teleport/base/nodes/set.yaml
> Mount Neco operation CLI commands on Teleport nodes

- test/moco_test.go
- test/testdata/moco.yaml
> Create MySQLCluster for test in restricted namespace

- monitoring/base/grafana-operator/datasources/csa-loki.yaml
- monitoring/base/grafana-operator/kustomization.yaml
> monitoring: add csa-loki datasource

- .circleci/config.yml
> Upgrade VM for dctest

- rook/base/ceph-object-store-clusterrolebinding/values.yaml
- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/values.yaml
- rook/base/ceph-poc-clusterrolebinding/values.yaml
- rook/base/ceph-poc/values.yaml
- rook/base/ceph-ssd-clusterrolebinding/values.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/values.yaml
- rook/base/common/values.yaml
- rook/base/values.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
issue: cybozu/csa#21
I replaced the CSI sidecars with self-built containers created by the following PR.
https://github.com/cybozu/neco-containers/pull/765
https://github.com/cybozu/neco-containers/pull/766
> rook: replace csi-related containers with self-built ones.

- argocd-config/base/accurate.yaml
- argocd-config/base/cattage.yaml
- argocd-config/base/moco.yaml
- argocd-config/base/prometheus-adapter.yaml
- argocd-config/base/tenet.yaml
- argocd-config/base/topolvm.yaml
- argocd/base/configmap.yaml
Reverts cybozu-go/neco-apps#2381
> Revert "Add system level ignoreDifferences for Certificate"

- meows/overlays/gcp/deployment.yaml
- meows/overlays/gcp/kustomization.yaml
- meows/overlays/gcp/upstream/agent/kustomization.yaml
- meows/overlays/gcp/upstream/controller/kustomization.yaml
- meows/overlays/stage0/runnerpool.yaml
> Update meows to 0.6.2

- monitoring/base/victoriametrics/rules/argocd-alertrule.yaml
- test/vmalert_test/argocd.yaml
> alert: cancel out-of-sync alert for csa namespaced applications

- monitoring/overlays/stage0/victoriametrics/vmcluster-largeset.yaml
> expand vmcluster-largeset PV size

- argocd-config/overlays/stage0/tenants/garoon-apps.yaml
- team-management/template/settings.json
Garoon team requests us to change their branch for staging cluster.
> Use staging branch to sync garoon-apps

- monitoring/base/cadvisor/daemonset.yaml
This reverts commit 5b5160dc8a01f56a6256b471deec4d80a1f0f6e5.
> Revert "Extend cAdvisor metrics"

- argocd/base/configmap.yaml
> Add health check script for Tenant resources

- argocd-config/overlays/osaka0/tenants/garoon-apps.yaml
- argocd-config/overlays/tokyo0/tenants/garoon-apps.yaml
- team-management/template/settings.json
./add_app_dest.sh garoon-apps tokyo0 production
./add_app_dest.sh garoon-apps osaka0 production
make all
> Update source revision of garoon-apps Application

- monitoring/base/victoriametrics/rules/monitoring-scrape.yaml
> add note for grafana-operator's metrics

- neco-admission/base/deployment.yaml
- neco-admission/overlays/gcp/deployment.yaml
> Allow ghcr.io/topolvm images

- logging/base/promtail/config/promtail.yaml
- monitoring/base/victoriametrics/rules/logging-scrape.yaml
- test/logging_test.go
- test/validation_test.go
> Expose rgw latency metrics

- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/cluster.yaml
- rook/base/ceph-poc/cluster.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
> Rook/Ceph apply a pached ceph image (v16.2.7.1)

- pvc-autoresizer/base/kustomization.yaml
> pvc-autoresizer: bump version to 0.3.6

- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
> add rgw response time graph to csa dashboard

- neco-admission/base/deployment.yaml
- neco-admission/overlays/gcp/deployment.yaml
> remove admission for csi sidecars.

- argocd-config/base/cattage.yaml
> Update cattage to v0.1.2 (chart v0.1.4)

- logging-small/base/loki.yaml
- logging-small/base/loki/pvc.yaml
> logging-small: fix threashold of pvc-autoresizer to avoid extra warning

- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/cluster.yaml
- rook/base/ceph-poc/cluster.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
> rook/ceph: apply a patch to ceph

- Makefile
- docs/maintenance.md
- logging-small/base/loki.yaml
- logging-small/base/loki/kustomization.yaml
- logging-small/base/promtail.yaml
- logging-small/base/promtail/kustomization.yaml
- logging-small/base/promtail/values.yaml
- logging/base/promtail/promtail.yaml
- logging/base/promtail/upstream/kustomization.yaml
- logging/base/promtail/upstream/values.yaml
> collect logs from ceph by promtail-small

- argocd-config/base/logging-small.yaml
- docs/maintenance.md
- logging-small/base/promtail.yaml
- logging-small/base/promtail/values.yaml
this PR edit manifests without updating promtail.
> logging-small: set maxUnavailable to logging-small's promtail

- meows/overlays/gcp/deployment.yaml
- meows/overlays/gcp/kustomization.yaml
- meows/overlays/gcp/upstream/agent/kustomization.yaml
- meows/overlays/gcp/upstream/controller/kustomization.yaml
- meows/overlays/gcp/upstream/crd/bases/meows.cybozu.com_runnerpools.yaml
- meows/overlays/stage0/runnerpool.yaml
> Update meows to v0.7.0

- Makefile
- grafana-sandbox/overlays/common/grafana.yaml
- monitoring/base/grafana-operator/deployment.yaml
- monitoring/base/kustomization.yaml
> Update grafana and grafana operator

- team-management/base/maneki/project.yaml
- team-management/template/settings.json
> Allow maneki team to deploy on app-metropolis (sub-)Namespace

- logging-small/base/loki/pvc.yaml
> logging-small: resize loki-small-data pvc

- rook/base/ceph-poc/configmap.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
> enable debug log for rgw in ceph-poc ns

- argocd-config/base/logging-small.yaml
> delete group option from ignoreDifferences

- logging-small/base/loki.yaml
> resize logging-small pvc to 20GiB

- cert-manager/overlays/stage0/kustomization.yaml
- cert-manager/overlays/stage0/letsencrypt-clusterissuer.yaml
> Add ClusterIssuer for Let's Encrypt

- argocd/base/configmap.yaml
> Add health check script for HTTPProxy

- Makefile
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/ceph-extra-exporter-scrape.yaml
- rook/base/ceph-extra-exporter/deployment.yaml
- rook/base/ceph-extra-exporter/kustomization.yaml
- rook/base/ceph-extra-exporter/service.yaml
- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/kustomization.yaml
- rook/base/ceph-poc/kustomization.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/kustomization.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
- test/storage_test.go
> ceph: deploy ceph-extra-exporter

- rook/base/ceph-object-store.yaml
- rook/base/ceph-object-store/cluster.yaml
- rook/base/ceph-poc/cluster.yaml
- rook/base/ceph-ssd.yaml
- rook/base/ceph-ssd/cluster.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
> rook/ceph: update ceph version to 16.2.7.3

- team-management/template/teleport/overlays/gcp/kustomization.libsonnet
- teleport/base/apps/kustomization.yaml
- teleport/base/apps/vmalertmanager-app-dbre-monitoring.yaml
- teleport/overlays/gcp/apps/vmalertmanager-app-dbre-monitoring.yaml
- teleport/overlays/gcp/kustomization.yaml
> Change target namespace of teleport app

- hubble/base/hubble-observer.yaml
> Collect DROPPED and ERROR verdict flow logs

- monitoring/base/victoriametrics/rules/ceph-extra-exporter-scrape.yaml
- test/validation_test.go
> set smallset label to ceph-extra-exporter scrape

- team-management/template/teleport/base/nodes/kustomization.libsonnet
- teleport/base/nodes/kustomization.yaml
> update teleport-node image for ubuntu security update

- monitoring/base/victoriametrics/rules/node-alertrule.yaml
- test/vmalert_test/node.yaml
> add NodeNetworkDown alert

- team-management/template/teleport/overlays/gcp/kustomization.libsonnet
- teleport/base/apps/kustomization.yaml
- teleport/base/apps/vmalert-largeset.yaml
- teleport/base/apps/vmalert-smallset.yaml
- teleport/overlays/gcp/apps/vmalert-largeset.yaml
- teleport/overlays/gcp/apps/vmalert-smallset.yaml
- teleport/overlays/gcp/kustomization.yaml
It may be useful to see vmalert (not vmalertmanager) 's web UI.
> add vmalert teleport app

- ingress/base/contour/01-crds.yaml
- ingress/base/contour/02-job-certgen.yaml
- ingress/base/contour/02-role-contour.yaml
- ingress/base/contour/03-contour.yaml
- ingress/base/contour/03-envoy.yaml
- ingress/base/kustomization.yaml
> Update contour to v1.20.1

- logging/base/loki/kustomization.yaml
- monitoring/base/ingress-health/deployment.yaml
- neco-admission/base/kustomization.yaml
- test/testdata/testhttpd/pod.yaml
- Update neco-admission to v0.16.1
- Update memcached to v1.6.15
- Update testhttpd
> Update neco-admission, memcached, testhttpd

- ingress/base/contour/01-crds.yaml
- ingress/base/contour/02-job-certgen.yaml
- ingress/base/contour/02-role-contour.yaml
- ingress/base/contour/03-contour.yaml
- ingress/base/contour/03-envoy.yaml
- ingress/base/kustomization.yaml
Reverts cybozu-go/neco-apps#2547
> Revert "Update contour to v1.20.1"

- hubble/base/upstream/hubble.yaml
- hubble/base/values.yaml
> Downgrade hubble-ui to v0.8.5

- rook/overlays/stage0/kustomization.yaml
> rook/ceph: update ceph version to 16.2.7.4

- .circleci/config.yml
> Copy PAT for reboot test

- monitoring/base/victoriametrics/rules/node-alertrule.yaml
- test/vmalert_test/node.yaml
> monitoring: monitor certain systemd units on boot servers

- meows/overlays/stage0/runnerpool.yaml
> Add user and token for cloning neco-apps in dctest-runner

- team-management/base/maneki/project.yaml
- team-management/template/settings.json
> Add app-minefield and app-themis namespaces

- meows/overlays/stage0/runnerpool.yaml
> Update meows-dctest-runner version.

- argocd-config/overlays/stage0/namespaces.yaml
issue: cybozu/csa#110
Co-authored-by: Daichi Mukai <daichi-mukai@cybozu.co.jp>
> namespaces: fix to set path to stage0 overlay namespaces application.

- argocd-config/overlays/stage0/network-policy.yaml
- network-policy/base/kustomization.yaml
- network-policy/base/policies/ceph.yaml
- network-policy/base/policies/logging-small.yaml
- network-policy/base/policies/pvc-autoresizer.yaml
- network-policy/base/policies/topolvm.yaml
- network-policy/overlays/stage0/ceph.yaml
- network-policy/overlays/stage0/kustomization.yaml
> allow networkpolicy in csa services

- test/tenant_networkpolicy_test.go
> test: wait for Accurate to create Namespace

- rook/base/ceph-poc/cephobjectstore.yaml
- rook/overlays/stage0/ceph-poc/ceph-poc.yaml
Co-authored-by: Toshikuni Fukaya <toshikuni-fukaya@cybozu.co.jp>
Co-authored-by: Yuji Ito <llamerada.jp@gmail.com>
> rook/ceph: ceph-poc: schedule rgw on nodes for benchmark

- test/Makefile
> do not use nilerr

- Makefile
- customer-egress/base/kustomization.yaml
- customer-egress/base/neco/squid.yaml
- customer-egress/base/squid.yaml
- monitoring/base/victoriametrics/kustomization.yaml
- monitoring/base/victoriametrics/rules/node-dns-scrape.yaml
- monitoring/base/victoriametrics/rules/unbound-scrape.yaml
- network-policy/base/policies/monitoring.yaml
part of https://github.com/cybozu-go/neco/issues/1975
> add unbound_exporter and its scraping configurations

- monitoring/base/grafana-operator/dashboards/csa-overview.yaml
> [monitoring] add a panel to show RGW request counts

- grafana-sandbox/overlays/common/grafana.yaml
- monitoring/base/grafana-operator/deployment.yaml
> update grafana to 8.5.4

- team-management/base/maneki/project.yaml
- team-management/template/settings.json
> Allow maneki team to deploy to app-elasticsearch-monitoring ns

- test/Makefile
> test: Fix to stop upgrade test when bootstrap fails
