metallb/base/deployment.yaml
MetalLB requires NET_RAW only when it is run in L2 mode.
In Neco, it is run in BGP mode hence does not require NET_RAW.
=> [metallb] do not require NET_RAW capability

external-dns/base/deployment.yaml, external-dns/overlays/gcp/deployment.yaml, external-dns/test/external-dns.go
Fix:
- `domain-filter` for GCP
- Removed `namespace` to adjust `contour-plus` specifications.
Use defaults:
- `crd-source-apiversion`
- `crd-source-kind`
- `policy`
=> [external-dns] update flags

test/network-policy_test.go
In this pull request, the following changes were made.
- add egress network policy tests.
- add missing ingress network policy test
- add `ingressroute` resource in the test to run tests properly
=> [network-policy] add egress network policy tests

bin/run-test.sh, network-policy/base/kustomization.yaml, network-policy/base/validation/network-policy.rego, network-policy/base/validation/network-policy_test.rego, test/Makefile, test/contour_test.go, test/metallb_test.go, test/network-policy_test.go
In this pull request, the following changes were made.
- add rego rules to prevent from creating or updating network policy resources with less than or equal to 1000 order defined by calico in some namespaces 
- add Open Policy Agent test cases
=> [network-policy] add Rego rules to validate NetworkPolicy.

test/Makefile, test/kustomize-fix.sh
As `kustomize edit fix` command migrates a kustomization file working with previous versions to one working with 2.0.0.
See the link below.
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v2.0.0.md#compatible-changes-new-features
Unfortunately, the command automatically edits the original kustomization file and applys without any warning and such behavior is not appropriate in CI test.
Therefore, in this pull request, the following changes were made.
- run `kustomize edit fix` command to all kustomization.yaml files to work with 2.0.0
- delete `kustomize edit fix` script to prevent from working in CI test
=> [kustomize] kustomize edit fix

teleport/base/validation/rolebinding-policy.rego, teleport/base/validation/rolebinding-policy_test.rego
Argocd creates `rolebinding` resource with `clusterrole`, but currently we allow the operation for only `system:masters`.
To fix this, this pull request made the following changes
- fix `rolebinding` rule and permit argocd controller to create such resources
- add test
=> [teleport] fix rolebinding policy

monitoring/base/grafana/dashboards/etcd.json, monitoring/base/grafana/statefulset.yaml, monitoring/base/prometheus/alert_rules.yaml, monitoring/base/prometheus/prometheus.yaml, monitoring/base/prometheus/test_rules.yaml, monitoring/overlays/stage0/grafana/statefulset.yaml, monitoring/overlays/stage0/kustomization.yaml, monitoring/overlays/stage0/prometheus/statefulset.yaml, network-policy/base/policies/monitoring.yaml, test/monitoring_test.go
- Allow prometheus access to cke-etcd's metrics
- Allow prometheus access to felix's metrics
- Fix node-exporter-full.json for provisioning Grafana
- Request 10Gi PV for Grafana and Prometheus on staging environment
- Relaxed etcd alert rules threshold
- Added alert rule using `up` metrics
- Enable to switch etcd cluster on the dashboard
=> Fix monitoring stack

.circleci/config.yml, docs/cicd.md
Enable bootstrap test with the `neco`'s feature branch.
When the branch has a specific prefix(`with-neco-branch-`), it's tested with neco feature branch which extracted from neco-apps's branch name.
Example:
When `with-neco-branch-foo-bar` branch of `neco-apps` has pushed, it's tested with `foo-bar` branch of `neco`.
=> Test with neco's feature branch

monitoring/base/grafana/dashboards/calico.json, monitoring/base/prometheus/prometheus.yaml, monitoring/overlays/stage0/prometheus/statefulset.yaml
- Allow Prometheus to scrape Contour's metrics.
- Fix default time range of Calico dashboard.
- Disable excessive labelmap.
- [stage0] Resize the storage of Prometheus 10Gi to 150Gi
=> [grafana][prometheus] Fix monitoring settings

go.mod, test/network-policy_test.go, vendor/golang.org/x/sync/AUTHORS, vendor/golang.org/x/sync/CONTRIBUTORS, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go, vendor/modules.txt
Gomega's matcher cannnot be used in goroutine, so fix test codes using errgroup.
=> Fix goroutine using errgroup

ingress/base/contour/deployment.yaml, monitoring/base/prometheus/alert_rules.yaml, monitoring/base/prometheus/prometheus.yaml, monitoring/base/prometheus/test_rules.yaml
- Use rate() for etcd_mvcc_db_total_size_in_use_in_bytes as grafana
recommended:
"Time series is monotonically increasing. Try applying a rate()
function."
- Enable an alert rule for exporter up status.
- Enable envoy metrics.
=> [monitoring] Update alert rules

monitoring/base/prometheus/alert_rules.yaml, monitoring/base/prometheus/test_rules.yaml
rate() expects counter but etcd_mvcc_db_total_size_in_use_in_bytes[1h]
is gauge. And the value is possibly decreased by compaction.
=> [monitoring] Revert alert rule of LogicalDatabaseUsageIncreaseRapidly

network-policy/base/policies/internet-egress.yaml, topolvm/base/namespace.yaml
This pull request made the following changes.
-  remove `k8s-app` label condition from network policy because such labels are already removed and from deployments.
- remove `name: topolvm-system` label from `topolvm-system` namespace as `topolvm` is no longer use `name` label for `namespaceSelector` in its `MutatingWebhookConfiguration` resource.
=> remove unnecessary lables

monitoring/base/alertmanager/deployment.yaml, monitoring/base/alertmanager/neco.template, monitoring/base/prometheus/prometheus.yaml, monitoring/base/prometheus/statefulset.yaml
- https://github.com/cybozu-go/neco/issues/527 Use `.Annotations` instead of `.CommonAnnotations` for cases without summary annotation 
- Enable to scrape prometheus and alertmanager pods 
- Rename machines-endpoints targets to node-exporter targets
=> [monitoring] Enable to scrape Prometheus and Alertmanager

teleport/base/statefulset.yaml
Fix https://github.com/cybozu-go/neco/issues/542
=> teleport: mount emptyDir on /tmp for teleport-auth

monitoring/base/prometheus/prometheus.yaml
Fix the missing configuration of Prometheus for scraping kube-state-metrics's own metrics.
- The port is configured by [`--telemetry-port`](https://github.com/cybozu/neco-containers/blob/master/kube-state-metrics/Dockerfile#L22).
- The port is already specified in [kube-state-metrics](https://github.com/cybozu-go/neco-apps/blob/master/monitoring/base/kube-state-metrics/service.yaml#L16-L18) service.
=> [monitoring] scrape kube-state-metrics's own metrics

monitoring/overlays/osaka0/prometheus/statefulset.yaml, monitoring/overlays/stage0/prometheus/statefulset.yaml, monitoring/overlays/tokyo0/prometheus/statefulset.yaml
According to "Prometheus Up and Running",
8GB of RAM is a good starting point for the environment having 100,000 ingests per second,
and more +1 core should be prepared for Prometheus to compute recording rules and queries.
=> [monitoring] allocate 8GB RAM and 2 CPU cores to Prometheus container

argocd-config/overlays/osaka0/argocd.yaml, argocd-config/overlays/osaka0/kustomization.yaml, argocd-config/overlays/tokyo0/argocd.yaml, argocd-config/overlays/tokyo0/kustomization.yaml, argocd/base/service.yaml, argocd/overlays/osaka0/ingressroute.yaml, argocd/overlays/osaka0/kustomization.yaml, argocd/overlays/stage0/ingressroute.yaml, argocd/overlays/stage0/kustomization.yaml, argocd/overlays/tokyo0/ingressroute.yaml, argocd/overlays/tokyo0/kustomization.yaml
refs: https://github.com/cybozu-go/neco/issues/585
- Change the service type of argocd-server to LoadBalancer type
- Register a subdomain for argocd-server with Google Cloud DNS by creating an IngressRoute resource.
=> Change the service type of argocd-server

test/.gitignore, test/argocd-server_test.go, test/run_test.go, test/run_test_kind.go, test/setup_test.go, test/suite_test.go
- Initialized Argo CD password is the pod name when it is created at the first time. It should be used other login tests.
=> test: Fix argocd-server Pod name as password for upgrade test

docs/manifests.md, monitoring/base/prometheus/alert_rules.yaml, monitoring/base/prometheus/kube_prometheus_alert_rules.yaml, monitoring/base/prometheus/prometheus.yaml, monitoring/base/prometheus/test_rules.yaml
In this PR https://github.com/cybozu-go/neco-apps/pull/161, some
alert rules are moved to `kube_prometheus_alert_rules.yaml`, This change
drops other alert rules which evaluate `absent(up{job="xx"} == 1)`.
This PR adds missing alert rules when exporters are down.
Also fixes instance label dropped port number.
=> monitroing: Fix wrong labels and missing alerts

namespaces/base/internet-egress.yaml, namespaces/base/kustomization.yaml
internet-egress namespace is used for Squid and Unbound
to connect to the Internet.  To apply network policy w/o
restriction enforced by neco-admission, the namespace
need to have label "control-plane: true".
=> Add internet-egress namespace

test/setup_test.go
Other applications should successfully be synchronized at the first try.
=> test: do not retry app sync for applications other than cert-manager

monitoring/base/prometheus/alert_rules/kubernetes.yaml, test/alert_test/kubernetes.yaml
Stop alerting if it comes from tenants' namespaces at PromQL layer.
The reason why we prepare this setting at PromQL:  
tenants want to use data in Neco's Prometheus so we should collect metrics from tenants' namespace
=> prometheus: stop alerting if its namespace is for tenants

cert-manager/base/deployment.yaml, cert-manager/base/kustomization.yaml, cert-manager/base/rbac.yaml, cert-manager/base/upstream/cert-manager_nsremoved.yaml, docs/maintenance.md
This pull request made the following changes.
- Remove namespace resource as it is managed in a different directory
- Update cert-manager to v0.11.1
- Fix maintenance doc.
=> [cert-manager] Update cert-manager to 0.11.1

namespaces/base/kustomization.yaml, test/setup_test.go
As cert-manager namespace accidentally managed by cert-manager Application, CI test always fails now.
To fix the problem above, this pull request made the following changes.
- manage cert-manager namespace by namespaces Application
- fix test
=> Fix sync process for cert-manager.

.circleci/config.yml
CircleCI timeouts before `Eventually` timeouts, because `no_output_timeout` is not set in kindtest.
=> circleci: set no_output_timeout to kindtest

test/cert-manager_test.go, test/contour_test.go
When CertificateRequest fails, `cert-manager` does not retry in 1h.
See [this](https://github.com/jetstack/cert-manager/blob/v0.11.1/pkg/controller/certificates/sync.go#L410-L440)
However, it is too long for our tests and `neco-apps` CIs sometimes fail.
To fix this, this pull request made the following changes.
- recreate Certificate when its CertificateRequest fails
- delete Certificate when `contour-plus` failed to succeed its CertificateRequest.
=> Recreate Certificate if CertificateRequest fails

team-management/base/common/clusterrole.yaml
- Allow using `HTTPProxy` for Neco developers instead of `IngressRoute`.
=> team-management: Update ClusterRole to use HTTPProxy

argocd-config/overlays/stage0/bmc-reverse-proxy.yaml
Set targetRevision parameter for argocd-config to use the branch of `stage` on the stage environment.
=> Fix argocd-config to use branch of stage on stage environment.

monitoring/base/prometheus/statefulset.yaml
This `failureThreshold=30` is unnecessary because Prometheus during initializing should be set `NotReady` quickly.
=> prometheus: remove unnecessary long failureThreshold

bmc-reverse-proxy/overlays/kind/bmc-reverse-proxy/deployment.yaml
Remove `volumes` and `volumeMounts` fields from dummy deployment as follows:
```
$ diff -u15 kind-deploy-before.yaml kind-deploy-after.yaml 
--- kind-deploy-before.yaml     2019-12-18 09:12:41.860136271 +0000
+++ kind-deploy-after.yaml      2019-12-18 09:18:06.144451405 +0000
@@ -145,39 +145,31 @@
template:
metadata:
labels:
app.kubernetes.io/name: bmc-reverse-proxy
spec:
containers:
- image: quay.io/cybozu/testhttpd:0
name: bmc-reverse-proxy
ports:
- containerPort: 8443
name: web
protocol: TCP
- containerPort: 5900
name: virtual-console
protocol: TCP
-        volumeMounts:
-        - mountPath: /etc/bmc-reverse-proxy
-          name: secret-fs
-          readOnly: true
serviceAccountName: bmc-reverse-proxy
-      volumes:
-      - name: secret-fs
-        secret:
-          secretName: …
```
=> bmc-reverse-proxy: remove volumes in kindtest

ingress/base/template/deployment.yaml
Check all "image:" and "imagePullPolicy" in the staging environment, and fix inappropriate ones.
```
for r in deployment daemonset statefulset; do kubectl get $r -A -o yaml | grep image: ; done
for r in deployment daemonset statefulset; do kubectl get $r -A -o yaml | grep imagePullPolicy: ; done
```
=> ingress: fix imagePullPolicy of envoy's init container.

test/suite_test.go
Pulling a container image sometimes gets stuck in the reboot test.
This seems to be a temporary problem caused by the instability of the HTTP proxy.
It takes ~16 minutes to be solved due to `net.ipv4.tcp_retries2` in Linux, so this PR extends the default timeout of `Eventually()` to 30 minutes.
=> test: extend Eventually() timeout mainly for reboot test.

monitoring/base/prometheus/prometheus.yaml, test/monitoring_test.go
1. Fix Prometheus configuration:
- Fix scheduler/controller-manager target.
- Rename ingress target to contour-envoy target.
- Remove envoy target since it is not used.
1. Fix test to make sure all targets are `up`.
=> prometheus: fix target configuration

monitoring/base/prometheus/README.md, monitoring/base/prometheus/alert_rules/argocd.yaml, monitoring/base/prometheus/alert_rules/cert-manager.yaml, monitoring/base/prometheus/alert_rules/elastic-operator.yaml, monitoring/base/prometheus/alert_rules/etcd.yaml, monitoring/base/prometheus/alert_rules/external-dns.yaml, monitoring/base/prometheus/alert_rules/ingress.yaml, monitoring/base/prometheus/alert_rules/kube-state-metrics.yaml, monitoring/base/prometheus/alert_rules/kubernetes.yaml, monitoring/base/prometheus/alert_rules/metallb.yaml, monitoring/base/prometheus/alert_rules/monitoring.yaml, monitoring/base/prometheus/alert_rules/network-policy.yaml, monitoring/base/prometheus/alert_rules/node.yaml, monitoring/base/prometheus/alert_rules/topolvm.yaml, test/alert_test/argocd.yaml, test/alert_test/etcd.yaml, test/alert_test/external-dns.yaml, test/alert_test/kubernetes.yaml, test/alert_test/metallb.yaml, test/alert_test/monitoring.yaml, test/alert_test/network-policy.yaml, test/alert_test/node.yaml
Add alert rules for applications on Kubernetes.
The generic rules are already exists in neco-apps, so this PR introduces application specific alert rules.
In addition, set the policy for the `severity` label.
---
- Alert if registry has any errors
- Alert if dns endpoints have any errors
- Alert if the status of Certificate is not Ready
- Alert if the count of invalid httpproxy resources is increasing
- Alert if any BGP sessions are down
- Alert if configurations are stale
- Alert if the address pool will be exhausted
- Alert if the time to apply data plane become slowly
- Alert if the count of errors in data plane is increasing
- Alert if the count of conntrack entries will be exhausted
- Alert if the disk size in the whole of cluster will be exhausted
=> [monitoring] Add alert rules for the applications.

local-pv-provisioner/base/daemonset.yaml, monitoring/base/grafana/configmap.yaml, monitoring/base/grafana/dashboards/local-pv-provisioner.json, monitoring/base/grafana/statefulset.yaml, monitoring/base/kustomization.yaml, monitoring/base/prometheus/prometheus.yaml, test/monitoring_test.go
Add a dashboard for local-pv-provisioner for watching the following metrics.
- `local_pv_provisioner_available_devices`
- `local_pv_provisioner_error_devices`
https://github.com/cybozu/neco-containers/tree/master/local-pv-provisioner#prometheus-metrics
=> Add metrics settings of local-pv-provisioner

monitoring/base/grafana/service.yaml, monitoring/overlays/gcp/grafana/service.yaml, monitoring/overlays/gcp/kustomization.yaml, monitoring/overlays/kind/grafana/service.yaml, monitoring/overlays/kind/kustomization.yaml
The Grafana is now published using `HTTPProxy`.
So, `grafana` svc need not be `type LoadBalancer` in stage and production environments.
But in gcp and kind, it should still be `type LoadBalancer` for debugging.
=> monitoring: Fix the type of grafana svc

.circleci/config.yml, docs/cicd.md
`op-stage-*` and `op-release-*` branches are created by `create-pull-request` jobs.
Always they passed `manual-dctest` and `kindtest`, so they can skip `kindtest` in `main` workflow.
=> circleci: skip kindtest if op-* branch

team-management/base/maneki/app-misc.yaml, team-management/base/sandbox/sandbox.yaml
Remove default `resources.limit` because it is annoyed when expanding `resources.request`.
If the default settings are deleted, the max limit is used.
=> team-management: remove default limits for sandbox and app-misc

test/Makefile.dctest
=> test: use "cp" instead of "ln -s" in preparation for overwriting.

test/Makefile.kindtest, test/setup_test.go, topolvm/base/upstream/controller.yaml, topolvm/base/upstream/node.yaml, topolvm/base/upstream/scheduler.yaml
- Upgrade topolvm to 0.3.0.
- Use force sync because `CSIDriver` cannot be patched.
- Remove some obsoleted setup code.
=> topolvm: upgrade to 0.3.0

ingress/base/template/deployment.yaml
- Update envoy to v1.12.3 as the vulnerability response.
ref: https://www.envoyproxy.io/docs/envoy/v1.12.3/intro/version_history
=> ingress: update envoy to v1.12.3

test/setup_test.go
`argocd app sync argocd-config --local argocd-config/overlays/gcp` takes a lot of time as `app sync` blocks until the sync process is complete.
Therefore, executing the command above with `ExecSafeAt()` function often causes  timeout error like [this](https://circleci.com/gh/cybozu-go/neco-apps/8401).
To avoid this problem,  add `async` flag for the command to return as soon as the sync request was received by the API server.
Application statuses eventually become healthy [here](https://github.com/cybozu-go/neco-apps/blob/master/test/setup_test.go#L308-L351), so this change will not have side effects.
=> Add async flag

monitoring/base/prometheus/prometheus.yaml, network-policy/base/calico/deployment.yaml
This PR adds scraping config for calico typha.
Alert rules for typha are going to be written in another task.
=> monitoring: Add scraping rule for Calico typha.

local-pv-provisioner/base/podsecuritypolicy.yaml
=> local-pv-provisioner: allow emptyDir in PSP.

monitoring/base/prometheus/prometheus.yaml
Do not remove the port number from node-exporter job's instance label
because node-exporter-full dashboard expects to be in the form of `ip:port`.
=> prometheus: do not remove the port number from node-exporter job's instance label

test/setup_test.go
=> test: create empty ConfigMap for bmc-reverse-proxy bootup.

.circleci/config.yml, docs/cicd.md
Because there are no environments running at master branch.
=> CI: remove upgrade-master job

monitoring/base/grafana-operator/grafana.yaml
This PR fixes `disable_signout_menu` unexpectedly introduced in
https://github.com/cybozu-go/neco-apps/pull/510
=> monitoring: fix to allow signout from GUI

monitoring/base/prometheus/alert_rules/argocd.yaml, test/alert_test/argocd.yaml
Follow metrics name change in Argo CD 1.5 and add monitoring alert AllAppMissing
=> monitoring: fix metrics name for Argo CD >= 1.5.0.

argocd-ingress/overlays/gcp/certificate.yaml, argocd-ingress/overlays/kind/certificate.yaml, argocd-ingress/overlays/osaka0/certificate.yaml, argocd-ingress/overlays/stage0/certificate.yaml, argocd-ingress/overlays/tokyo0/certificate.yaml, bmc-reverse-proxy/overlays/gcp/bmc-reverse-proxy/certificate.yaml, bmc-reverse-proxy/overlays/osaka0/bmc-reverse-proxy/certificate.yaml, bmc-reverse-proxy/overlays/stage0/bmc-reverse-proxy/certificate.yaml, bmc-reverse-proxy/overlays/tokyo0/bmc-reverse-proxy/certificate.yaml, ingress/base/template/certificate.yaml, ingress/base/template/deployment.yaml, neco-admission/base/certificates.yaml, teleport/overlays/gcp/certificate.yaml, teleport/overlays/osaka0/certificate.yaml, teleport/overlays/stage0/certificate.yaml, teleport/overlays/tokyo0/certificate.yaml, test/cert-manager_test.go, test/validation_test.go, topolvm/base/upstream/certificates.yaml, topolvm/base/upstream/controller.yaml, topolvm/base/upstream/node.yaml, topolvm/base/upstream/scheduler.yaml
This PR specifies certificates' extended key usages explicitly.
- updates manifests managed in neco-apps
- updates TopoLVM to reflect manifests managed in upstream
This PR also updates contour-plus to 0.4.3 to generate certificates with explicit usages.
=> Specify certificate's extended key usage explicitly

monitoring/base/prometheus/statefulset.yaml
The Prometheus Volume was resized to 460Gi through our operation. 
Therefore, this PR fixes the volume size of the Prometheus manifest.
=> Resize the Prometheus volume

argocd/base/configmap.yaml, team-management/base/neco/project.yaml
This PR adds permission to read other applications to Neco team using embed role such as `role:admin`, `role:readonly`.
=> Add read other applications permission to Neco

ingress/base/bastion/httpproxy.yaml, ingress/base/bastion/kustomization.yaml, ingress/base/forest/httpproxy.yaml, ingress/base/forest/kustomization.yaml, ingress/base/global/httpproxy.yaml, ingress/base/global/kustomization.yaml, ingress/base/template/httpproxy.yaml, ingress/base/template/kustomization.yaml
This PR is to prevent envoy crush loop.
See: https://github.com/cybozu-go/neco/issues/1002
=> ingress: add dummy HTTPProxies

bmc-reverse-proxy/overlays/osaka0/kustomization.yaml
bmc-reverse-proxy was not deployed on osaka0 due to the incorrect kustomize manifests.
Fix this problem.
=> bmc-reverse-proxy: fix osaka0 overlay

monitoring/base/alertmanager/deployment.yaml, monitoring/base/kustomization.yaml, monitoring/base/prometheus/prometheus.yaml, monitoring/base/prometheus/statefulset.yaml, monitoring/base/pushgateway/deployment.yaml, monitoring/base/pushgateway/service.yaml, monitoring/overlays/osaka0/kustomization.yaml, monitoring/overlays/osaka0/pushgateway/httpproxy.yaml, monitoring/overlays/stage0/kustomization.yaml, monitoring/overlays/stage0/pushgateway/httpproxy.yaml, monitoring/overlays/tokyo0/kustomization.yaml, monitoring/overlays/tokyo0/pushgateway/httpproxy.yaml, test/monitoring_test.go, test/suite_test.go
- Add manifests of Pushgateway
- Deployment/Service/HTTPProxy
- Configure Prometheus to scrape Pushgateway
- Add test to confirm that Pushgateway is accessible from each network
- Refactor to manage image versions by imageTags
=> pushgateway: add manifests and tests for pushgateway

monitoring/base/ingress-health/deployment.yaml, monitoring/base/ingress-health/service.yaml, monitoring/base/kustomization.yaml, monitoring/overlays/osaka0/ingress-health/httpproxy.yaml, monitoring/overlays/osaka0/kustomization.yaml, monitoring/overlays/stage0/ingress-health/httpproxy.yaml, monitoring/overlays/stage0/kustomization.yaml, monitoring/overlays/tokyo0/ingress-health/httpproxy.yaml, monitoring/overlays/tokyo0/kustomization.yaml, test/monitoring_test.go, test/suite_test.go
Deploy testhttpd and expose the endpoint to global, forest and bastion with HTTPProxy.
=> monitoring: add httpproxy and services for ingress-watcher

network-policy/base/policies/bmc-reverse-proxy.yaml
=> network-policy: Add synv-wave for bmc-reverse-proxy network-policy

test/argocd-ingress_test.go
The test code overwrote the same resource created by Argo CD.
This results in flakiness because Argo CD tries to self-heal
the resource.
=> test: fix test for argocd-ingress

.circleci/config.yml, bin/run-test.sh, test/suite_test.go
To view the statistics of failed tests in each branch easily, this PR modified `neco-apps` test to generate junit-compatible test result.
With this change, you can see the statistics by following the steps below
1. Go to [this page](https://circleci.com/build-insights)
2. Click `cybozu-go/neco-apps`
3. Select `ci-metrics`branch from the pull down menu`Change branch`
4. You can see `Failed Tests` and `Slowest Failed Tests` at the bottom of the page 
=> ci: output junit-compatible test result

bmc-reverse-proxy/base/machines-endpoints/cronjob.yaml, monitoring/base/machines-endpoints/cronjob.yaml
Set startingDeadlineSeconds less than interval*100.
If it is too small, jobs cannot start. Use 30s for minutely jobs.
=> bmc-reverse-proxy, monitoring: add startingDeadlineSeconds to CronJobs

test/Makefile
to download teleport binaries reliably.
=> Add --retry-connrefused flag to wget

docs/maintenance.md, monitoring/base/prometheus/statefulset.yaml, sandbox/overlays/gcp/grafana/statefulset.yaml, teleport/base/statefulset.yaml, test/elastic_test.go, topolvm/base/kustomization.yaml, topolvm/base/upstream/base/controller.yaml, topolvm/base/upstream/base/node.yaml, topolvm/base/upstream/overlays/daemonset-scheduler/kustomization.yaml, topolvm/base/upstream/overlays/daemonset-scheduler/scheduler.yaml, topolvm/base/upstream/overlays/deployment-scheduler/kustomization.yaml, topolvm/base/upstream/overlays/deployment-scheduler/scheduler.yaml
- Upgrade TopoLVM to v0.5.2.
- Remove fsGroup for topolvm provisioned volume.
=> upgrade TopoLVM to v0.5.2

argocd-config/base/maneki-apps.yaml, argocd-config/base/network-policy.yaml, test/validation_test.go
This PR moves network-policy sync-wave in order to prevent the connection failure to the Kube API server.
=> Stabilize argocd sync

argocd-config/base/maneki-apps.yaml, argocd-config/base/rook.yaml, rook/overlays/gcp/ceph-ssd/cluster.yaml, rook/overlays/gcp/kustomization.yaml, teleport/base/statefulset.yaml, teleport/overlays/gcp/statefulset.yaml, test/setup_test.go, test/validation_test.go
- Change Teleport's storage to TopoLVM instead of RBD.
- Move Rook to last of syncWeve.
- Ignore Rook on eventually loop to wait for sync of ArgoCD.
- Move test for Rook to Ceph test job.
=> [Rook/Ceph] stabilize neco-apps CI

.circleci/config.yml, argocd-config/base/kustomization.yaml, argocd-config/overlays/gcp-rook/kustomization.yaml, argocd-config/overlays/gcp-rook/rook.yaml, argocd-config/overlays/gcp/kustomization.yaml, argocd-config/overlays/gcp/rook.yaml, argocd-config/overlays/osaka0/kustomization.yaml, argocd-config/overlays/osaka0/rook.yaml, argocd-config/overlays/stage0/kustomization.yaml, argocd-config/overlays/stage0/rook.yaml, argocd-config/overlays/tokyo0/kustomization.yaml, argocd-config/overlays/tokyo0/rook.yaml, bin/run-test.sh, test/setup_test.go, test/validation_test.go
- remove rook app from circle-ci on gcp
- create gcp-rook folder and apply it when CI of ceph
=> rook: remove rook app from gcp CI to stabilize CI

monitoring/base/prometheus/prometheus.yaml
prometheus.yaml have some `action: drop` relabel configs to drop some metrics. However, those configs does not work and the metrics have been already used. So, remove the useless configs.
=> remove useless prometheus relabel configs.

monitoring/base/prometheus/alert_rules/kubernetes.yaml, test/alert_test/kubernetes.yaml
This PR adds `KubeNodeUnschedulable` alert to monitor cordoned nodes.
=> reboot: alert if nodes are unschedulable

test/monitoring_test.go, test/setup_test.go
This PR cleans up some temporal code blocks which are added to emulate manual operations to be done only once for https://github.com/cybozu-go/neco-apps/pull/783.
=> Clean up code blocks which was added only for regular container update in 2020/09

test/Makefile, test/setup_test.go, test/teleport_test.go
Update of teleport from v4.1 to v4.2 caused a degradation that the URL of kube-apiserver is given like 0.0.0.0:3206.
This PR contains a new test case to prevent this behavior from occurring again.
=> Add teleport proxy test which confirms that teleport client can access kube-apiserver

bin/clean-dns.sh
CI fails on cleaning DNS and we need more detailed logs to investigate that.
=> test: Update clean dns to show commands in each step

coil/base/egress.yaml, customer-egress/base/egress.yaml
I investigated https://github.com/torvalds/linux/blob/bbe2ba04c5a92a49db8a42c850a5a2f6481e47eb/net/netfilter/ipvs/ip_vs_core.c
and found that the session affinity timeout for UDP is updated every time packets are sent or received.
This means that the source hashing option is not needed any more and we should just use `sessionAffinity` to keep long-lived sessions  alive.
=> coil: Enable sessionAffinity for egresses

monitoring/overlays/osaka0/mackerel-agent.yaml, monitoring/overlays/stage0/mackerel-agent.yaml, monitoring/overlays/tokyo0/mackerel-agent.yaml
`mackerel-agent` stores its host ID under `/var/lib/mackerel-agent` directory.
To keep the host ID between Pod recreation, the volume for the directory should be persistent.
=> mackerel-agent: store stateful data in Ceph RBD volume

monitoring/base/prometheus/alert_rules/kubernetes.yaml
The `KubePodCrashLooping` alert rule in neco-apps is too sensitive.
The upstream rule is fixed, backport it.
Please check the following rule.
https://github.com/prometheus-operator/kube-prometheus/blob/v0.6.0/manifests/prometheus-rules.yaml#L1031
=> monitoring: backport KubePodCrashLooping alert rule

docs/maintenance.md, neco-admission/base/kustomization.yaml, neco-admission/base/upstream/manifests.yaml, neco-admission/base/webhook.yaml
ValidatingWehbhookConfiguration for GrafanaDashboard is left unconfigured by mistake.
This PR adds the config to the manifest.
=> neco-admission: Use upstream

test/setup_test.go
This PR cleans the  temporal code introduced [here](https://github.com/cybozu-go/neco-apps/pull/883).
=> test: Cleanup temporary code.

monitoring/base/prometheus/alert_rules/cke.yaml, monitoring/base/prometheus/alert_rules/kubernetes.yaml, test/alert_test/cke.yaml, test/alert_test/kubernetes.yaml
This PR adds and fixes alert rules for `neco reboot-worker`.
- `CKEOperationTakesLongTime`
Reboot phase is removed from alert calculation.
- `CKESabakanIntegrationDoesNotPerformAnyOps`
It is silenced when reboot operation is ongoing.
- `CKERebootQueueStuck`
It is added to alert reboot queue being stuck for 60mins.
- `K8sAPIServersDegraded`
Extend from 10mins to 15mins.
- `KubeDaemonSetRolloutStuck`
Extend from 15mins to 30mins.
- `KubeNodeNotReady`
It is silenced when the node is rebooted.
- `KubeNodeUnschedulable`
Extend from 15mins to 60mins.
- `KubePodCrashLooping`
It is already treated in #891.
- `KubeDeploymentReplicasMismatch`
- `KubePodNotReady`
They are not treated in this PR.
=> monitoring: fix alert rules to use neco reboot-worker

docs/maintenance.md, monitoring/base/grafana-operator/upstream/cluster_roles/README.md, monitoring/base/grafana-operator/upstream/crds/Grafana.yaml, monitoring/base/kustomization.yaml
I confirmed that there is only the difference that I recognize should be according to the release note by executing `kustomize build .` before and after the update.
Ref https://github.com/cybozu/neco-containers/pull/475
=> grafana-operator: Upgrade to 3.7.0

ingress/base/bastion/contour-config.yaml, ingress/base/forest/contour-config.yaml, ingress/base/global/contour-config.yaml
Custom JSON fields for Envoy access logs is enabled since Contour v1.10.0.
By using this function, we can have many additional fields like `response_code_details`, `response_code_details, connection_time_details` in our Envoy access logs.
Therefore, in this PR, I added the following log fields in addition to the default fields.
- `response_code_details`
- `connection_time_details` 
- `request_duration` 
- `response_duration` 
- `upstream_transport_failure_reason`
=> customize envoy log fields

monitoring/base/grafana-operator/dashboards/coil.yaml
- Change the graph of `Unallocated Blocks` to `Allocated Blocks` and fix the background bar.
- Delete the graph of `Block Allocation Rate`.
=> monitoring: update coil dashboard

argocd/base/kustomization.yaml
After upgrading dex from v2.22.0 to v2.27.0, argocd login via cli does not work,
Therefore, this PR revert the dex upgrade.
=> Revert "argocd: Upgrade dex to v2.27.0"

cert-manager/overlays/stage0/clusterissuer.yaml, test/validation_test.go
This PR replaces the ClusterIssuer (name: clouddns) from Let's Encrypt to ZeroSSL.
To enable the ClusterIssuer, we need the operation creating Secret that includes EAB HMAC Key.
=> cert-manager: Use ZeroSSL for stage0.

monitoring/base/victoriametrics/rules/topolvm-alertrule.yaml
kube-state-metrics-alertrule.yaml and kubernetes-alertrule.yaml don't seems to have problems.
=> fix vmalert rule for TopoLVM

bmc-reverse-proxy/base/machines-endpoints/pod-security-policy.yaml, metallb/base/pod-security-policy.yaml, monitoring/base/machines-endpoints/pod-security-policy.yaml, team-management/base/common/elastic-rbac.yaml, topolvm/base/upstream/base/psp.yaml
Implements https://github.com/cybozu-go/neco/issues/1018
=> Use MayRunAs instead of MustRunAs to avoid recursive chown

cert-manager/overlays/stage0/clusterissuer.yaml
After this PR is merged and released, we should set auto-sync for `cert-manager` ArgoCD app.
=> cert-manager: Fix ZeroSSL EAB key.

sandbox/overlays/gcp/grafana/service.yaml, test/sandbox_test.go, test/setup_test.go, test/suite_test.go
Check the access to Sandbox Grafana via HTTPProxy as in stage0.
This test logic is same as the Grafana in monitoring ns.
https://github.com/cybozu-go/neco-apps/blob/c179828305a8b85a0e9ae27d1e3e75c719ff6fff/test/monitoring_test.go#L483-L563
=> Disable ExternalIP of sandbox grafana svc

test/teleport_test.go
The names of boot servers are now prefixed with "gcp0-".
=> Change boot server names for Ubuntu 20.04 dctest

monitoring/base/victoriametrics/alertmanager.yaml
Add PVC to vmalertmanager.
STS should be deleted manually after this PR is applied to stage/prod because STSs cannot be modified except  'replicas', 'template', and 'updateStrategy'.
=> add PVC to vmalertmanager

monitoring/base/victoriametrics/vmagent-smallset.yaml, monitoring/base/victoriametrics/vmalert-smallset.yaml, test/validation_test.go
To reduce load of API server, see only monitoring NS.
If namespace selector is omitted (nil), they see only the NS which they are in.
=> make vmagent/vmalert see CRs in monitoring NS only

coil/base/egress.yaml, customer-egress/base/egress.yaml
iptables fails to lock `/run/xtables.lock` on Ubuntu 20.04.
=> Fix egress nat to mount `/run`

monitoring/base/victoriametrics/rules/monitoring-scrape.yaml, test/validation_test.go
- use VMServiceScrape instead of VMPodScrape for vmagent/vmalert
- add `app.k8s.io/component` label
=> fix scraping CR for VM smallset

monitoring/base/victoriametrics/operator.yaml
- we don't use VMServiceScrape which is created by the operator for VMAgent, VMAlert etc.
- we never require Prometheus operator CR conversion
see also: https://github.com/VictoriaMetrics/operator/blob/v0.7.1/vars.MD
=> do not make VictoriaMetrics operator create self VMServiceScrape

customer-egress/base/namespace.yaml, namespaces/base/argocd.yaml, namespaces/base/bmc-reverse-proxy.yaml, namespaces/base/cert-manager.yaml, namespaces/base/domestic-egress.yaml, namespaces/base/elastic.yaml, namespaces/base/external-dns.yaml, namespaces/base/ingress.yaml, namespaces/base/internet-egress.yaml, namespaces/base/kube-system.yaml, namespaces/base/metallb.yaml, namespaces/base/monitoring.yaml, namespaces/base/rook-ceph.yaml, namespaces/base/teleport.yaml, namespaces/base/topolvm.yaml, neco-admission/base/deployment.yaml, neco-admission/base/kustomization.yaml, test/setup_test.go
This PR removes unnecessary webhook ignore labels.
Note that `vnetworkpolicy` rejects less than `admission.cybozu.com/min-policy-order` annotation value, not including "equal" value (default is `1000.0`).
See: https://github.com/cybozu/neco-containers/pull/497
=> Remove unnecessary webhook ignore labels

test/elastic_test.go
=> test: remove "cluster.local" domain suffix when accessing from nodes.

monitoring/base/prometheus/alert_rules/node.yaml, test/alert_test/node.yaml
`job="node-exporter"` metrics have port number in `instance` label (i.e. `instance="10.0.0.1:9100"`, not `instance="10.0.0.1"`), even on Prometheus.
=> fix NodeExporterDown alert on Prometheus

monitoring/base/kube-state-metrics/deployment.yaml
Starting with kube-state-metrics v2.0.0, labels metrics such as
`kube_namespace_labels` or `kube_node_labels` does not include
Kubernetes resource labels.
https://github.com/kubernetes/kube-state-metrics/issues/1270
Since we are using some Kubernetes labels, this commit restores them.
=> monitoring: add Kubernetes labels to node/namespace metrics

local-pv-provisioner/base/daemonset.yaml, monitoring/base/victoriametrics/kustomization.yaml, monitoring/base/victoriametrics/rules/coil-scrape.yaml, monitoring/base/victoriametrics/rules/external-dns-scrape.yaml, monitoring/base/victoriametrics/rules/local-pv-provisioner-scrape.yaml, monitoring/base/victoriametrics/rules/neco-admission-scrape.yaml
This PR adds scrape configs of local-pv-provisioner and coil for the VictoriaMetrics largeset cluster.
This also fixes some existing VMPodMetrics configs to specify the port names explicitly.
=> monitoring: complement scrape configs for VictoriaMetrics largeset cluster.

test/Makefile, test/moco_test.go, test/sealed-secret_test.go
They are now pre-installed by neco debian package.
=> test: do not prepare kubectl-moco and kubeseal

coil/base/egress.yaml, customer-egress/base/egress.yaml
This reverts commit c42ce63085cdd55769aed67bebdb766ff039bed4.
The coil bug was fixed in 2.0.5.
https://github.com/cybozu-go/coil/blob/main/CHANGELOG.md#205---2021-01-14
=> Revert "Fix egress nat to mount `/run`"

.circleci/config.yml, argocd-config/overlays/gcp/kustomization.yaml, argocd-config/overlays/gcp/neco-admission.yaml, docs/manifests.md, namespaces/base/cert-manager.yaml, namespaces/base/internet-egress.yaml, namespaces/base/kube-system.yaml, neco-admission/base/deployment.yaml, neco-admission/base/kustomization.yaml, neco-admission/base/upstream/manifests.yaml, neco-admission/base/webhook.yaml, neco-admission/overlays/gcp/deployment.yaml, neco-admission/overlays/gcp/kustomization.yaml, neco-admission/overlays/stage0/deployment.yaml, neco-admission/overlays/stage0/kustomization.yaml, test/contour_test.go, test/local-pv-provisioner_test.go, test/network-policy_test.go, test/setup_test.go, test/storage_test.go, test/topolvm_test.go
neco-admission is configured so that it protects the following resources
if they are annotated with `admission.cybozu.com/prevent: delete`.
- PersistentVolumeClaim
- ObjectBucketClaim
- MySQLCluster
- Elasticsearch
neco-admission is also configured to deny images from untrusted sources.
=> Update neco-admission to 0.9.0

monitoring/base/prometheus/alert_rules/metallb.yaml, monitoring/base/prometheus/alert_rules/network-policy.yaml, monitoring/base/victoriametrics/rules/metallb-alertrule.yaml, monitoring/base/victoriametrics/rules/network-policy-alertrule.yaml, test/alert_test/metallb.yaml, test/alert_test/network-policy.yaml, test/vmalert_test/metallb.yaml, test/vmalert_test/network-policy.yaml
Unreachable nodes can be tainted with "NoSchedule" effect
instead of "NoExecute".
=> monitoring: fix alert rules for DaemonSets

monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml, pvc-autoresizer/base/controller.yaml
=> pvc-autoresizer: fix to refer to VictoriaMetrics instead of Prometheus

test/suite_test.go, test/team-management_test.go
This PR includes two commits:
1. Make MOCO test faster by preparing MySQLCluster early
2. Simplify RBAC test for ObjectBucket
=> Improve tests

Makefile, argocd-config/base/kube-metrics-adapter.yaml, argocd-config/base/kustomization.yaml, argocd-config/overlays/stage0/kube-metrics-adapter.yaml, argocd-config/overlays/stage0/kustomization.yaml, docs/maintenance.md, kube-metrics-adapter/base/apiservice.yaml, kube-metrics-adapter/base/cert.yaml, kube-metrics-adapter/base/deployment.yaml, kube-metrics-adapter/base/kustomization.yaml, kube-metrics-adapter/base/namespace.yaml, kube-metrics-adapter/base/upstream/manifest.yaml, test/hpa_test.go, test/setup_test.go
The manifest is based on the upstream Helm chart with the following kustomizations:
- Use cert-manager to generate TLS certificates
- Adjust command-line arguments
=> Add kube-metrics-adapter

monitoring/base/victoriametrics/vmcluster-largeset.yaml
* Because vmstorage sometimes takes a long time to start up.
=> Add startupProbe for vmstorage

monitoring/base/victoriametrics/kustomization.yaml, monitoring/base/victoriametrics/operator.yaml, monitoring/base/victoriametrics/rbac/editor_aggregation.yaml, monitoring/base/victoriametrics/rbac/viewer_aggregation.yaml, monitoring/base/victoriametrics/remove_crd_status.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmagents.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalerts.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmclusters.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmstaticscrapes.yaml, monitoring/base/victoriametrics/upstream/crd/kustomization.yaml, monitoring/base/victoriametrics/upstream/crd/patches/cainjection_in_vmstaticscrapes.yaml, monitoring/base/victoriametrics/upstream/crd/patches/webhook_in_vmstaticscrapes.yaml, monitoring/base/victoriametrics/upstream/rbac/leader_election_role.yaml, monitoring/base/victoriametrics/upstream/rbac/leader_election_role_binding.yaml, monitoring/base/victoriametrics/upstream/rbac/role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmagent_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmalert_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmalertmanager_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmnodescrape_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmprobe_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmrule_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmservicescrape_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmsingle_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmstaticscrape_editor_role.yaml, monitoring/base/victoriametrics/upstream/rbac/vmstaticscrape_viewer_role.yaml, test/team-management_test.go
Update VictoriaMetrics operator to v0.10.0.
From v0.10.0, `VMStaticScrape` CR is introduced. In this PR, add the permission to tenant teams.
https://github.com/VictoriaMetrics/operator/blob/v0.10.0/docs/quick-start.MD#VMStaticScrape
=> Update VictoriaMetrics operator to v0.10.0

monitoring/base/grafana-operator/dashboards/all-nodes.yaml, monitoring/base/grafana-operator/dashboards/calico.yaml, monitoring/base/grafana-operator/dashboards/ceph-clusters.yaml, monitoring/base/grafana-operator/dashboards/ceph-osd.yaml, monitoring/base/grafana-operator/dashboards/cert-manager.yaml, monitoring/base/grafana-operator/dashboards/coil.yaml, monitoring/base/grafana-operator/dashboards/contour.yaml, monitoring/base/grafana-operator/dashboards/cpu-usage.yaml, monitoring/base/grafana-operator/dashboards/envoy.yaml, monitoring/base/grafana-operator/dashboards/etcd.yaml, monitoring/base/grafana-operator/dashboards/ingress-watcher.yaml, monitoring/base/grafana-operator/dashboards/kube-controller-manager.yaml, monitoring/base/grafana-operator/dashboards/kubernetes-cluster.yaml, monitoring/base/grafana-operator/dashboards/kubernetes-persistence-volumes.yaml, monitoring/base/grafana-operator/dashboards/local-pv-provisioner.yaml, monitoring/base/grafana-operator/dashboards/memory-usage.yaml, monitoring/base/grafana-operator/dashboards/neco-admission.yaml, monitoring/base/grafana-operator/dashboards/sabakan.yaml, monitoring/base/grafana-operator/dashboards/topolvm-volumegroup.yaml, monitoring/base/grafana-operator/dashboards/victoriametrics-vmcluster.yaml, monitoring/base/grafana-operator/dashboards/victoriametrics-vmsingle.yaml
- do not specify concrete instance value to query
- show all namespaces using templating
- use same timerange across dashboards and don't refresh by default
- note: "Node Exporter Full" dashboard is not modified because its definition is not included in neco-apps but is downloaded from grafana.com
=> refine Grafana dashboards

team-management/base/cydec/app-gorush.yaml, team-management/base/ept/app-ept-monitoring.yaml, team-management/base/ept/app-ept-wiki.yaml, team-management/base/garoon/app-garoon-monitoring.yaml, team-management/base/garoon/app-garoon-static.yaml, team-management/base/garoon/kustomization.yaml, team-management/base/garoon/project.yaml, team-management/base/maneki/project.yaml
This PR includes:
- Add `app-garoon-monitoring` namespace and bind admin roles to `garoon` and `maneki` team
- Fix: add admin role binding of tenant teams's namespace to `node-maneki` ServiceAccount
=> Add app-garoon-monitoring namespace.

logging/base/promtail.yaml, logging/base/promtail/configmap.yaml, test/logging_test.go
This PR adds a job for promtail scraping audit logs from API servers.
It should be merged after: https://github.com/cybozu-go/neco/pull/1444
=> monitoring: Add scrape job for audit log

test/env.go, test/metallb_test.go, test/monitoring_test.go, test/teleport_test.go, test/test.sh
This PR removes placemat v1 compatible codes. Also, reverts Teleport test to run on the test host. 
The original teleport test modifies `/etc/hosts` using sed and it leads to the error when the test runs inside a k8s container. So this PR fixes it to stop using sed as well.
=> Remove Placemat v1 compatible codes

monitoring/base/victoriametrics/vmagent-largeset.yaml, monitoring/base/victoriametrics/vmagent-smallset.yaml
As we faced the scraping error caused by the response size of the scraping metrics, this PR increased the maxScrapeSize parameter of VictoriaMetrics Agent.
=> Increase maxScrapeSize

team-management/base/maneki/app-forest-archive.yaml, team-management/base/maneki/kustomization.yaml, team-management/base/maneki/project.yaml
- add app-forest-archive to deploy ObjectBucketClaim to store old logs.
- allow maneki team to manage it.
=> add app-forest-archive namespace and allow maneki to manage it.

monitoring/base/victoriametrics/operator.yaml, monitoring/base/victoriametrics/rules/monitoring-scrape.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmagents.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalerts.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmclusters.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmprobes.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmsingles.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmstaticscrapes.yaml, monitoring/base/victoriametrics/upstream/rbac/role.yaml, monitoring/base/victoriametrics/vmagent-largeset.yaml, monitoring/base/victoriametrics/vmalert-largeset.yaml, monitoring/base/victoriametrics/vmalertmanager-largeset.yaml, monitoring/base/victoriametrics/vmcluster-largeset.yaml
This PR updates VictoriaMetrics operator from 0.10.0 to 0.12.2, and refines its manifests as follows.
* use embedded PodDisruptionBudget; introduced in 0.12.0
* remove `topologySpreadConstraints`s because they are duplicates of the default setting in Neco environment
cf. https://github.com/cybozu-go/neco/blob/main/etc/cke-template.yml
* restore `livenessProbe` for vmstorage; removed in 0.12.1
* fix port name of vmalertmanager for scraping; changed in 0.11.0
=> monitoring: update VictoriaMetrics operator to 0.12.2

monitoring/base/grafana-operator/dashboards/all-nodes.yaml
The panel `Top 10 Nodes: High Memory Usage` in Grafana dashboard calculates the available bytes without omitting disk cache memory usage.
This PR fixes the configuration to use `node_memory_MemAvailable_bytes`, which is truly meaningful for node monitoring.
=> monitoring: Update high memory usage panel to use available bytes

monitoring/base/victoriametrics/rules/monitoring-alertrule.yaml, test/vmalert_test/monitoring.yaml
Currently, the alerting thresholds for some of the victoria-metrics smallset are set to 15m.
However, this is too short and alerts comes up if rebooting the node where the smallset pods are running takes more than 15m,
unnecessary alerts come up.
This PR extends the value to 60m to suppress the unnecessary alerts.
=> monitoring: extend alerting threshold for smallset to 60m

argocd-config/overlays/osaka0/kustomization.yaml, argocd-config/overlays/tokyo0/kustomization.yaml
This PR fixes a bug: `neco-tenant-apps` has not been deployed to tokyo0 and osaka0.
=> deploy neco-tenant-apps to tokyo0 and osaka0

argocd-config/base/prometheus-adapter.yaml
In order to avoid `__name__!~"^container_.*"` queries, which try to return too much metrics.
The upstream helm chart has no ability to enable `__name__=~"^container_.*"` queries and `__name__!~"^container_.*"` queries separately. We disable all of them and write `__name__=~"^container_.*"` queries as custom queries manually.
=> prometheus-adapter: narrow down metrics retrieval

logging/base/loki/main.jsonnet, logging/base/loki/upstream/apps-v1.StatefulSet-querier.yaml, test/setup_test.go
querier caches index whose size is 500Mi per day.
If searches are executed for 20 days, querier requires 10Gi, this makes it disk full.
To prevent such a situation, I enlarge disk space to 100Gi.
=> loki: enlarge disk size to avoid disk full for querier

argocd-config/base/argocd-config.yaml, argocd-config/base/kustomization.yaml, argocd-config/overlays/osaka0/argocd-config.yaml, argocd-config/overlays/osaka0/kustomization.yaml, argocd-config/overlays/stage0/argocd-config.yaml, argocd-config/overlays/stage0/kustomization.yaml, argocd-config/overlays/tokyo0/argocd-config.yaml, argocd-config/overlays/tokyo0/kustomization.yaml
If you rewrite argocd-config application resource manually, it does not automatically revert back.
So, we will use ArgoCD to manage the resource.
=> Add application manifests for argocd-config

test/Makefile
If the local branch name is "main", argocd sync revision in a test environment refers to remote "main" branch.
If the local branch revision differs from the remote one, the user intended test revision also differs.
To prevent such a situation, use commit hash instead of the branch name.
=> use commit hash to stabilize test revision

argocd-config/base/namespaces.yaml, argocd-config/base/team-management.yaml, argocd-config/overlays/osaka0/argocd-config.yaml, argocd-config/overlays/stage0/argocd-config.yaml, argocd-config/overlays/tokyo0/argocd-config.yaml
- Enable auto-prune for `namespaces`  app and `team-management` app.
- Set default setting of sync policy explicitly for `argocd-config` app.
=> Update applications sync policy

argocd-config/base/rook.yaml, rook/base/common/patch.yaml
CRD spec.preserveUnknownFields default is true until v1beta1, but as of v1, it is false and can not be set to true.
When updating API version, we did not set preserveUnknownFields explicitly, so the value is true.
If we update other fields in the CRD, k8s rejects the update because preserveUnknownFields is true.
This PR set preserveUnknownFields to false explicitly and ignore the field by Argocd to avoid sync failure.
=> Rook: set preserveUnknownFields to false explicitly

monitoring/base/victoriametrics/vmsingle-smallset.yaml
The previous value 15d was a bit shorter for post-investigation.
I assume 2 months is sufficient and expect it consumes about 20GB
of disk space but it could not exhaust all space.
=> monitoring: lengthen the retention period for smallset.

monitoring/base/grafana-operator/dashboards/kube-apiserver.yaml
The current query for the CPU Usage panel is not working because the instance label of `process_cpu_seconds_total` metrics contains port numbers and that of `machine_cpu_cores` does not.
This PR omits the division by `machine_cpu_cores` and let CPU Usage panal show the total usage of CPUs in kube-apiserver.
=> Fix CPU Usage panal for kube-apiserver

monitoring/base/grafana-operator/dashboards/all-nodes.yaml
Currently, there is no panel to check the number of reboot for each nodes.
As viewing the number is important because kernel panic leads to reboot its node, this PR add the panel to show the reboot timing.
The timing is calculated by the equation
```
deriv(time() - node_boot_time_seconds{}) < bool 0.1
```
=> Add reboot node time panel

test/setup_test.go
=> Remove temporally codes

.circleci/config.yml, coil/base/addresspool.yaml, coil/overlays/stage0/addresspool.yaml
Modify the AddressPool setting of domestic-egress for dctest to be the same as stage because it does not match the GlobalNetWorkPolicy settings.
This PR disables upgrade tests temporarily because AddressPool change is rejected in upgrade tests.
=> Modify the AddressPool setting of domestic-egress

monitoring/base/grafana-operator/dashboards/all-nodes.yaml
I saw [this webpage](https://tips.weseek.co.jp/Tips/Prometheus/Kubernetes%28GKE%29%20%E3%81%A7%E4%BE%BF%E5%88%A9%E3%81%AA%20Prometheus%20%E5%B0%8F%E3%83%8D%E3%82%BF%E9%9B%86#Node%20%E3%81%AE%E5%86%8D%E8%B5%B7%E5%8B%95%E3%82%92%E6%A4%9C%E7%9F%A5%E3%81%99%E3%82%8B) and thought that using [this changes() function](https://prometheus.io/docs/prometheus/latest/querying/functions/) would show the reboot count more properly.
Therefore, this PR modified the current query to show each nodes' reboot timing by using `changes()` function.
=> Modify reboot count query

rook/base/ceph-hdd/cluster.yaml, rook/base/ceph-hdd/configmap.yaml, rook/base/ceph-hdd/deployment.yaml, rook/base/ceph-hdd/kustomization.yaml, rook/base/ceph-ssd/cluster.yaml, rook/base/ceph-ssd/configmap.yaml, rook/base/ceph-ssd/deployment.yaml, rook/base/ceph-ssd/kustomization.yaml, rook/base/upstream/kustomization.yaml, rook/base/values.yaml
We found an issue that the prepare job is failed and the osd process does not come up.
The issue is related to bluefs io mode, so to avoid the issue, we set bluefs_buffered_io to alse.
=> update ceph witch comfigmap to avoid bluefs corruption

rook/base/ceph-hdd/cluster.yaml, rook/base/ceph-ssd/cluster.yaml
The field `.spec.resources.osd` was not worked but it has fixed in Rook
1.6 or lator. Set the resource limits using the `.spec.resources` field in line with other resources.
=> Rook: use `.spec.resources.osd` to set resource limits for OSD

bmc-reverse-proxy/base/bmc-reverse-proxy/service.yaml, customer-egress/base/neco/squid.yaml, customer-egress/base/squid.yaml, ingress/base/template/service.yaml, teleport/base/service.yaml, test/Makefile, test/reboot_test.go, test/vmalert_test/kube-state-metrics.yaml
- Upgrade tools' versions in test/Makefile
- Use `node-role.kubernetes.io/control-plane` instead of `node-role.kubernetes.io/master` that is referred to test and squid.yaml
- Set Service.spec.allocateLoadBalancerNodePorts=false to Load Balancer Services that don't need node port.
=> Updates for k8s 1.20

monitoring/base/grafana-operator/dashboards/all-nodes.yaml
Sometimes, `node_boot_time_seconds` fluctuates in a small range especially when its node is up.
Such fluctuations are nothing related to rebooting, so fix the query for detecting rebooting nodes to ignore them.
=> fix reboot count query

topolvm/base/kustomization.yaml, topolvm/base/provisioner.yaml, topolvm/base/storageclass.yaml
This introduces two new storageclasses to provide ext4 and xfs using topolvm.
Previously, a SC with xfs using topolvm is provided as topolvm-provisioner,
but its name is not user friendly, so we add a more sophisticated one and
retain topolvm-provisioner for compatibility.
=> topolvm: add new storageclasses

team-management/base/common/project.yaml, team-management/template/team-management/base/common/project.libsonnet
After update of Argo CD (in container regular update), some cluster resources are out of sync. Add them to whitelist.
=> fix tenant OutOfSync after Argo CD update

rook/base/ceph-hdd/cluster.yaml, rook/poc/ceph-poc/cluster.yaml
We observed that an osd is crash looping because of its livenessProbe. With our investigation, the startup process is successful but too slow.
This PR extends the initialDelaySeconds to survive in such a case.
=> Rook/Ceph: expand livenessProbe.initialDelaySeconds for osd pod

rook/base/ceph-hdd/cluster.yaml, rook/poc/ceph-poc/cluster.yaml
livenessProve is incorrectly configured, so undo the PR.
=> Rook/Ceph: revert manifest to remove livenessProbe.initialDelaySeconds for osd pod

neco-admission/base/config.yaml, team-management/template/neco-admission/base/config.libsonnet, test/admission_test.go
This PR uses `repositoryPrefix` to validate ArgoCD Applications.
All teams in `settings.json` except `neco-devusers` will be able to deploy Applications from `cybozu-private` organization.
I think this PR can be reviewed and merged now because the [fix of neco-admission](https://github.com/cybozu/neco-containers/pull/632) is not urgent and can be deployed later.
=> admission: use repositoryPrefix for repository validation

argocd-config/overlays/osaka0/argocd-config.yaml, argocd-config/overlays/stage0/argocd-config.yaml, argocd-config/overlays/tokyo0/argocd-config.yaml
Change 'argocd-config' Application's sync-wave in order to sync this Application last.
Before this PR, argocd-config's sync-wave is not set (= sync-wave "0"). This may cause syncing other child Applications themselves (such as adding/deleting Applications) stuck.
see also: https://github.com/cybozu-go/neco/issues/1661
=> change argocd-config's sync-wave to 9999

rook/overlays/gcp/kustomization.yaml
=> Rook/Ceph: expand dctest osd size to defer disk full

rook/base/ceph-hdd/cluster.yaml, rook/base/ceph-hdd/deployment.yaml, rook/base/ceph-ssd/deployment.yaml, rook/base/upstream/kustomization.yaml, rook/base/values.yaml, rook/poc/ceph-poc/cluster.yaml, rook/poc/ceph-poc/deployment.yaml
Avoid the problem of OSDs that take a long time to initialize being terminated by livenessProbe.
=> Rook/Ceph: extend livenessProve.initialDelaySeconds

argocd/base/configmap.yaml, team-management/base/common/project.yaml, team-management/template/team-management/base/common/project.libsonnet
=> team-management: add CSA team having the same permission as neco team

monitoring/base/victoriametrics/kustomization.yaml, monitoring/base/victoriametrics/rules/moco-alertrule.yaml, test/vmalert_test/moco.yaml
This PR adds an alert rule to check `moco-controller` metrics is scraped
=> add moco controller alert rule

rook/base/ceph-hdd/cephobjectstore.yaml, rook/poc/ceph-poc/cephobjectstore.yaml, test/storage_test.go
- double rgw pods to high availability
- add anti-affinity to spread across racks
issue: cybozu-go/neco#1662
=> rook: double rgw pods

Makefile, monitoring/base/victoriametrics/kustomization.yaml, monitoring/base/victoriametrics/vmalertmanager-largeset.yaml, monitoring/base/victoriametrics/vmalertmanager-smallset.yaml
This commit disables the hash suffix functionality for the ConfigMaps
used in VMAlertmanager CRs.
The update of ConfigMap contents is detected by the configmap-reload
sidecar containers instead.
With this commit we can avoild the early deletion of old ConfigMaps
by Argo CD, the instability of the VMAlertmanager StatefulSets, and
the hang-up of VictoriaMetrics operator's reconciliation.
=> Disable hash suffix for VMAlertmanager ConfigMaps to stabilize update

neco-admission/base/kustomization.yaml, test/admission_test.go, test/testdata/admission-pod.yaml
part of https://github.com/cybozu-go/neco/issues/1647
use neco-admission 0.11.1 to limit local ephemeral storage.
=> upgrade neco-admission 0.11.1

rook/base/ceph-hdd/cephobjectstore.yaml, rook/base/ceph-hdd/cluster.yaml, rook/base/ceph-hdd/kustomization.yaml, rook/base/ceph-hdd/mgr-pdb.yaml, rook/base/ceph-ssd/cluster.yaml, rook/base/ceph-ssd/kustomization.yaml, rook/base/ceph-ssd/mgr-pdb.yaml, rook/poc/ceph-poc/cephobjectstore.yaml, rook/poc/ceph-poc/cluster.yaml, rook/poc/ceph-poc/kustomization.yaml, rook/poc/ceph-poc/mgr-pdb.yaml, test/storage_test.go
- Rook manages PDB for OSD, MON, RGW.
- If the number of RGW is two, Rook does not create PDB (BUG?), so we create 3 instances for a workaround.
- Current Rook does not manage PDB for MGR, so we create it manually.
issue: cybozu/csa#3
=> Rook: enable PDB for ceph daemons

rook/base/ceph-hdd/cluster.yaml, rook/base/ceph-ssd/cluster.yaml, rook/poc/ceph-poc/cluster.yaml
=> Rook/Ceph: disable pdb for osd to avoid blocking node reboot

monitoring/base/victoriametrics/vmcluster-largeset.yaml
Expand VictoriaMetrics storage size to 3GB,  since we get no space left error if we don't stop dctest few days.
=> VictoriaMetrics: Expand largeset's storage size on dctest

monitoring/base/grafana-operator/dashboards/etcd.yaml, test/setup_test.go
This PR removes `ETCDCTL_API=3`, that becomes default on etcd 3.4.
Also, it replaces `etcd_debugging_mvcc_db_total_size_in_bytes` with `etcd_mvcc_db_total_size_in_bytes`.
=> Remove ETCDCTL_API variable

pod-security-admission/base/configmap.yaml, pod-security-admission/base/kustomization.yaml, pod-security-admission/base/upstream/install.yaml, pod-security-admission/base/webhook.yaml, test/psa_test.go, test/setup_test.go, test/suite_test.go, test/testdata/psa-hostnetwork-pod.yaml, test/testdata/psa-hostpath-pod.yaml
part of https://github.com/cybozu-go/neco/issues/1694
- add "traceable" policy which can use /sys/kernel/tracing hostPath.
=> add traceable policy which can use perf

team-management/base/sandbox/sandbox.yaml
This PR adds `development: "true"` to the sandbox namespace.
It applies to all the clusters (incl. tokyo0 and osaka0).
=> Add development label to sandbox namespace

argocd-config/base/pod-security-admission.yaml, docs/manifests.md, meows/overlays/gcp/kustomization.yaml, meows/overlays/gcp/namespace.yaml, meows/overlays/gcp/webhook.yaml, namespaces/base/cert-manager.yaml, namespaces/base/internet-egress.yaml, namespaces/base/kube-system.yaml, pod-security-admission/base/certificate.yaml, pod-security-admission/base/configmap.yaml, pod-security-admission/base/kustomization.yaml, pod-security-admission/base/namespace.yaml, pod-security-admission/base/upstream/install.yaml, pod-security-admission/base/webhook.yaml, test/setup_test.go
This PR refines the following webhooks.
* meows
* Limit the target namespaces of the webhook
* pod-security-admission
* Import the latest manifests from the upstream
* The PSA objects are deployed into kube-system namespace instead of psa-system namespace
* This prevents the PSA Pods from being blocked by webhooks
=> Refine meows and pod-security-admission webhooks

meows/overlays/gcp/namespace.yaml, meows/overlays/stage0/kustomization.yaml, meows/overlays/stage0/runnerpool.yaml
Add two runner pools to be used for testing in the neco-tenant-apps repository.
- The `dctest-runner` is a runner pool that waits for jobs after preparing a dctest environment with neco and neco-apps bootstrap. 
- The [`bootstrap.sh`](https://github.com/cybozu/neco-containers/blob/main/dctest-meows-runner/bootstrap.sh) that is run by dctest-runner is provided in the [image](https://github.com/cybozu/neco-containers/blob/main/dctest-meows-runner/Dockerfile).
- The `default-runner` is a runner pool that waits for jobs without preparing a dctest environment. This is necessary to run jobs that do not require a dctest environment, as it takes time to prepare one.
The mount settings, etc. were based on the previous PoC.
- https://github.com/cybozu/neco-containers/tree/poc-run-placemat-on-k8s/dct …
=> add `RunnerPool` of meows for neco-tenant-apps repository

argocd-config/base/init-template.yaml, argocd-config/base/kustomization.yaml, argocd-config/overlays/stage0/init-template.yaml, argocd-config/overlays/stage0/kustomization.yaml, init-template/base/kustomization.yaml, init-template/base/namespace.yaml, team-management/base/dbre/dev-dbre.yaml, team-management/base/maneki/app-maneki.yaml, team-management/base/maneki/dev-maneki.yaml, team-management/base/network/dev-network.yaml, team-management/template/settings.json, test/team-management_test.go, test/validation_test.go
This PR adds `init-template` Application that deploys `init-template` namespace.
It is annotated as a template namespace of Accurate, that stores common resources.
=> Set accurate template for tenant root namespaces

monitoring/base/victoriametrics/rules/moco-scrape.yaml
It seems that the original manifest selects all pods.
=> fix VMPodScrapes for moco

meows/overlays/stage0/runnerpool.yaml
If you let dctest-runner wait for a long time, the size of the volume prepared in `/var/scratch` will be exhausted and the test execution environment will die.
I know that the 300Gi size that I have available will be consumed in about 20 hours at this point.
It consumes about 100Gi when it is just started, and the trend is roughly linear, consuming 100Gi per 10 hours.
If this trend remains unchanged for more than 20 hours, this change will increase the deadline of the test execution environment by 10 hours.
In the future, meows will be added a feature to recreate the test execution environment.
We plan to use the feature to recreate the test execution environment in 24 hours, so 30 hours of its availability will be sufficient.
While the feature to recreate cannot be enabled, you will need …
=> extend disk size used `/var/scratch` in dctest-runner

test/meows_test.go
In the test checking meows online runner pods, the curl options, and `pipefail` option were not set properly, so I fixed that.
Also, the error when checking the online runner pod was not clear, so I added a few notes.
=> fix meows test

test/testdata/meows-runnerpool.tmpl.yaml
- The image of the RunnerPool resource used for testing was specified with the latest tag.
- In connection with the release of meows, only the Image version of runner has been increased and is no longer executable.
- Fixed to explicitly specify the version.
=> fix RunnerPool image for test

test/setup_test.go, test/storage_test.go
When restarting the node, the pods are not created and confirmOsdPrepare() falls into an error.
This is a problem with the point where confirmOsdPrepare() is called.
Therefore, we changed the location of the call to confirmOsdPrepare().
=> Move confirmOsdPrepare() to testSetup().

rook/base/ceph-hdd/configmap.yaml, rook/base/ceph-object-store/configmap.yaml, rook/base/ceph-ssd/configmap.yaml, rook/overlays/gcp/ceph-hdd/debug.yaml, rook/overlays/gcp/ceph-object-store/debug.yaml, rook/poc/ceph-poc-2/configmap.yaml, rook/poc/ceph-poc/configmap.yaml
Suppress the folowing warning.
```
health: HEALTH_WARN
1 pools have many more objects per pg than average
```
The definition of this parameter is as follows.
https://github.com/ceph/ceph/blob/d31130d4516a36c585b1224c193ec720f31c649c/src/common/options/mgr.yaml.in#L237-L247
```
- name: mon_pg_warn_max_object_skew
type: float
level: advanced
desc: max skew few average in objects per pg
fmt_desc: Raise ``HEALTH_WARN`` if the average RADOS object count per PG
of any pool is greater than ``mon_pg_warn_max_object_skew`` times
the average RADOS object count per PG of all pools. Zero or a non-positive
number disables this. Note that this option applies to ``ceph-mgr`` daemons.
default: 10
services:
- mgr
```
This warning is harmless in Neco's Ceph clusters because we don't care the difference of …
=> Rook/Ceph: disable warning by MANY_OBJECTS_PER_PG for ceph-ssd

logging/base/promtail/config/promtail.yaml
- Each start and end of the ssh session was given a unique label value.
- The value of `session-1.scope` etc. at the beginning of ssh is converted to `session.scope`.
- The value of `sshd@231-10.69.0.4:22-10.72.48.0:41850.service` etc. at the end of ssh is converted to `sshd.service`
=> add relable_configs for session and sshd

monitoring/base/victoriametrics/rules/node-alertrule.yaml, test/vmalert_test/node.yaml
This PR adds two alerts.
- ChronyMetricsMissing: alert if chrony metrics is missing on machines that are visible to sabakan.
It is expected to find failure when node_exporter is running but chrony_monitor is not rendering metrics correctly.
- NodeClockSkew: alert if node's system time is fastened or delayed by a certain amount.
The severity is set to warning for a while.
=> Alert if clock skew is detected

test/monitoring_test.go, test/team-management_test.go, test/teleport_test.go
=> insert double dash before remote command of `kubectl exec`

meows/overlays/stage0/kustomization.yaml
Enable `dctest-runner` when [dctest: Run chrony on VM](https://github.com/cybozu-go/neco/pull/1850) is on the release branch. 
=> Enable and update dctest-runner

argocd/base/kustomization.yaml, argocd/base/upstream/install.yaml, cert-manager/base/kustomization.yaml, cert-manager/base/upstream/cert-manager.yaml, docs/maintenance.md, external-dns/base/deployment.yaml, external-dns/base/rbac.yaml, ingress/base/contour/01-contour-config.yaml, ingress/base/contour/01-crds.yaml, ingress/base/contour/02-job-certgen.yaml, ingress/base/contour/02-role-contour.yaml, ingress/base/contour/03-contour.yaml, ingress/base/contour/03-envoy.yaml, ingress/base/kustomization.yaml, ingress/base/template/common.yaml, ingress/base/template/deployment-contour.yaml, ingress/base/template/deployment-envoy.yaml, neco-admission/base/kustomization.yaml, network-policy/base/kustomization.yaml, test/Makefile, test/team-management_test.go
https://github.com/cybozu/neco-containers/pull/710
Update ArgoCD to v2.1.8 
Update Calico image to 3.20.0.3 
Update cert-manager to v1.6.1 
Update exteral-dns to v0.10.2 
Update neco-admission to v0.15.1 
Update Contour to v1.19.1 
=> Container regular update (ArgoCD, Calico, cert-manager, Contour, ExternalDNS and neco-admission)

monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml, test/vmalert_test/kubernetes.yaml
Currently, `K8sAPIServersDegraded warning` rings on machine reboot, because it takes longer than the alert threshold.
This PR relaxes the time to 30mins, which is equal to that of `NodeExporterDown`.
=> Relax K8sAPIServersDegraded to 30mins

team-management/base/dbre/team-dbre.yaml, team-management/template/settings.json
Add `pod-security.cybozu.com/policy: traceable` to `team-dbre` namespace.
This is required to convert DBRE namespaces into subnamespaces of `team-dbre`.
=> Add traceable policy to team-dbre namespace

argocd-config/base/prometheus-adapter.yaml, metallb/base/kustomization.yaml, metallb/base/upstream/example-config.yaml, metallb/base/upstream/metallb.yaml, metallb/base/upstream/prometheus-operator.yaml, monitoring/base/kustomization.yaml, monitoring/base/victoriametrics/operator.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmagents.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalertmanagers.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmalerts.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmauths.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmclusters.yaml, monitoring/base/victoriametrics/upstream/crd/bases/operator.victoriametrics.com_vmsingles.yaml, monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmagents.yaml, monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmalertmanagers.yaml, monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmalerts.yaml, monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmauths.yaml, monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmclusters.yaml, monitoring/base/victoriametrics/upstream/crd/legacy/operator.victoriametrics.com_vmsingles.yaml, monitoring/base/victoriametrics/upstream/rbac/role.yaml, monitoring/base/victoriametrics/vmalert-largeset.yaml, monitoring/base/victoriametrics/vmalert-smallset.yaml
Part of the container reguler update.
Update MetalLB to v0.11.0 
Update VictoriaMetrics to v0.70.0 and config-reloader to v0.53.0 
Update VictoriaMetrics operator to v0.21.0 
Update Prometheus Adapter to v0.9.1 (Chart v3.0.0) 
Update Pushgateway to v1.4.2 
=> Container reguler update (2021-12)

monitoring/README.md, monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml, test/vmalert_test/sabakan.yaml
- Add node failure alert
- Generate an alert labeled `severity: urgent` when `sum(sabakan_machine_status{status="unreachable"}) > 0` for 60 minutes.
- Confirmed that there are no false alerts due to the reboot of all node.
- Add description about the urgent severity
=> Add node failure alert

argocd-config/base/rook.yaml
In accordance with `kubectl`'s behavior, change resource prune deletion
propagation policy to the background. This is because some of Rook's CRD
sets ownerReference and uses cascading deletion to delete some resources.
And it expects the background deletion policy.
issue: cybozu/csa#84
=> Rook: change resouces prune deletion propagation policy to background

monitoring/base/grafana-operator/dashboards/cert-manager.yaml, monitoring/base/victoriametrics/rules/cert-manager-scrape.yaml
The `namespace=cert-manager` label in the metrics retrieved from cert-manager is meaningless, so change it to be the name of the namespace where the certificate exists.
before metrics
```
certmanager_certificate_*{exported_namespace="<name of namespace where the certificate>", namespace="cert-manager"}
```
after metrics
```
certmanager_certificate_*{exported_namespace="<name of namespace where the certificate>", namespace="<<namespace name where the certificate>>"}
```
The `exported_namespace` label is already in use for alerts and dashboards, so `exported_namespace` will be kept temporarily.
The `exported_namespace` label will be removed when it is no longer used.
- With this change, metrics other than certmanager_certificate_* will also have the new label exported_namaspace=certmanager, …
=> Fix namespace label on cert-manager metrics.

network-policy/base/kustomization.yaml, network-policy/base/policies/hubble-relay.yaml, test/suite_test.go, test/team-management_test.go
This PR 
- Modifies team-management_test so that it works both with and without Cilium.
- Adds NetworkPolicy to allow hubble-relay to access cilium-agent running on each node.
=> Prepare Cilium setup

monitoring/base/victoriametrics/rules/cert-manager-alertrule.yaml, test/vmalert_test/cert-manager.yaml
After confirming that https://github.com/cybozu-go/neco-apps/pull/2163 is stage-released and correctly labeled, modify the alert rules to stop using the `exported_namespace` label and use the `namespace` label.
=> Use namespace label for cert-manager alerts

monitoring/base/victoriametrics/vmagent-largeset.yaml, monitoring/base/victoriametrics/vmagent-smallset.yaml
increase limit because metrics size of kube-state-metrics significantly increased (from less than 32M to more than 64M).
=> increase vmagent's maxScrapeSize to 200MiB

monitoring/base/victoriametrics/rules/cert-manager-scrape.yaml
Will be applied to stage on Jan 25 and prod on Jan 26.
=> [Merge to main on Jan 24]Remove exported_namespace label for cert-manager metrics

monitoring/base/victoriametrics/rules/kubernetes-scrape.yaml, network-policy/base/global-policies/controller-manager.yaml
part of https://github.com/cybozu-go/neco-apps/issues/2075
=> use HTTPS port to scrape kube-controller-manager metrics

monitoring/base/victoriametrics/rules/kubernetes-scrape.yaml
part of https://github.com/cybozu-go/neco-apps/issues/2075
forgot to use https scheme (and auth tokens) in https://github.com/cybozu-go/neco-apps/pull/2192
=> use HTTPS port to scrape kube-controller-manager metrics (fix)

monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml, test/vmalert_test/sabakan.yaml
Fixed false NodeUnreachable alerts when multiple machines were in the `sabakan_machine_status{status="unreachable"}` state alternately.
By changing the evaluation formula to separate instance, address, and serial, an alert will be issued only when one unit is unreachable for 60 minutes.
=> Fix false NodeUnreachable alerts.

grafana-sandbox/overlays/common/grafana.yaml, grafana-sandbox/overlays/common/kustomization.yaml
to prevent `kustomize` from incorrectly rewriting the name of the Secret
in the Role.
part of https://github.com/cybozu-go/neco/issues/1871
=> rename grafana ConfigMap

argocd-config/overlays/stage0/tenants/garoon-apps.yaml, team-management/template/argocd-config/overlays/template/tenants/main.libsonnet
Migrate only stage0 to migrate garoon-apps repoURL step by step.
Edit jsonnet directly to put in specific processing.
before(only stage0 overlay): https://github.com/garoon-private/garoon-apps.git
after(only stage0 overlay): https://github.com/cybozu-private/garoon-apps.git 
=> Add workaround for switching app with overlays for garoon-apps.

monitoring/base/victoriametrics/rules/kube-storage-version-migrator-alertrule.yaml, test/vmalert_test/kube-storage-version-migrator.yaml
This alert rule can only detect migration rarely. It is useless.
=> remove incomplete storage version migration detection

test/domestic-egress_test.go, test/network-policy_test.go, test/testdata/network-policy.yaml
This PR fixes the broken network policy tests in which ping failed because the ubuntu pod doesn't have the permission to ping. Also it fixes the domestic egress test.
=> Fix tests for network policy

test/reboot_test.go, test/replica_test.go
`AvailableReplicas` in StatefulSetStatus is available since k8s 1.22. It is more preferable than ReadyReplicas.
=> use AvailableReplicas instead of ReadyReplicas

Makefile, bin/curl-github, bin/wget-github, test/Makefile
This PR enables the GitHub auth token in the neco-apps test in a similar way to https://github.com/cybozu-go/neco/pull/1926 .
Shell scripts are copied from cybozu-go/neco rather than referred because cybozu-go/neco does not always exist, especially in setup.
=> Send token when downloading materials from GitHub

argocd-config/base/cattage.yaml
helm chart v0.1.3 is for cattage v0.1.1
=> Update cattage to v0.1.1

monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml
It may not be a problem for the parser since it is single-quoted, but VSCode redline it.
=> fix bad indent of line continuation

network-policy/base/policies/teleport.yaml
Teleport apps can't access teleport-proxy LB because Cilium doesn't properly handle packets destined to LB services from Pod. It manages backends for LB services only if NodePort is enabled. Cilium is aware of those packets' destination as host. 
https://github.com/cilium/cilium/blob/917051f8efcd477552d649e4af38f9dbbbc55e97/pkg/k8s/service.go#L452 
This PR works around this issue by adding the policy that allows teleport apps to access teleport-proxy LB.
=> Allow teleport apps to access teleport-proxy LB

argocd-config/base/accurate.yaml, argocd-config/base/cattage.yaml, argocd-config/base/moco.yaml, argocd-config/base/prometheus-adapter.yaml, argocd-config/base/tenet.yaml, argocd-config/base/topolvm.yaml, argocd/base/configmap.yaml
- Add system level ignoreDifferences for Certificate.
- All tenant users may need this setting.
- Convert to new keys in `argocd-cm` ConfigMap.
- The new kay format is introduced in Argo CD v2.1.0. And the old format is deprecated.
- https://blog.argoproj.io/argo-cd-v2-1-first-release-candidate-is-ready-c1aab7795638
=> Add system level ignoreDifferences for Certificate

monitoring/base/victoriametrics/rules/kubernetes-alertrule.yaml, test/vmalert_test/kubernetes.yaml
The usage of VictoriaMetrics PVs is saw-toothed. The original alert rule is too sensitive and causes many false positives.
=> loosen PersistentVolumeUsageRapidIncrease alert for VictoriaMetrics PVs

monitoring/base/cadvisor/daemonset.yaml
cAdvisor pods are sometimes throttled, despite the low CPU usage. 
I try improving the throttling by setting the GOMAXPROCS.
Current CPU limits of cadvisor DaemonSet.
```
name: cadvisor
resources:
limits:
cpu: 800m
ephemeral-storage: 1Gi
memory: 2000Mi
requests:
cpu: 400m
ephemeral-storage: 200Mi
memory: 400Mi
```
Actual CPU usage.
```
cybozu@stage0-boot-0:~$ kubectl top pod -n monitoring | grep cadvisor | head -n 5
cadvisor-28fhj                                         199m         106Mi
cadvisor-4c4fh                                         111m         53Mi
cadvisor-4gsll                                         193m         83Mi
cadvisor-4rs2d                                         197m         83Mi
cadvisor-5b664                                         203m         92Mi
``` …
=> Set GOMAXPROCS to cAdvisor DaemonSet

argocd/base/configmap.yaml
Convert to new keys in `argocd-cm` ConfigMap.
The new kay format is introduced in Argo CD v2.1.0. And the old format is deprecated.
https://blog.argoproj.io/argo-cd-v2-1-first-release-candidate-is-ready-c1aab7795638
The new key are in the form: `resource.customizations.health.<group_kind>`
=> Convert to new argocd-cm format

argocd/base/configmap.yaml
Tenant users can use cattage to manage app-of-apps application resources themselves.
In order to synchronize app-of-apps application resources, their status must always be HEALTHY.
=> The status of app-of-apps application must always be HEALTHY

team-management/base/dbre/project.yaml, team-management/base/maneki/project.yaml, team-management/template/settings.json
DBRE team requests permission to deploy to `app-dbre-monitoring` namespace.
=> Allow dbre team to deploy to app-dbre-monitoring

monitoring/base/cadvisor/daemonset.yaml
Enable `oom_event`
- `container_oom_events_total` is useful to check memory limits.
Increase CPU limits
- cAdvisor pods are still throttled.
ref: https://github.com/cybozu-go/neco-apps/pull/2423
=> Enable oom_envent

monitoring/base/victoriametrics/rules/sabakan-alertrule.yaml, test/vmalert_test/sabakan.yaml
- `BootServerNotHealthy`: fire individual alerts for each boot server.
- `NodeUnreachable`: output rack number in alerts.
=> improve node unreachable alerts

rook/base/ceph-object-store-clusterrolebinding/values.yaml, rook/base/ceph-object-store.yaml, rook/base/ceph-object-store/values.yaml, rook/base/ceph-poc-clusterrolebinding/values.yaml, rook/base/ceph-poc/values.yaml, rook/base/ceph-ssd-clusterrolebinding/values.yaml, rook/base/ceph-ssd.yaml, rook/base/ceph-ssd/values.yaml, rook/base/common/values.yaml, rook/base/values.yaml, rook/overlays/stage0/ceph-poc/ceph-poc.yaml
issue: cybozu/csa#21
cephcsi is replaced with the self-built container.
(cf. https://github.com/cybozu/neco-containers/pull/769)
=> rook: replace cephcsi container with self-built one.

monitoring/base/grafana-operator/grafana.yaml, monitoring/overlays/gcp/grafana-operator/grafana.yaml
Grafana pods are throttled hard.
There is no need to set the CPU limits (it is the defualt value of grafana operator), so I remove it.
Current CPU limits of Grafana Deployment.
```
resources:
limits:
cpu: 500m
memory: 1Gi
requests:
cpu: 100m
memory: 256Mi
```
Actual CPU usage.
```
$ kubectl top pod -n monitoring | grep grafana-deployment
grafana-deployment-857d76dd56-gtrxl                    233m         135Mi
grafana-deployment-857d76dd56-xn4gw                    2m           111Mi
```
=> Remove resources limits from Grafana deployment

team-management/base/dbre/project.yaml, team-management/base/maneki/project.yaml, team-management/template/settings.json
DBRE team requests permission to deploy to `app-dashboard-server-db` namespace.
=> Add dbre team to deploy to app-dashboard-server-db

argocd-config/base/elastic.yaml, argocd-config/base/logging-small.yaml
- fix `group` field for `core/v1` resources.
- `ignoreDifferences` field for Secret of elastic-system/webhook-server-secret looks unused.
=> argocd-config: fix group field to ignore diff of core resources

argocd-config/base/tenet.yaml, tenet-policy/base/admission/forbid-egress-node.yaml, test/tenant_networkpolicy_test.go, test/testdata/tenant-networkpolicy-node-entity.yaml
This deploys the updated 0.3.0 version of tenet which adds support for specifying forbidden entities in tenant network policies. Accordingly, the NetworkPolicyAdmissionRule for restricting node access has been updated to forbid the relevant entities on top of their IPs.
=> deploy tenet 0.3.0 and add forbidden entities to networkpolicyadmissionrules

neco-admission/base/deployment.yaml
This PR adds toleration for node.cybozu.io/cluster-not-ready since neco-admission needs to be running during L4LB migration. Otherwise the neco upgrade will fail.
=> Add node.cybozu.io/cluster-not-ready to neco-admission

monitoring/base/grafana-operator/dashboards/node-exporter.yaml
When importing a dashboard using the `.spec.url` of `GrafanaDashboard`, a 429 error often occurs, so I replaced it with a url that was hosted independently on gcloud storage.
=> Replace a URL for the node-exporter dashboard.

test/tenant_networkpolicy_test.go
I found a case where `testConnectivity` failed, probably due to a delay in applying `tenant-ingress-cluster-allow`. Therefore, I made a fix to run `testConnectivity` periodically.
In addition, I also modified it to wait for the ubuntu pod in the `testTenantNamespace/2`NS.
=> Fix flaky in testTenantNetworkPolicy

cert-manager/base/kustomization.yaml
part of https://github.com/cybozu-go/neco/issues/1993
=> use patched cert-manager to extend ACME API timeout

rook/base/ceph-object-store.yaml, rook/base/ceph-object-store/cluster.yaml, rook/base/ceph-ssd.yaml, rook/base/ceph-ssd/cluster.yaml, rook/overlays/stage0/kustomization.yaml
A serious regression in stage0 after applying PR#2539.
So we must not upgrade ceph image to 16.2.7.3.
However, we must keep version to 16.2.7.3 in stage0.
It's because downgrading to 16.2.7.2 causes osd crash.
Co-authored-by: Satoru Takeuchi <satoru.takeuchi@gmail.com>
Co-authored-by: Daichi Mukai <daichi-mukai@cybozu.co.jp>
=> rook: prevent osd crash

.circleci/config.yml, test/setup_test.go
Fixed the problem that registration of credentials is required to make neco-apps private.
In addition, the order of setup_test.go has been partially rearranged.
=> Add cred for neco-apps

logging-small/overlays/stage0/kustomization.yaml, logging/overlays/gcp/kustomization.yaml, logging/overlays/stage0/kustomization.yaml, metallb/base/patch.yaml, monitoring/base/cadvisor/daemonset.yaml, topolvm/base/values.yaml
I will add a `neco/reserved_for_meows=true:NoExecute` taint when reserving a node for meows.
Therefore, I have added tolerations to the components required for meows execution.
=> Add tolerations for meows

rook/overlays/stage0/kustomization.yaml
=> rook/ceph: change the number of OSD to 30 in ceph-ssd.

Makefile, meows/overlays/stage0/kustomization.yaml, meows/overlays/stage0/neco-apps-runner.yaml
- Add neco-apps-runner as a RunnerPool to run CI for neco-apps
- Set nodeSelector and tolerations to schedule RunnerPool that running dctest to dedicated nodes. Targets are as follows.
- dctest-runner: for neco-tenant-apps
- neco-apps-runner: for neco-apps
=> Add neco-apps-runner and tolerations/nodeSelector in RunnerPool

test/setup_test.go
Fixed unstable execution of `argocd repocred add` command in setup_test.go.
This command failure event does not seem to have occurred in the test with CircleCI, but was confirmed in the test using GitHubActions.
=> Eventuallyized `argocd repocreds add` command.

.github/actions/dctest/action.yaml, .github/actions/prepare-git/action.yaml, .github/actions/teleport-dns-cname/action.yaml, .github/workflows/ci.yaml, .github/workflows/create-pull-request-release.yaml, .github/workflows/daily.yaml, .github/workflows/dctest-bootstrap.yaml, .github/workflows/dctest-reboot.yaml, .github/workflows/dctest-upgrade.yaml, .github/workflows/dctest-with-neco-feature-branch.yaml, .github/workflows/push-release-tag.yaml, meows/overlays/stage0/neco-apps-runner.yaml
Added workflows for migrating from CircleCI to GitHubActions.
We are currently disabling GitHub Actions in order to use the self-hosted runner, but we will enable these workflows after we make this repository private.
Under `.github/actions`, we place composite actions that cut out the parts common to multiple workflows, such as launching dctest.
The workflow created is described below.
- ci.yaml: The jobs to be executed when pushing to each branch are summarized. (minimum test, dctest-bootstrap and dctest-upgrade. At main merge, create PR for release.)
- daily.yaml: Jobs to be performed daily are summarized. (Delete DNS records, dctest-reboot, dctest-bootstrap and dctest-upgrade)
- dctest-bootstrap.yaml: Workflow for bootstrap testing. Called from daily.yaml and ci.yaml.
- …
=> Add .github/workflows

logging-small/base/loki.yaml, logging-small/base/loki/kustomization.yaml, logging-small/base/loki/values.yaml
I just run `make update-loki-small`.
As far as I confirmed, these changes have no negative impact to loki-small.
https://grafana.com/docs/loki/latest/upgrading/
NOTE: The `loki.yaml` in the `loki` secret has the following difference.
- Use the memberlist instead of in memory store.
- Specify the WAL dir (`loki-small-data` PVC is aleady mounted to `/data`)
```
$ diff -U30 old.yaml new.yaml 
--- old.yaml    2022-06-02 07:56:51.521710582 +0000
+++ new.yaml    2022-06-02 07:56:40.617594931 +0000
@@ -1,45 +1,50 @@
auth_enabled: false
chunk_store_config:
max_look_back_period: 0s
compactor:
retention_delete_delay: 2h
retention_enabled: true
shared_store: filesystem
working_directory: /data/loki/boltdb-shipper-compactor
ingester:
chunk_block_size: 262144
chunk_idle_period: 3m
chunk_retain_period: …
```
=> Loki 2.5.0 (loki-small)
